### DISCUSSION TITLE
terraform-esque module system for pulumi projects

### DISCUSSION THREAD

**Discussion by foxydevloper** [pulumi/pulumi#12567] [Ideas]
I'm using Pulumi YAML, and there's no real way to create components like you can in the other runtimes. I could possibly use a compiler, but it doesn't let you use the pulumi yaml lsp, and creating components using yaml compilers is hard because all the resources are in the same namespace. It'd be nice if there were a way to use other Pulumi projects as if they were resources themselves, like:
```yaml
resources:
  server1:
    type: Pulumi:Project
    properties:
      source: ./server
      name: server 1
  server2:
    type: Pulumi:Project
    properties:
      source: ./server
      name: server 2
outputs:
  server1ip: ${server1.ip}
  server2ip: ${server2.ip}
```
This would give pulumi yaml a dedicated way to create reusable pulumi components, similar to modules in terraform.
Source could even be remote pulumi projects, just like modules in terraform. This would also make cross-language pulumi components possible, instead of them having to be a class in the native language. It would also allow for testing components easily since you can use them just like normal projects.
