### DISCUSSION TITLE
Supporting Bazel for builds

### DISCUSSION THREAD

**Discussion by kylepl** [pulumi/pulumi#14417] [Ideas]
Hi,

I've recently started using Pulumi, through the Java bindings - and given my whole codebase uses Bazel, was hoping to continue do so (rather than say Maven directly).

I've actually got this working OK, by doing something like: `bazel build :first_example_binary_deploy.jar && pulumi up`

With a configuration like:
```
name: first_real_project
runtime:
  name: java
  options:
    binary: /hard/coded/path/first_example_binary_deploy.jar
description: Just trying out Pulumi.
```

This relies upon the the [JAR executor](https://github.com/pulumi/pulumi-java/blob/fe67fea3c13e25c69a8fbacb9167d55546fc444a/pkg/internal/executors/executor_jar.go).

While I have thought about how this would work in cloud deployments, my one musing was there could be a Java executor that would just execute some command to build the JAR, and that can be injected, e.g. I could just run `pulumi up` and have the configuration:

``` 
name: first_real_project
runtime:
  name: java
  options:
    build_command: "bazel build :first_example_binary_deploy.jar"
    binary: /hard/coded/path/first_example_binary_deploy.jar
description: Just trying out Pulumi.
```

This creates a lot of flexibility, while still having `pulumi up` be the interface.

And while I could have left this comment on the pulumi-java repo, I figured similar support might be useful for all languages. My initial musing is that currently the language hosts (like pulumi-language-java) actually couple the building and running of the code, but for some like Bazel (or Buck2, or any language-agnostic build system) - it would seem nice to separate it. Like a pulumi-build-bazel or pulumi-build-maven for building, and then pulumi-run-java for execution - so pulumi-build-bazel could be re-used across languages. Or maybe you just need a pulumi-build-command instead of anything say Bazel specific.

Thoughts?
