### DISCUSSION TITLE
Is it possible to create a workspace (new project) from a template directory using Automation API

### DISCUSSION THREAD

**Discussion by RandyHoffman** [pulumi/pulumi#16910] [Automation API] [answered]
Hi, I am trying to create a new project from a local directory template using the Automation API.  I can do this with the cmdline, so I figured you should be able to do it via Automation, but I can't find a way to create a local workspace (new project) utilizing a template directory.
This command does what I need and am looking to duplicate this utilizing the Automation API.
```
mkdir myProject && cd myProject
pulumi new ../templates/test -g -t -y -n {myProjectName} -d {myProjectDesc}
```
My templates/test/Pulumi.yaml is based on the S3 website example:

```
name: ${PROJECT}
description: ${DESCRIPTION}
runtime: go
backend:
  url: s3://my-pulumi-state
config:
  aws:region: us-east-1
  path: ./www
  indexDocument: index.html
  errorDocument: error.html
template:
```
 
Any help is greatly appreciated!
