### DISCUSSION TITLE
Strange condition with DependsOn - C# / Yaml

### DISCUSSION THREAD

**Discussion by FavitoX** [pulumi/pulumi#17510] [Pulumi in Practice]
Hello! How are you?
I'm testing with the Keycloak provider, and I'm having problems when creating authentication flows. Specifically, I can't create the executionSteps and subflows in the correct order. According to the documentation, to ensure the order, the dependsOn option must be used. I've also tried setting the parallel option to 0 and 1, always with the same result.

My test code is the following, any help you can give me I'll appreciate it! :)

```yaml
name: keycloak
description: Keycloak configuration
runtime: yaml
config:
  keycloak:clientId:
      value: admin-cli
  keycloak:password:
      value: my-super-extra-secret
  keycloak:url:
      value: http://localhost:8081
  keycloak:basePath:
      value: /auth
  keycloak:username:
      value: my-username@contoso.com
  keycloak:realm:
      value: master
  keycloak:tlsInsecureSkipVerify:
      value: true
resources:
  # use the data source
  flow:
    type: keycloak:authentication:Flow
    properties:
      realmId: "my-custom-realm"
      alias: my-flow-alias
  executionOne:
    type: keycloak:authentication:Execution
    properties:
      realmId: "my-custom-realm"
      parentFlowAlias: ${flow.alias}
      authenticator: auth-cookie
      requirement: REQUIRED
  executionTwo:
    type: keycloak:authentication:Execution
    properties:
      realmId: "my-custom-realm"
      parentFlowAlias: ${flow.alias}
      authenticator: identity-provider-redirector
      requirement: REQUIRED
    options:
      dependsOn:
        - ${executionOne}
  executionTree:
    type: keycloak:authentication:Execution
    properties:
      realmId: "my-custom-realm"
      parentFlowAlias: ${flow.alias}
      authenticator: reset-credentials-choose-user
      requirement: REQUIRED
    options:
      dependsOn:
        - ${executionTwo}
  executionFour:
    type: keycloak:authentication:Execution
    properties:
      realmId: "my-custom-realm"
      parentFlowAlias: ${flow.alias}
      authenticator: reset-credential-email
      requirement: REQUIRED
    options:
      dependsOn:
        - ${executionTree}
  executionFive:
    type: keycloak:authentication:Execution
    properties:
      realmId: "my-custom-realm"
      parentFlowAlias: ${flow.alias}
      authenticator: reset-password
      requirement: REQUIRED
    options:
      dependsOn:
        - ${executionFour}
outputs: {}
```

First execution [Sucess] -> pulumi up -r=true -p 1 -y
![image](https://github.com/user-attachments/assets/48db9296-4577-4053-856e-e834856934b2)

Second execution [Sucess] (before delete all from keycloak) -> pulumi up -r=true -p 1 -y
![image](https://github.com/user-attachments/assets/48db9296-4577-4053-856e-e834856934b2)

Third execution [Fail] (before delete all from keycloak) -> pulumi up -r=true -p 1 -y
![image](https://github.com/user-attachments/assets/936d87c5-3453-4d40-a23b-363e080d37ad)

I'm really quite lost, this same thing with Terraform works correctly when introducing dependsOn
