### DISCUSSION TITLE
Error installing Python packages on Apple Silicon (M1)

### DISCUSSION THREAD

**Discussion by mattstratton** [pulumi/pulumi#7357] [Pulumi in Practice] [answered]
When I was trying to create a boilerplate Pulumi project with python (`pulumi new python`) there are errors when building the packages.

specifically:

```
Building wheels for collected packages: grpcio
  Building wheel for grpcio (setup.py) ... -
```

**Comment by mattstratton** [comment, marked as answer]
The good news is, this is an easy fix.

Set two environment variables:

```
export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1
```

and you are good to go!

(source: https://github.com/grpc/grpc/issues/25082#issuecomment-778392661)

**Comment by nimbinatus** [comment]
Note that, as of version 1.39.0, `grpcio` is good to go on M1 without any env variable adjustments: https://github.com/grpc/grpc/issues/25082. Pulumi's package is pulling in the newest version, so double-check your dependencies on any older virtual envs.

**Comment by palladius** [comment]
As per https://github.com/grpc/grpc/issues/30723 
this finally worked for me: `@gnossen , Just an update. I fixed this by updating my python to 3.10.6`

What I did is:
```brew upgrade python
# still no python in my path so I forced it this way
/opt/homebrew/bin/python3  -m venv venv-m1
venv-m1/bin/pip install -r requirements.txt
```

I also updated my package to remind myself for other computers:
```
name: blahblah-python
description: A minimal Google Cloud Python Pulumi program
runtime:
    name: python
    options:
        # /opt/homebrew/bin/python3  -m venv venv-m1
        # venv-m1/bin/pip install -r requirements.txt
        # sul Mac M1 :)
        virtualenv: venv-m1
```
