### ISSUE TITLE
pulumi convert to java fails

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi#10035]
### What happened?

When trying to convert the following program to java, pulumi convert fails

```
name: pulumi-yaml-abac
runtime: yaml
description: A minimal Pulumi YAML program

resources:
  createPolicy:
    type: aws:iam:Policy
    properties:
      policy:
        Fn::ToJSON:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 'lambda:*'
              Resource: 'arn:aws:lambda:*:*:function:*'
              Condition:
                StringEquals:
                  aws:RequestTag/Team:
                    - iamuser-admin
                    - iamuser2-admin
                ForAllValues:StringEquals:
                  aws:TagKeys:
                    - Team

```

### Steps to reproduce

Using the above program, run the command:

```
$ pulumi convert --language java --out java-demo
```

### Expected Behavior

Conversion to succeed

### Actual Behavior

```
pulumi convert --language java --out java-demo
error: Failed to configure executor, tried: jar, maven, gradle, jbang

error: failed to load language plugin java: could not read plugin [/usr/local/bin/pulumi-language-java] stdout: EOF
```

### Additional context

I did initialize an empty project in the java-demo folder and the conversion succeeded BUT it just dumped the code to a file in the root called `MyStack.java` - this doesn't follow the correct template for a Java program

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
