### ISSUE TITLE
[codegen/dotnet] `pulumi convert` outputs unexpected InputParameters when language-specific settings exist

### ISSUE THREAD

**Issue by kpitzen** [pulumi/pulumi#10042]
### What happened?

When the provider schema contains a `Schema.Language.Name` value, codegen is currently not renaming the corresponding `InputParameter` in accordance with that specification (despite the corresponding resource expecting that name in its `<resource>Args` constructor).

### Steps to reproduce

Create an AWS IAM Policy resource in `yaml` with a corresponding JSON policy document:
```yaml
# Pulumi.yaml
resources:
  policy:
    type: aws:iam:Policy
    properties:
      path: /
      description: My test policy
      policy:
        Fn::ToJSON:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource:
                - arn:aws:s3:::some-aws-bucket/*
              Condition:
                Foo:
                  Bar:
                    - iamuser-admin
                    - iamuser2-admin
                Baz:
                  Qux:
                    - iamuser3-admin
```

### Expected Behavior

`pulumi convert` outputs corresponding C# code with correctly-named arguments:
```csharp
// MyStack.cs
class MyStack : Stack
{
    public MyStack()
    {
        var createPolicy = new Aws.Iam.Policy("createPolicy", new Aws.Iam.PolicyArgs
        {
            Path = "/",
            Description = "My test policy",
            PolicyDocument = JsonSerializer.Serialize(new Dictionary<string, object?>
            {
                { "Version", "2012-10-17" },
                { "Statement", new[]
                    {
                        new Dictionary<string, object?>
                        {
                            { "Action", new[]
                                {
                                    "s3:GetObject",
                                }
                             },
                            { "Effect", "Allow" },
                            { "Resource", "arn:aws:s3:::some-aws-bucket/*" },
                            { "Condition", new Dictionary<string, object?>
                            {
                                { "Foo", new Dictionary<string, object?>
                                {
                                    { "Bar", new[]
                                        {
                                            "iamuser-admin",
                                            "iamuser2-admin",
                                        }
                                     },
                                } },
                                { "Baz", new Dictionary<string, object?>
                                {
                                    { "Qux", new[]
                                        {
                                            "iamuser3-admin",
                                        }
                                     },
                                } },
                            } },
                        },
                    }
                 },
            }),
        });
    }

}

```

### Actual Behavior

`pulumi convert` creates invalid C# code with a misnamed argument for `new Aws.Iam.PolicyArgs`
```csharp
// MyStack.cs
class MyStack : Stack
{
    public MyStack()
    {
        var createPolicy = new Aws.Iam.Policy("createPolicy", new Aws.Iam.PolicyArgs
        {
            Path = "/",
            Description = "My test policy",
            Policy = JsonSerializer.Serialize(new Dictionary<string, object?>
            {
                { "Version", "2012-10-17" },
                { "Statement", new[]
                    {
                        new Dictionary<string, object?>
                        {
                            { "Action", new[]
                                {
                                    "s3:GetObject",
                                }
                             },
                            { "Effect", "Allow" },
                            { "Resource", "arn:aws:s3:::some-aws-bucket/*" },
                            { "Condition", new Dictionary<string, object?>
                            {
                                { "Foo", new Dictionary<string, object?>
                                {
                                    { "Bar", new[]
                                        {
                                            "iamuser-admin",
                                            "iamuser2-admin",
                                        }
                                     },
                                } },
                                { "Baz", new Dictionary<string, object?>
                                {
                                    { "Qux", new[]
                                        {
                                            "iamuser3-admin",
                                        }
                                     },
                                } },
                            } },
                        },
                    }
                 },
            }),
        });
    }

}

```

### Versions used

```shell
CLI          
Version      3.36.0-alpha.1656738344+69a1002f.dirty
Go Version   go1.18.3
Go Compiler  gc
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
