### ISSUE TITLE
Go program-gen doesn't reassign err when already defined from temp variables

### ISSUE THREAD

**Issue by Zaid-Ajaj** [pulumi/pulumi#10048]
### What happened?

Generating a Go program with the following criteria creates an invalid Go program
 - Single resource
 - Uses temporary variables
 - Doesn't export anything related to the single resource

### Steps to reproduce

Take this Pulumi.yaml and then run `pulumi convert --language go --out output` 
```yaml
name: pulumi-yaml-abac
runtime: yaml
description: A minimal Pulumi YAML program

resources:
  createPolicy:
    type: aws:iam:Policy
    properties:
      policy:
        Fn::ToJSON:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 'lambda:*'
              Resource: 'arn:aws:lambda:*:*:function:*'
```

### Expected Behavior

The generated resource assignment looks like this
```go
_, err = iam.NewPolicy(ctx, "createPolicy", &iam.PolicyArgs{
	Policy: pulumi.String(json0),
})
```

### Actual Behavior

The generated go code looks like this
```go
_, err := iam.NewPolicy(ctx, "createPolicy", &iam.PolicyArgs{
	Policy: pulumi.String(json0),
})
```
