### ISSUE TITLE
Dotnet program-gen should emit output-versioned function invokes

### ISSUE THREAD

**Issue by Zaid-Ajaj** [pulumi/pulumi#10104]
### What happened?

The current way dotnet programgen handles function invokes is faulty and can easily result in programs that don't compile. This is because we use the plain version of function invokes (i.e `InvokeAsync`) and then we wrap that inside `Output.Create`.

This easily breaks when you want to use a property  output of function invoke A as input for function invoke B

### Steps to reproduce

Run `pulumi convert` against the following YAML program:
```yaml
name: YamlTest
runtime: yaml
description: A static website hosted on AWS S3
variables:
  vpcId:
    Fn::Invoke:
      Function: aws:ec2:getVpc
      Arguments:
        default: true
      Return: id
  subnetIds:
    Fn::Invoke:
      Function: aws:ec2:getSubnetIds
      Arguments:
        vpcId: ${vpcId}
      Return: ids
outputs:
  subnets: ${subnetIds}
```

### Expected Behavior

It should generate
```cs
using System.Collections.Immutable;
using Pulumi;
using Aws = Pulumi.Aws;

class MyStack : Stack
{
    public MyStack()
    {
        var vpcId = Aws.Ec2.GetVpc.Invoke(new Aws.Ec2.GetVpcInvokeArgs
        {
            Default = true,
        }).Apply(invoke => invoke.Id);

        var subnetIds = Aws.Ec2.GetSubnetIds.Invoke(new Aws.Ec2.GetSubnetIdsInvokeArgs
        {
            VpcId = vpcId,
        }).Apply(invoke => invoke.Ids);

        this.Subnets = subnetIds;
    }

    [Output("subnets")]
    public Output<ImmutableArray<string>> Subnets { get; set; }
}
```

### Actual Behavior

It generates
```cs
using Pulumi;
using Aws = Pulumi.Aws;

class MyStack : Stack
{
    public MyStack()
    {
        var vpcId = Output.Create(Aws.Ec2.GetVpc.InvokeAsync(new Aws.Ec2.GetVpcArgs
        {
            Default = true,
        })).Apply(invoke => invoke.Id);
        var subnetIds = Output.Create(Aws.Ec2.GetSubnetIds.InvokeAsync(new Aws.Ec2.GetSubnetIdsArgs
        {
            VpcId = vpcId,
        })).Apply(invoke => invoke.Ids);
        this.Subnets = subnetIds;
    }

    [Output("subnets")]
    public Output<string> Subnets { get; set; }
}
```

### Versions used

Pulumi v3.53.3

### Additional context

The generated intermediate PCL 
```
vpcId = invoke("aws:ec2/getVpc:getVpc", {
        default = true
}).id

subnetIds = invoke("aws:ec2/getSubnetIds:getSubnetIds", {
        vpcId = vpcId
}).ids

output subnets {
        __logicalName = "subnets"
        value = subnetIds
}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
