### ISSUE TITLE
Dotnet program-gen should output less noisy dictionaries using property initializers

### ISSUE THREAD

**Issue by Zaid-Ajaj** [pulumi/pulumi#10113]
### What happened?

The generated dictionaries by dotnet program-gen today are noisy: too many curly brackets and too much indentation

### Steps to reproduce

Run `pulumi convert --language csharp --out dist` against the following YAML program
```yaml
name: YamlTest
runtime: yaml
description: Dictionaries
resources:
  policyJson:
    type: aws:iam:Policy
    properties:
      policy:
        Fn::ToJSON:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 'lambda:*'
              Resource: 'arn:aws:lambda:*:*:function:*'

outputs:
  policy: ${policyJson.name}
```

### Expected Behavior

Should generate:
```csharp
using System.Collections.Generic;
using System.Text.Json;
using Pulumi;
using Aws = Pulumi.Aws;

class MyStack : Stack
{
    public MyStack()
    {
        var policyJson = new Aws.Iam.Policy("policyJson", new Aws.Iam.PolicyArgs
        {
            PolicyDocument = JsonSerializer.Serialize(new Dictionary<string, object?>
            {
                ["Version"] = "2012-10-17",
                ["Statement"] = new[]
                {
                    new Dictionary<string, object?>
                    {
                        ["Effect"] = "Allow",
                        ["Action"] = "lambda:*",
                        ["Resource"] = "arn:aws:lambda:*:*:function:*",
                    },
                },
            }),
        });
        this.Policy = policyJson.Name;
    }

    [Output("policy")]
    public Output<string> Policy { get; set; }
}

```

### Actual Behavior

It generates
```csharp
using System.Collections.Generic;
using System.Text.Json;
using Pulumi;
using Aws = Pulumi.Aws;

class MyStack : Stack
{
    public MyStack()
    {
        var policyJson = new Aws.Iam.Policy("policyJson", new Aws.Iam.PolicyArgs
        {
            PolicyDocument = JsonSerializer.Serialize(new Dictionary<string, object?>
            {
                { "Version", "2012-10-17" },
                { "Statement", new[]
                    {
                        new Dictionary<string, object?>
                        {
                            { "Effect", "Allow" },
                            { "Action", "lambda:*" },
                            { "Resource", "arn:aws:lambda:*:*:function:*" },
                        },
                    }
                 },
            }),
        });
        this.Policy = policyJson.Name;
    }

    [Output("policy")]
    public Output<string> Policy { get; set; }
}
```

### Additional context

Intermediate PCL
```
resource policyJson "aws:iam/policy:Policy" {
        __logicalName = "policyJson"
        policy = toJSON({
                "Version" = "2012-10-17",
                "Statement" = [{
                        "Effect" = "Allow",
                        "Action" = "lambda:*",
                        "Resource" = "arn:aws:lambda:*:*:function:*"
                }]
        })
}

output policy {
        __logicalName = "policy"
        value = policyJson.name
}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
