### ISSUE TITLE
Automation API - Set structured configuration

### ISSUE THREAD

**Issue by Werner-Swart-83** [pulumi/pulumi#10136]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I have the following structure:

```
ServiceResources:ExecutionModel:
    UseUpperStackReferences: true
ServiceResources:UpperStackReferenceModel:
    ClientStackNames:
    - client-ppc001
    CoreStackName: core-integration_europe01
    GlobalStackName: global-integration
    RegionalStackNames:
    - regional-integration_westeurope01
```

I am following this [example](https://github.com/pulumi/pulumi/issues/6700) and created the following:

```
var stack =  await LocalWorkspace.CreateOrSelectStackAsync(inlineProgram);

await stack.SetAllConfigAsync(new Dictionary<string, ConfigValue>
{
    {"ServiceResources:ExecutionModel" , new ConfigValue("{\"UseUpperStackReferences\": \"true\"}")},
    {"ServiceResources:UpperStackReferenceModel" , new ConfigValue("{\"ClientStackNames\": [\"client-ppc001\"], \"CoreStackName\": \"core-integration_europe01\", \"GlobalStackName\": \"global-integration\", \"RegionalStackNames\": [\"regional-integration_westeurope01\"]}")}
});
```

But then I get the following error:
```Error: Configuration 'ServiceResources:ExecutionModel' value '{"UseUpperStackReferences": "true"}' is not a valid```

This is the config it generated:

```
config:
  ServiceResources:ExecutionModel: '{"UseUpperStackReferences": "true"}'
  ServiceResources:UpperStackReferenceModel: '
  {"ClientStackNames": ["client-ppc001"],
    "CoreStackName": "core-integration_europe01", 
    "GlobalStackName": "global-integration",
    "RegionalStackNames": ["regional-integration_westeurope01"]}'
```

How do I structure my config files using this library?

### Affected area/feature

Automation API
