### ISSUE TITLE
Report 1 error instead of 2 when YAML projects fail

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#10226]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Small usability enhancement - consider reporting 1 error not 2 when a YAML project contains one errror.

### Reproduce

- ```pulumi new aws-yaml```

- Edit Pulumi.yaml:

```
name: yaml-err
runtime: yaml
description: A minimal AWS Pulumi YAML program

resources:
  # Create an AWS resource (S3 Bucket)
  my-bucket:
    type: aws:s3:Bucket

outputs:
  # Export the name of the bucket
  bucketName: ${my-bucket.i}  # *** .i is a deliberate error ***
```

- `pulumi preview`

### Current behavior

```
Previewing update (dev)

View Live: https://app.pulumi.com/t0yv0/yaml-err/dev/previews/8d548f2e-94ec-4e16-acdb-d76097ce075b

     Type                 Name          Plan       Info
 +   pulumi:pulumi:Stack  yaml-err-dev  create     2 errors
 
Diagnostics:
  pulumi:pulumi:Stack (yaml-err-dev):
    error: i does not exist on my-bucket
    
      on Pulumi.yaml line 12:
      12:   bucketName: ${my-bucket.i}
    
    Existing properties are: id, acl, arn, urn, tags and 22 others
    error: an unhandled error occurred: failed to evaluate template
 ```

### Desired behavior

```
Previewing update (dev)

View Live: https://app.pulumi.com/t0yv0/yaml-err/dev/previews/8d548f2e-94ec-4e16-acdb-d76097ce075b

     Type                 Name          Plan       Info
 +   pulumi:pulumi:Stack  yaml-err-dev  create     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (yaml-err-dev):
    error: i does not exist on my-bucket
    
      on Pulumi.yaml line 12:
      12:   bucketName: ${my-bucket.i}
    
    Existing properties are: id, acl, arn, urn, tags and 22 others
```

The error message is helpful it is just confusing that Pulumi reports 2 errors instead of 1. "failed to evaluate template" may retain if it is meaningful.
