### ISSUE TITLE
[codegen/python] Non idiomatic default values for config

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#10268]
The following YAML:

```yaml
configuration:
  containerPort:
    type: Number
    default: 80
  cpu:
    type: Number
    default: 512
  memory:
    type: Number
    default: 128
```

Currently emits this:

```python
config = pulumi.Config()
container_port = config.get_float("containerPort")
if container_port is None:
    container_port = 80
cpu = config.get_float("cpu")
if cpu is None:
    cpu = 512
memory = config.get_float("memory")
if memory is None:
    memory = 128
```

It should emit this:

```python
config = pulumi.Config()
container_port = config.get_int("containerPort") or 80
cpu = config.get_int("cpu") or 512
memory = config.get_int("memory") or 128
````
