### ISSUE TITLE
Azure DevOps Pipeline Fails

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi#10262]
### What happened?

Running Azure Devops Pipeline is suddenly failing  pulumi cli when using a windows runner image and installing the v3.37.0 of Pulumi.
Running with ubuntu does not have a problem.

The following error is thrown and the pipeline fails:
(See pipeline code below.)
```
Starting: Pulumi Setup
==============================================================================
Task         : Pulumi Azure Pipelines Task
Description  : Azure Pipelines task extension for running Pulumi apps.
Version      : 1.0.16
Author       : Pulumi
Help         : Join us on Slack at https://slack.pulumi.com./
==============================================================================
Downloading: https://get.pulumi.com/releases/sdk/pulumi-v3.37.0-windows-x64.zip
Extracting archive
C:\Windows\system32\chcp.com 65001
Active code page: 65001
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\4f043eaf-28c9-470d-b6dd-ece43ddbf47d', 'D:\a\_temp\c0b62a5c-431b-4bed-885c-e05f7f525230')"
##[error]Pulumi installation failed with error 'Directory does not exist: D:\a\_temp\c0b62a5c-431b-4bed-885c-e05f7f525230\pulumi\bin'.
```

**Pipeline code:**
```
variables:
  # Override which service connection to use if environment variable is set.
  serviceConnection: REDACTED
  # Override which Pulumi Organization to use if environment variable is set.
  pulumiOrg: REDACTED
  # Returns the root branch name. e.g. for branch "dev/goo" this is "goo"
  pulumiStack: $(Build.SourceBranchName) 

trigger:
- dev/*

pool:
  # vmImage: ubuntu-latest
  vmImage: windows-latest

# # Use Pulumi's published python image. It contains the pulumi command line and a python environment.
# container: pulumi/pulumi-python:latest

steps:
# Just some debugging stuff
- script: |
    pulumi version
    echo "serviceConnection: $(serviceConnection)"
    echo "pulumiOrg: $(pulumiOrg)"
    echo "pulumiStack: $(pulumiStack)"
  displayName: 'Check Environment'

- task: Pulumi@1
  inputs:
    azureSubscription: '$(serviceConnection)'
    stack: "$(pulumiOrg)/$(pulumiStack)"
    command: 'preview'
    cwd: '.' # unnecessary, but wanted to note that there is a cwd argument that can be used to drive where the pulumi up is run.
    createStack: 'true' # create the stack if it does not already exist
  displayName: 'Pulumi Setup'
```

### Steps to reproduce

Run an Azure devops pipeline using the `windows-latest` image using the Pulumi Task and see the error.

### Expected Behavior

The pipeline should run as expected.

### Actual Behavior

Pipeline fails

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
