### ISSUE TITLE
pulumi creates venv in cwd when it is already specified in `Pulumi.yaml`

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#10343]
### What happened?

while working on #9175 

when `src` was current working directory, pulumi made a new `venv` dir inside `./src` which was the current working directory rather than inside the root level that was specified.

```
# Pulumi.yaml
name: prog-aws-python
main: src
runtime:
  name: python
  options:
    virtualenv: ./venv
```

dir structure
```
./
./Pulumi.yaml
./venv/.
./src/.
./src/requirements.txt
./src/__main__.py
```

### Steps to reproduce

^

### Expected Behavior

not create venv

### Actual Behavior

create env

### Versions used

master

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
