### ISSUE TITLE
pulumi convert runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jamesianberry** [pulumi/pulumi#10448]
### What happened?

Consistently get the following result whether I choose to convert to python or csharp:
```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.38.0
Go Version:       go1.19
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/homebrew/Cellar/go/1.19/libexec/src/runtime/debug/stack.go:24 +0x64
main.panicHandler()
        /private/tmp/pulumi-20220816-66818-1yift85/pkg/cmd/pulumi/main.go:29 +0x34
panic({0x10275a880, 0x10385f090})
        /opt/homebrew/Cellar/go/1.19/libexec/src/runtime/panic.go:884 +0x204
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.(*importer).importExpr(0x140003def60?, {0x102a51530?, 0x1400094b350?}, {0x102a51b98?, 0x0?})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/pulumi-yaml@v0.5.4/pkg/pulumiyaml/codegen/load.go:397 +0x558
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.(*importer).importBuiltin(0x1400052b688, {0x102a5cd80?, 0x14000661280?})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/pulumi-yaml@v0.5.4/pkg/pulumiyaml/codegen/load.go:268 +0x214
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.(*importer).importExpr(0x102731000?, {0x102a51468?, 0x14000661280?}, {0x0?, 0x0?})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/pulumi-yaml@v0.5.4/pkg/pulumiyaml/codegen/load.go:432 +0x430
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.(*importer).importVariable(0x1400052b688, {{{0x102a48dc0, 0x140001f9660}, 0x140001f9480, {0x102a55db0, 0x140009433b0}}, 0x14000385ae0, {0x102a51468, 0x14000661280}})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/pulumi-yaml@v0.5.4/pkg/pulumiyaml/codegen/load.go:577 +0x9c
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.(*importer).importTemplate(0x1400052b688, 0x14000a70410)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/pulumi-yaml@v0.5.4/pkg/pulumiyaml/codegen/load.go:871 +0x8b8
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.ImportTemplate(0x1028d36c0?, {0x102a54690?, 0x1400083e440?})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/pulumi-yaml@v0.5.4/pkg/pulumiyaml/codegen/load.go:929 +0x94
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.ConvertTemplateIL(0x5000?, {0x102a51c60?, 0x14000995c40?})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/pulumi-yaml@v0.5.4/pkg/pulumiyaml/codegen/convert.go:52 +0xf8
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.EjectProgram(0x14000a70410?, {0x102a51c60?, 0x14000995c40})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/pulumi-yaml@v0.5.4/pkg/pulumiyaml/codegen/convert.go:63 +0x30
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.Eject({0x1400005a054?, 0x17?}, {0x0, 0x0})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/pulumi-yaml@v0.5.4/pkg/pulumiyaml/codegen/eject.go:50 +0x1e8
main.newConvertCmd.func1(0xe?, {0x14000660d00?, 0x1400052bd58?, 0x100f7ae34?})
        /private/tmp/pulumi-20220816-66818-1yift85/pkg/cmd/pulumi/convert.go:83 +0x25c
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0x14000929b80?, {0x14000795940, 0x0, 0x4})
        /private/tmp/pulumi-20220816-66818-1yift85/sdk/go/common/util/cmdutil/exit.go:112 +0x38
github.com/spf13/cobra.(*Command).execute(0x14000929b80, {0x14000795900, 0x4, 0x4})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x4ac
github.com/spf13/cobra.(*Command).ExecuteC(0x1400065ac80)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /private/tmp/pulumi-20220816-66818-1yift85/pkg/cmd/pulumi/main.go:48 +0x3c
```

### Steps to reproduce

Attempt to convert the following Pulumi YAML to Python using: `pulumi convert --language python --out ../3-groups-and-members`
```
name: 3-groups-and-members
runtime: yaml
description: Create groups for role assignments and ACLs and manage members

configuration:
  env:
    default: Dev

resources:
  adls-owner-gg:
    type: azuread:Group
    properties:
      displayName: GG-Azure-DataHub${env}-ADLS-Owner
      description: ADH ADLS Storage Blob Data Owners
      owners:
        - ${current.objectId}
      preventDuplicateNames: true
      securityEnabled: true
  adls-contributor-gg:
    type: azuread:Group
    properties:
      displayName: GG-Azure-DataHub${env}-ADLS-Contributor
      description: ADH ADLS Storage Blob Data Contributors
      members:
        - ${adf3-sp.id}
        - ${adf-sp.id}
        - ${databricks-user.id}
        - ${datahub-group.id}
      owners:
        - ${current.objectId}
      preventDuplicateNames: true
      securityEnabled: true
  adls-reader-gg:
    type: azuread:Group
    properties:
      displayName: GG-Azure-DataHub${env}-ADLS-Reader
      description: ADH ADLS Storage Blob Data Readers
      members:
        - ${sql-sp.id}
        - ${srch-sp.id}
        - ${databricks-user.id}
        - ${raw-sp.id} # should this rather be assigned to the raw container?
      owners:
        - ${current.objectId}
      preventDuplicateNames: true
      securityEnabled: true
  adls-contributor-transient-gg:
    type: azuread:Group
    properties:
      displayName: GG-Azure-DataHub${env}-ADLS-Contributor-transient
      description: ADH ADLS Storage Blob Data Contributors (transient)
      members:
        - ${transient-sp.id}
      owners:
        - ${current.objectId}
      preventDuplicateNames: true
      securityEnabled: true
  adls-reader-datamart-gg:
    type: azuread:Group
    properties:
      displayName: GG-Azure-DataHub${env}-ADLS-Reader-datamart
      description: ADH ADLS Storage Blob Data Readers (datamart)
      members:
        - ${adb-sql-sp.id}
      owners:
        - ${current.objectId}
      preventDuplicateNames: true
      securityEnabled: true
  adls-reader-structured-gg:
    type: azuread:Group
    properties:
      displayName: GG-Azure-DataHub${env}-ADLS-Reader-structured
      description: ADH ADLS Storage Blob Data Readers (structured)
      members:
        - ${adb-sql-sp.id}
      owners:
        - ${current.objectId}
      preventDuplicateNames: true
      securityEnabled: true

variables:
  readme:
    Fn::ReadFile: ./README.md
  current:
    Fn::Invoke:
      Function: azuread:getClientConfig
      Arguments: {}
  #resource lookup for azuread is not supported in YAML
  pipeline-sp:
    id: 37f52b79-c26b-435c-8307-88f9d5758f8b
    name: svc_ADH_ADO_Pipeline
  adf3-sp:
    id: d2872c91-3f34-44ad-ad0c-d48ddeb999be
    name: adh-dev3-adf
  adf-sp:
    id: f7a8eb5a-c123-4826-abc0-9b5e24087f33
    name: adh-dev-adf
  databricks-user:
    id: 207bd53b-94b2-47de-b9c8-f86a805f8c72
    name: DataBricks - ADH (DEV)
  datahub-group:
    id: 3024c599-ab6d-4f0c-a840-b2a2d7f08666
    name: GG-Azure-DataHubDEV-Contributor
  sql-sp:
    id: 491b0af8-51c9-4a8a-8676-196c309215e9
    name: devadhaesqlsvr
  srch-sp:
    id: 3703bf72-f345-4f21-86a6-3d8214b8373a
    name: dev-adh-mirnaddress-ae-srch
  raw-sp:
    id: 91a55e8f-ba86-499b-9c11-47bd5cff6e72
    name: svc_ADH_ADB_to_ADLS_Raw_DEV
  adb-sql-sp:
    id: 60ed73d0-55d6-4372-9d01-a699750f0040
    name: svc_ADH_ADB_SQL_to_ADLS_Dev
  transient-sp:
    id: 5ffdc3e1-d126-4608-b35b-0229589ecf80
    name: svc_ADH_ADB_to_ADLS_Trnsnt_DEV

outputs:
  readme: ${readme}
  ADLS Owner Group Object ID: ${adls-owner-gg.objectId}
  ADLS Contributor Group Object ID: ${adls-contributor-gg.objectId}
  ADLS Reader Group Object ID: ${adls-reader-gg.objectId}
  ADLS Contributor (transient) Group Object ID: ${adls-contributor-transient-gg.objectId}
  ADLS Reader (datamart) Group Object ID: ${adls-reader-datamart-gg.objectId}
  ADLS Reader (structured) Group Object ID: ${adls-reader-structured-gg.objectId}
```

### Expected Behavior

expected the target directory to be created and populated with the project converted from yaml to python (or csharp)

### Actual Behavior

although the target directory was created, no files were generated in it as expected

### Output of `pulumi about`

CLI          
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME     VERSION
azuread  unknown
yaml     unknown

Host     
OS       darwin
Version  12.5
Arch     arm64

This project is written in yaml

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jamesianberry
User           jamesianberry
Organizations  jamesianberry, furo-demo

No dependencies found

Pulumi locates its logs in /var/folders/k3/lj1b0c7d5xb1d2_t_pnsv7t40000gn/T/ by default
warning: Failed to get information about the current stack: No current stack

### Additional context

Have successfully converted another project from yaml to python in the same way today

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
