### ISSUE TITLE
pulumi convert breaks with eks example

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi#10466]
The following eks YAML program breaks pulumi convert:

```
name: yaml-test
runtime: yaml
description: A minimal Pulumi YAML program
resources:
  provider:
    type: pulumi:providers:kubernetes
    properties:
      enableServerSideApply: true
    options:
      version: 3.20.2
  cluster:
    type: eks:Cluster
    properties:
      version: "1.21"
    options:
      provider: ${provider}
  patch1:
    type: kubernetes:apps/v1:DeploymentPatch
    properties:
      metadata:
        name: "coredns"
        namespace: "kube-system"
        annotations:
          pulumi.com/patchForce: "true"
      spec:
        template:
          containers:
            name: "coredns"
            # Use the version retrieved earlier as the image tag here!
            image: "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/coredns:v1.8.7-eksbuild.1"
    options:
      provider: ${provider}
```

This produces output that looks as follows:

```
, storageClassName = union(none, string), volumeMode = union(none, string), volumeName = union(none, string)}, annotated(0x140031f3080)))}, annotated(0x140031f3840)))}, annotated(0x140031f3b00))), fc = union(none, object({fsType = union(none, string), lun = union(int, none), readOnly = union(bool, none), targetWWNs = union(list(string), none), wwids = union(list(string), none)}, annotated(0x14003224380))), flexVolume = union(none, object({driver = union(none, string), fsType = union(none, string), options = union(map(string), none), readOnly = union(bool, none), secretRef = union(none, object({name = union(none, string)}, annotated(0x140030a1800)))}, annotated(0x14003224e80))), flocker = union(none, object({datasetName = union(none, string), datasetUUID = union(none, string)}, annotated(0x14003225640))), gcePersistentDisk = union(none, object({fsType = union(none, string), partition = union(int, none), pdName = union(none, string), readOnly = union(bool, none)}, annotated(0x14003225d40))), gitRepo = union(none, object({directory = union(none, string), repository = union(none, string), revision = union(none, string)}, annotated(0x14003234540))), glusterfs = union(none, object({endpoints = union(none, string), path = union(none, string), readOnly = union(bool, none)}, annotated(0x14003234c80))), hostPath = union(none, object({path = union(none, string), type = union(none, string)}, annotated(0x140032352c0))), iscsi = union(none, object({chapAuthDiscovery = union(bool, none), chapAuthSession = union(bool, none), fsType = union(none, string), initiatorName = union(none, string), iqn = union(none, string), iscsiInterface = union(none, string), lun = union(int, none), portals = union(list(string), none), readOnly = union(bool, none), secretRef = union(none, object({name = union(none, string)}, annotated(0x140030a1800))), targetPortal = union(none, string)}, annotated(0x14003244100))), name = union(none, string), nfs = union(none, object({path = union(none, string), readOnly = union(bool, none), server = union(none, string)}, annotated(0x14003244f40))), persistentVolumeClaim = union(none, object({claimName = union(none, string), readOnly = union(bool, none)}, annotated(0x14003245580))), photonPersistentDisk = union(none, object({fsType = union(none, string), pdID = union(none, string)}, annotated(0x14003245a80))), portworxVolume = union(none, object({fsType = union(none, string), readOnly = union(bool, none), volumeID = union(none, string)}, annotated(0x14003250080))), projected = union(none, object({defaultMode = union(int, none), sources = union(list(object({configMap = union(none, object({items = union(list(object({key = union(none, string), mode = union(int, none), path = union(none, string)}, annotated(0x140031c1700))), none), name = union(none, string), optional = union(bool, none)}, annotated(0x14003250980))), downwardAPI = union(none, object({items = union(list(object({fieldRef = union(none, object({apiVersion = union(none, string), fieldPath = union(none, string)}, annotated(0x14002f440c0))), mode = union(int, none), path = union(none, string), resourceFieldRef = union(none, object({containerName = union(none, string), divisor = union(none, string), resource = union(none, string)}, annotated(0x14002f446c0)))}, annotated(0x140031cd280))), none)}, annotated(0x14003250f00))), secret = union(none, object({items = union(list(object({key = union(none, string), mode = union(int, none), path = union(none, string)}, annotated(0x140031c1700))), none), name = union(none, string), optional = union(bool, none)}, annotated(0x14003251480))), serviceAccountToken = union(none, object({audience = union(none, string), expirationSeconds = union(int, none), path = union(none, string)}, annotated(0x14003251bc0)))}, annotated(0x14003251fc0))), none)}, annotated(0x140032624c0))), quobyte = union(none, object({group = union(none, string), readOnly = union(bool, none), registry = union(none, string), tenant = union(none, string), user = union(none, string), volume = union(none, string)}, annotated(0x14003262dc0))), rbd = union(none, object({fsType = union(none, string), image = union(none, string), keyring = union(none, string), monitors = union(list(string), none), pool = union(none, string), readOnly = union(bool, none), secretRef = union(none, object({name = union(none, string)}, annotated(0x140030a1800))), user = union(none, string)}, annotated(0x14003263c80))), scaleIO = union(none, object({fsType = union(none, string), gateway = union(none, string), protectionDomain = union(none, string), readOnly = union(bool, none), secretRef = union(none, object({name = union(none, string)}, annotated(0x140030a1800))), sslEnabled = union(bool, none), storageMode = union(none, string), storagePool = union(none, string), system = union(none, string), volumeName = union(none, string)}, annotated(0x14003290e80))), secret = union(none, object({defaultMode = union(int, none), items = union(list(object({key = union(none, string), mode = union(int, none), path = union(none, string)}, annotated(0x140031c1700))), none), optional = union(bool, none), secretName = union(none, string)}, annotated(0x14003291c40))), storageos = union(none, object({fsType = union(none, string), readOnly = union(bool, none), secretRef = union(none, object({name = union(none, string)}, annotated(0x140030a1800))), volumeName = union(none, string), volumeNamespace = union(none, string)}, annotated(0x140032a8640))), vsphereVolume = union(none, object({fsType = union(none, string), storagePolicyID = union(none, string), storagePolicyName = union(none, string), volumePath = union(none, string)}, annotated(0x140032a9000)))}, annotated(0x140032a94c0))), none)}, annotated(0x140032b6d40)))}, annotated(0x1400342aa00)))), annotated(0x1400046c800));
```

**Comment by iwahbe** [comment]
It looks like the `spec.templates.containers` property does not exist on `kubernetes:apps/v1:DeploymentPatch`.

We see `kubernetes:apps/v1:DeploymentPatch.spec` defined here:
https://github.com/pulumi/pulumi-kubernetes/blob/3f10bd024190d7674cf0f2b086c182b6f95668c7/provider/cmd/pulumi-resource-kubernetes/schema.json#L60220-L60223

Then `kubernetes:apps/v1:DeploymentSpecPatch.template` defined here:
https://github.com/pulumi/pulumi-kubernetes/blob/3f10bd024190d7674cf0f2b086c182b6f95668c7/provider/cmd/pulumi-resource-kubernetes/schema.json#L6866-L6869

Finally, `kubernetes:core/v1:PodTemplateSpecPatch` is defined here:
https://github.com/pulumi/pulumi-kubernetes/blob/3f10bd024190d7674cf0f2b086c182b6f95668c7/provider/cmd/pulumi-resource-kubernetes/schema.json#L32221-L32233

As you can see, it has properties `metadata` and `spec`, but not `containers`.

**Comment by stack72** [comment]
@lblackstone is this something missed in the schema?

**Comment by lblackstone** [comment]
It looks like the YAML program is missing a `spec` key (i.e., the program is invalid).

It should look like this:
```yaml
name: yaml-test
runtime: yaml
description: A minimal Pulumi YAML program
resources:
  provider:
    type: pulumi:providers:kubernetes
    properties:
      enableServerSideApply: true
    options:
      version: 3.20.2
  cluster:
    type: eks:Cluster
    properties:
      version: "1.21"
    options:
      provider: ${provider}
  patch1:
    type: kubernetes:apps/v1:DeploymentPatch
    properties:
      metadata:
        name: "coredns"
        namespace: "kube-system"
        annotations:
          pulumi.com/patchForce: "true"
      spec:
        template:
          spec:
            containers:
              name: "coredns"
              # Use the version retrieved earlier as the image tag here!
              image: "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/coredns:v1.8.7-eksbuild.1"
    options:
      provider: ${provider}
```
