### ISSUE TITLE
Dependencies of component providers aren't downloaded

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi#10521]
Given the following YAML program, which uses the Synced Folder component (a package built from [pulumi-component-provider-ts-boilerplate](https://github.com/pulumi/pulumi-component-provider-ts-boilerplate)):

```
name: yaml-synced-folder-test
runtime: yaml

resources:
  bucket:
    type: aws:s3:Bucket

  bucket-folder:
    type: synced-folder:index:S3BucketFolder
    properties:
      path: ./site   # You'll need a folder with some files here.
      bucketName: ${bucket.bucket}
```

... the initial update fails because the provider's resource plugin wasn't downloaded:

```
pulumi up
Previewing update (dev)

View Live: https://app.pulumi.com/cnunciato/yaml-synced-folder-test/dev/previews/bbb32df0-7f6d-4640-97f7-ed34baa7b9d6

Downloading plugin: 38.06 MiB / 38.06 MiB [=========================] 100.00% 4s
[resource plugin synced-folder-0.0.8] installing
Downloading plugin: 126.54 MiB / 126.54 MiB [=======================] 100.00% 9s
[resource plugin aws-5.13.0] installing

     Type                                   Name                         Plan       Info
 +   pulumi:pulumi:Stack                    yaml-synced-folder-test-dev  create     
 +   ├─ aws:s3:Bucket                       bucket                       create     
 +   ├─ synced-folder:index:S3BucketFolder  bucket-folder                create     
     └─ pulumi:providers:aws                default_5_12_1                          1 error
 
Diagnostics:
  pulumi:providers:aws (default_5_12_1):
    error: no resource plugin 'pulumi-resource-aws' found in the workspace at version v5.12.1 or on your $PATH, install the plugin using `pulumi plugin install resource aws v5.12.1`
```

This is presumably happening because the current version of pulumi-aws is `5.13` (which does get downloaded), whereas the latest synced-folder was built against `pulumi-aws@5.12.1`. The following is a snippet from my local `yarn.lock` that shows this:

```
"@pulumi/aws@^5.0.0":
  version "5.12.1"
  resolved "https://registry.yarnpkg.com/@pulumi/aws/-/aws-5.12.1.tgz#6fdae06c825e852392fc63f4dbe835626acbe36f"
  integrity sha512-QRuqXgNnDNWQZu0xcGHhbgLLF+dYyd9wt2dfsIy5UeP8nExaWmWv0DS4AhWO9KaaUGH+ifqsmX7RdfAzDmVBPw==
  dependencies:
    "@pulumi/pulumi" "^3.0.0"
    aws-sdk "^2.0.0"
    builtin-modules "3.0.0"
    mime "^2.0.0"
    read-package-tree "^5.2.1"
    resolve "^1.7.1"
```

To repro, ensure you don't have `5.12.1` installed already, then run `pulumi up`. I would expect Pulumi to download 5.12.1 and for the update to work without requiring an additional manual install.
