### ISSUE TITLE
TS ProgramGen introduces unnecessary applies for array indexing

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#10543]
### What happened?

Running `pulumi convert` on a Pulumi YAML produced unnecessarily messy output.

### Steps to reproduce

Run `pulumi convert` on 
```yaml
name: test-acm
runtime: yaml
description: A minimal AWS Pulumi YAML program

variables:
  zoneId:
    Fn::Invoke:
      Function: aws:route53:getZone
      Arguments:
        name: "example.com"
        privateZone: false
      Return: id
resources:
  exampleCertificate:
    type: aws:acm:Certificate
    properties:
      domainName: "example.com"
      validationMethod: "DNS"
  certValidation:
    type: aws:route53:Record
    properties:
      name: ${exampleCertificate.domainValidationOptions[0].resourceRecordName}
      records:
        - ${exampleCertificate.domainValidationOptions[0].resourceRecordValue}
      ttl: 60
      type: ${exampleCertificate.domainValidationOptions[0].resourceRecordType}
      zoneId: ${zoneId}
  certCertificateValidation:
    type: aws:acm:CertificateValidation
    properties:
      certificateArn: ${exampleCertificate.arn}
      validationRecordFqdns:
        - ${certValidation.fqdn}
outputs:
  certificateArn: ${certCertificateValidation.certificateArn}
```

### Expected Behavior

We should generate the following (or something equivalent):
```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const zoneId = aws.route53.getZone({
    name: "example.com",
    privateZone: false,
}).then(invoke => invoke.id);
const exampleCertificate = new aws.acm.Certificate("exampleCertificate", {
    domainName: "example.com",
    validationMethod: "DNS",
});
const certValidation = new aws.route53.Record("certValidation", {
    name: exampleCertificate.domainValidationOptions[0].resourceRecordName,
    records: [exampleCertificate.domainValidationOptions[0].resourceRecordValue],
    ttl: 60,
    type: exampleCertificate.domainValidationOptions[0].resourceRecordType,
    zoneId: zoneId,
});
const certCertificateValidation = new aws.acm.CertificateValidation("certCertificateValidation", {
    certificateArn: exampleCertificate.arn,
    validationRecordFqdns: [certValidation.fqdn],
});
export const certificateArn = certCertificateValidation.certificateArn;
```

### Actual Behavior

We generate
```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const zoneId = aws.route53.getZone({
    name: "example.com",
    privateZone: false,
}).then(invoke => invoke.id);
const exampleCertificate = new aws.acm.Certificate("exampleCertificate", {
    domainName: "example.com",
    validationMethod: "DNS",
});
const certValidation = new aws.route53.Record("certValidation", {
    name: exampleCertificate.domainValidationOptions.apply(domainValidationOptions => domainValidationOptions[0].resourceRecordName),
    records: [exampleCertificate.domainValidationOptions.apply(domainValidationOptions => domainValidationOptions[0].resourceRecordValue)],
    ttl: 60,
    type: exampleCertificate.domainValidationOptions.apply(domainValidationOptions => domainValidationOptions[0].resourceRecordType).apply((x) => aws.route53.recordtype.RecordType[x]),
    zoneId: zoneId,
});
const certCertificateValidation = new aws.acm.CertificateValidation("certCertificateValidation", {
    certificateArn: exampleCertificate.arn,
    validationRecordFqdns: [certValidation.fqdn],
});
export const certificateArn = certCertificateValidation.certificateArn;
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
