### ISSUE TITLE
`pulumi convert` generates invalid types for some resources

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi#10664]
Given the following valid YAML program:

```yaml
name: yaml-test
runtime: yaml

configuration:
  domain:
    type: String
    default: example.com
  subdomain:
    type: String
    default: www

variables:
  domainName: ${subdomain}.${domain}
  zone:
    Fn::Invoke:
      Function: aws:route53:getZone
      Arguments:
        name: ${domain}

resources:

  certificate:
    type: aws:acm:Certificate
    properties:
      domainName: ${domainName}
      validationMethod: DNS

  certificateValidation:
    type: aws:route53:Record
    properties:
      name: ${certificate.domainValidationOptions[0].resourceRecordName}
      type: ${certificate.domainValidationOptions[0].resourceRecordType}
      zoneId: ${zone.zoneId}
      ttl: 60
      records:
        - ${certificate.domainValidationOptions[0].resourceRecordValue}
```

... `pulumi convert` fails because of a codegen error:

```
$ pulumi convert --out my-go-program --language go

main.go:56:81: expected operand, found 'return'
main.go:61:1: missing ',' in composite literal
main.go:63:1: expected operand, found '}'
main.go:65:1: expected ';', found 'if'
```

Internal thread for some additional context: https://pulumi.slack.com/archives/C027PR8QZPH/p1662664787503099
