### ISSUE TITLE
Provide latest development builds

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#10728]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would be great to be able to find the latest "dev" build of Pulumi and install it in a CI context. It does not particularly matter how the latest dev build is defined (last commit on master perhaps)?

We have a precedent of doing it this way in pulumi/templates:

```
https://github.com/pulumi/templates/blob/master/.github/workflows/cron.yml#L62

  - if: matrix.pulumi-version == 'dev'
        name: Get Latest Dev Version of Pulumi
        shell: bash
        run: |
          echo "DEV_PULUMI_VERSION=$(curl -sSL "http://registry.npmjs.org/-/package/@pulumi/pulumi/dist-tags" | jq -r .dev)" >> $GITHUB_ENV
   - if: matrix.pulumi-version == 'dev'
        name: Install Latest Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1
        with:
          pulumi-version: ${{ env.DEV_PULUMI_VERSION }}
```

But that does not seem to work great after the migration to BORS.
