### ISSUE TITLE
Fatal error when running pulumi convert with Azure Native provider

### ISSUE THREAD

**Issue by scottslowe** [pulumi/pulumi#10726]
### What happened?

I have a working YAML program that uses the Azure Native provider to stand up an AKS (managed Kubernetes) cluster in a new virtual network. When I attempt to use `pulumi convert` to generate code in another language, I get a fatal error.

Specifically, what I've tried so far is:
`pulumi convert --generate-only --language typescript --out ../kubernetes-azure-typescript`
`pulumi convert --generate-only --language go --out ../kubernetes-azure-go`

I have not tried generating Python, Java, or C#. The output of the command is pasted below in "Additional Context".

### Steps to reproduce

Create a YAML program using the Azure Native provider that creates a virtual network, subnets, within that virtual network, and a managed Kubernetes cluster. Verify this YAML program works with `pulumi preview` and `pulumi up`.

Try to generate code in another language with `pulumi convert`. A fatal error is reported.

### Expected Behavior

I expected the `pulumi convert` command to generate code in the specified language.

### Actual Behavior

The `pulumi convert` command crashed with a fatal error.

### Output of `pulumi about`

```
CLI
Version      3.39.1
Go Version   go1.19
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  unknown
yaml          unknown

Host
OS       darwin
Version  12.5.1
Arch     arm64

This project is written in yaml

Current Stack: test

Found no resources associated with test

Found no pending operations associated with test

Backend
Name           pulumi.com
URL            https://app.pulumi.com/scottslowe
User           scottslowe
Organizations  scottslowe

No dependencies found

Pulumi locates its logs in /var/folders/kp/nk2y9x1x13n6v6r_d1wqhztm0000gn/T/ by default
```

### Additional context

```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.39.1
Go Version:       go1.19
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            fatal: A failure has occurred: unexpected builtin type *ast.FromBase64Expr

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.19/libexec/src/runtime/debug/stack.go:24 +0x64
main.panicHandler()
	/private/tmp/pulumi-20220902-19159-3jcy6y/pkg/cmd/pulumi/main.go:29 +0x34
panic({0x1021481e0, 0x140001d1890})
	/opt/homebrew/Cellar/go/1.19/libexec/src/runtime/panic.go:884 +0x204
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
	/private/tmp/pulumi-20220902-19159-3jcy6y/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Failf({0x101bd5f3f?, 0x140001d17a0?}, {0x140005e4cf0?, 0x1025272b8?, 0x1400024c380?})
	/private/tmp/pulumi-20220902-19159-3jcy6y/sdk/go/common/util/contract/fail.go:30 +0xbc
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.(*importer).importBuiltin(0x140005e5678?, {0x12b582af0?, 0x140008246c0?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/pulumi-yaml@v0.5.5/pkg/pulumiyaml/codegen/load.go:373 +0x182c
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.(*importer).importExpr(0x102205480?, {0x102526b38?, 0x140008246c0?}, {0x0?, 0x0?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/pulumi-yaml@v0.5.5/pkg/pulumiyaml/codegen/load.go:455 +0x430
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.(*importer).importVariable(0x140005e5678, {{{0x10251e4c0, 0x14000635000}, 0x14000634f20, {0x10252b598, 0x14000bceff0}}, 0x1400014e680, {0x102526b38, 0x140008246c0}})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/pulumi-yaml@v0.5.5/pkg/pulumiyaml/codegen/load.go:600 +0x9c
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.(*importer).importTemplate(0x140005e5678, 0x14000bbaf70)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/pulumi-yaml@v0.5.5/pkg/pulumiyaml/codegen/load.go:900 +0x8b8
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.ImportTemplate(0x1023a8460?, {0x102529e78?, 0x1400014e7e0?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/pulumi-yaml@v0.5.5/pkg/pulumiyaml/codegen/load.go:958 +0x94
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.ConvertTemplateIL(0x5000?, {0x102527380?, 0x140008247c0?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/pulumi-yaml@v0.5.5/pkg/pulumiyaml/codegen/convert.go:52 +0xf8
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.EjectProgram(0x14000bbaf70?, {0x102527380?, 0x140008247c0})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/pulumi-yaml@v0.5.5/pkg/pulumiyaml/codegen/convert.go:63 +0x30
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.Eject({0x1400005c004?, 0x1e?}, {0x0, 0x0})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/pulumi-yaml@v0.5.5/pkg/pulumiyaml/codegen/eject.go:50 +0x1e8
main.newConvertCmd.func1(0xe?, {0x140008dab00?, 0x14000a51d58?, 0x100a445e4?})
	/private/tmp/pulumi-20220902-19159-3jcy6y/pkg/cmd/pulumi/convert.go:83 +0x25c
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0x14000baf180?, {0x1400015d900, 0x0, 0x5})
	/private/tmp/pulumi-20220902-19159-3jcy6y/sdk/go/common/util/cmdutil/exit.go:112 +0x38
github.com/spf13/cobra.(*Command).execute(0x14000baf180, {0x1400015d8b0, 0x5, 0x5})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x4ac
github.com/spf13/cobra.(*Command).ExecuteC(0x14000afc280)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/private/tmp/pulumi-20220902-19159-3jcy6y/pkg/cmd/pulumi/main.go:48 +0x3c
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by scottslowe** [comment]
Same fatal error occurs when trying to generate Python.

**Comment by scottslowe** [comment]
Also tested on a second machine and got the same fatal error.

Here's `pulumi about` on the second system I tested:

```
CLI
Version      3.39.3
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  unknown
yaml          unknown

Host
OS       darwin
Version  12.5.1
Arch     arm64

This project is written in yaml

Current Stack: test

Found no resources associated with test

Found no pending operations associated with test

Backend
Name           pulumi.com
URL            https://app.pulumi.com/scottslowe
User           scottslowe
Organizations  scottslowe

No dependencies found

Pulumi locates its logs in /var/folders/c_/1pdwtg4j5zx4dvx5t6qp9v180000gn/T/ by default
```

**Comment by scottslowe** [comment]
Additional information: I can reproduce the error with versions 1.75.0, 1.77.0, and 1.78.0 of the Azure Native provider.

**Comment by scottslowe** [comment]
Here's the YAML code I'm using that generates this panic:
```
name: ${PROJECT}
description: ${DESCRIPTION}
runtime: yaml
template:
  description: A YAML document to create a Kubernetes cluster on Azure
  important: true
  config:
    azure-native:region:
      default: westus2
      description: The Azure region in which to create the cluster
configuration:
  numWorkerNodes:
    type: Number
    default: 3
  azureLocation:
    type: String
    default: westus2
  prefixForDns:
    type: String
    default: pulumi
  kubernetesVersion:
    type: String
    default: 1.24.3
  azureVmSize:
    type: String
    default: Standard_DS2_v2
  mgmtGroupId:
    type: String
  sshPubKey:
    type: String
resources:
  # Create a new resource group
  resourceGroup:
    type: azure-native:resources:ResourceGroup
    properties:
      location: ${azureLocation}
      resourceGroupName: aks-rg
  # Create a new virtual network
  virtualNetwork:
    type: azure-native:network:VirtualNetwork
    properties:
      addressSpace:
        addressPrefixes:
          - 10.0.0.0/16
      location: ${azureLocation}
      resourceGroupName: ${resourceGroup.name}
      subnets:
        - addressPrefix: 10.0.0.0/24
          name: aks-subnet-1
        - addressPrefix: 10.0.1.0/24
          name: aks-subnet-2
        - addressPrefix: 10.0.2.0/24
          name: aks-subnet-3
      virtualNetworkName: aks-vnet
  # Create a managed cluster
  managedCluster:
    type: azure-native:containerservice:ManagedCluster
    properties:
      aadProfile:
        enableAzureRBAC: true
        managed: true
        adminGroupObjectIDs:
          - ${mgmtGroupId}
      addonProfiles: {}
      agentPoolProfiles:
        - count: ${numWorkerNodes}
          enableNodePublicIP: false
          mode: System
          name: systempool
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: ${azureVmSize}
      dnsPrefix: ${prefixForDns}
      enableRBAC: true
      identity:
        type: SystemAssigned
      kubernetesVersion: ${kubernetesVersion}
      linuxProfile:
        adminUsername: azureuser
        ssh:
          publicKeys:
            - keyData: ${sshPubKey}
      location: ${azureLocation}
      networkProfile:
        networkPlugin: azure
        networkPolicy: azure
        serviceCidr: 10.96.0.0/16
        dnsServiceIP: 10.96.0.10
      resourceGroupName: ${resourceGroup.name}
      resourceName: aks-cluster
variables:
  # Get the credentials for the AKS cluster created above
  aksCredentials:
    Fn::Invoke:
      Function: azure-native:containerservice:listManagedClusterUserCredentials
      Arguments:
        resourceGroupName: ${resourceGroup.name}
        resourceName: ${managedCluster.name}
  actualKubeConfig:
    Fn::FromBase64: ${aksCredentials.kubeconfigs[0].value}
outputs:
    # Export the Kubeconfig of the cluster
    clusterName: ${managedCluster.name}
    kubeconfig: ${actualKubeConfig}
```
