### ISSUE TITLE
convert - `configuration`, `resources`, `outputs` blocks are being written to generated `Pulumi.yaml` files

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#10795]
### What happened?

`pulumi convert....` is writing `configuration`, `resources`, `outputs` blocks, from the `pulumi-yaml` source Pulumi.yaml file, to the outputted Pulumi.yaml files.

### Steps to reproduce

Execute below yaml in a Pulumi yaml project
```yaml
name: yaml-config-convert
runtime: yaml
description: A minimal Pulumi YAML program
configuration:
  val: 
    type: String
resources:
  bucket:
    type: aws:s3:Bucket
outputs:
  bucketName: ${bucket.bucket}
```

### Expected Behavior

Generated Pulumi.yaml files only contain relevant information to the generated code/project.

### Actual Behavior

Generated Pulumi.yaml files contain yaml blocks from source Pulumi.yaml file.

```yaml
name: yaml-config-convert
runtime: go
description: A minimal Pulumi YAML program
configuration:
  val:
    type: String
outputs:
  bucketName: ${bucket.bucket}
resources:
  bucket:
    type: aws:s3:Bucket
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
