### ISSUE TITLE
Conversion fails on resources with inputs named `type`

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi#10814]
### What happened?

Given the following YAML program:

```yaml
name: some-program
runtime: yaml

resources:
  resource-group:
    type: azure-native:resources:ResourceGroup

  account:
    type: azure-native:storage:StorageAccount
    properties:
      resourceGroupName: ${resource-group.name}
      kind: StorageV2
      sku:
        name: Standard_LRS

  container:
    type: azure-native:storage:BlobContainer
    properties:
      accountName: ${account.name}
      resourceGroupName: ${resource-group.name}
      publicAccess: None

  blob:
    type: azure-native:storage:Blob
    properties:
      accountName: ${account.name}
      resourceGroupName: ${resource-group.name}
      containerName: ${container.name}
      type: block
```

... `pulumi convert` fails rendering invalid code -- for example, with Go:

```
$ pulumi convert --language go --out to-go

...

_, err = storage.NewBlob(ctx, "blob", &storage.BlobArgs{
AccountName: account.Name,
ResourceGroupName: resourceGroup.Name,
ContainerName: container.Name,
Type: %!v(PANIC=Format method: runtime error: invalid memory address or nil pointer dereference),
})
if err != nil {
return err
}
return nil
})
}
: 37:7: expected operand, found '%' (and 5 more errors)
```

```typescript
// ...

const blob = new azure_native.storage.Blob("blob", {
    accountName: account.name,
    resourceGroupName: resourceGroup.name,
    containerName: container.name,
    type: %!v(PANIC=Format method: runtime error: invalid memory address or nil pointer dereference),
});
```

```python
# ...

blob = azure_native.storage.Blob("blob",
    account_name=account.name,
    resource_group_name=resource_group.name,
    container_name=container.name,
    type=%!v(PANIC=Format method: runtime error: invalid memory address or nil pointer dereference))
```

It looks like it's either the existence of the `type` property on `blob` or that the `type` property expects an enum that's causing this. 

### Steps to reproduce

See above.

### Expected Behavior

Conversion completes and produces a valid program.

### Actual Behavior

Conversion fails and/or produces an invalid program.

### Output of `pulumi about`

```
CLI
Version      3.40.1
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  unknown
yaml          unknown

Host
OS       darwin
Version  12.5.1
Arch     x86_64

This project is written in yaml
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
