### ISSUE TITLE
Cannot up dynamically created stacks using 3.40.2

### ISSUE THREAD

**Issue by johnkors** [pulumi/pulumi#10862]
### What happened?

3.40.0 can up dynamically created stacks (eg. pr pull request)
3.40.2 errors when up'-ing a dynamically created stack

### Steps to reproduce

We're creating stacks dynamically using github actions:

```
    - name: Create new pr stack
      run: |
        pulumi stack init --non-interactive --logtostderr "${{ env.STACK_NAME }}" --copy-config-from myorg/test
      working-directory: ./infra
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      continue-on-error: true # init fails if exists
    - name: Init some configs
      run: |
        pulumi config cp --non-interactive --logtostderr --stack myorg/test --dest "${{ env.STACK_NAME }}" // ex: "pull68"
      working-directory: ./infra
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    - uses: pulumi/actions@v3
      id: pulumi
      with:
        command: up
        stack-name: ${{ env.STACK_NAME }}
        work-dir: ./infra
        pulumi-version: 3.40.2
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
```

Errorlog:

```
Run pulumi/actions@v3
  with:
    command: up
    stack-name: myorg/pull68
    work-dir: ./infra
    comment-on-pr: false
    github-token: ***
..snip
Error: code: -2
 stdout: 
 stderr: Command failed with exit code 255: pulumi stack select myorg/pull68 --non-interactive
error: could not get cloud url: could not load current project: 1 error occurred:
	* #/config: expected string or null, but got object
```

### Expected Behavior

Being able to `up` the stack.

### Actual Behavior

Errors:

```
 stderr: Command failed with exit code 255: pulumi stack select myorg/pull68 --non-interactive
error: could not get cloud url: could not load current project: 1 error occurred:
	* #/config: expected string or null, but got object
```

### Output of `pulumi about`

Can be provided if necessary

### Additional context

Reverting to pulumi-version: 3.40.0 fixes the issue and works as expected.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
