### ISSUE TITLE
Resource Option Import not respected in YAML

### ISSUE THREAD

**Issue by rdbartram** [pulumi/pulumi#10898]
### What happened?

When using resource options within Pulumi YAML, pulumi doesnt seem to even try to perform a lookup and instead just jumps to creation

### Steps to reproduce

``` yaml
{
  "resources": {
    "bob": {
      "properties": {
        "password": "P@ssw0rd1234",
        "userPrincipalName": "bob@xxx.onmicrosoft.com",
        "givenName": "bob",
        "displayName": "Bob"
      },
      "type": "azuread:index/user:User",
      "options": {
        "import": "bc6993d9-fe39-4f02-b32d-104e8e0a621b",
        "deleteBeforeReplace": false,
        "ignoreChanges": [
          "password"
        ],
        "protect": false,
        "retainOnDelete": false
      }
    }
  },
  "variables": {},
  "outputs": {}
}
```
pulumi up

### Expected Behavior

Type                    Name                    Plan       
     pulumi:pulumi:Stack     psyamlpulumi.ad-ad-dev             
 =   ├─ azuread:index:User   bob                     import

### Actual Behavior

Type                    Name                    Plan       
     pulumi:pulumi:Stack     psyamlpulumi.ad-ad-dev             
 +   ├─ azuread:index:User   bob                     create 

### Output of `pulumi about`

CLI          
Version      3.40.2
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME     VERSION
azuread  unknown
yaml     unknown

Host     
OS       alpine
Version  3.14.8
Arch     x86_64

This project is written in yaml

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/rdbartram
User           rdbartram
Organizations  rdbartram, worxspace

No dependencies found

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current stack

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
