### ISSUE TITLE
Templates error when they include objects with default values

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#10892]
### What happened?

A user attempted to create a template with an object as a default value.

### Steps to reproduce

Try to run `pulumi new` on this template:
```yaml
name: ${PROJECT}
description: ${DESCRIPTION}
runtime: nodejs
template:
  description: A minimal AWS TypeScript Pulumi program
  config:
    aws:defaultTags:
      default:
        tags:
          Tag1: value1
          Tag2: value2
```

### Expected Behavior

It should just work.

### Actual Behavior

```
X pulumi new ..                                               
error: yaml: unmarshal errors:
  line 9: cannot unmarshal !!map into string
```

### Output of `pulumi about`

CLI          
Version      3.41.0-dev.0
Go Version   go1.19
Go Compiler  gc

Host     
OS       darwin
Version  12.4
Arch     x86_64

### Additional context

Originated in the community slack. See https://pulumi-community.slack.com/archives/C84L4E3N1/p1664546902094349.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
