### ISSUE TITLE
Allow structured config to be iterable in typescript

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#10931]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When using structured config, it's possible to get the keys of the config but not each object.

Example:

With the following in the stack config:

```yml
config:
  myproject:mystackconfig:
    vars:
      var1: var1value
      var2: var2value
      secret1:
        secure: AAABALZIAzDaE45MbdO08w/QMHK6CE4hssidMK70pyYt6hIFHpKeq0mBNic=
```
and then the following code:

```typescript
import * as pulumi from "@pulumi/pulumi";

interface myConfig {
    vars: pulumi.Output<string>[];
}

const config = new pulumi.Config();
const mystackconfig = config.requireObject<myConfig>("myStackConfig");

for(let setting in mystackconfig.vars) {
    console.log(setting)
}
```

produces the following:

```
var1
var2
secret1
```

but it would be nice to be able to do something like:

```typescript
for(let setting of mystackconfig.vars) {
   if (pulumi.isSecret(setting)) {
    console.log("Is a secret");
  }
}
```

But currently getting this error message:

```
error: Running program '/Users/piers/go/src/github.com/pierskarsenbarg/secrets' failed with an unhandled exception:
    TypeError: mystackconfig.vars is not iterable
```

### Affected area/feature

Config
