### ISSUE TITLE
How to transform annotations in ConfigFile

### ISSUE THREAD

**Issue by shiyuhang0** [pulumi/pulumi#11025]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

How to transform annotations in ConfigFile. My scenario is as follows, but I find the transformations is error

The full yaml:
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-letsencrypt-cert
  namespace: cert-manager
spec:
  secretName: gateway-letsencrypt-secret
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "tidb-admin.*"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
```

I want to alter the `reflector.v1.k8s.emberstack.com/reflection-allowed` according to some conditions. but don't know how to configure it :
```
transformations: [
        metadata.withNamespace(nsName),
        (obj, opts) => {
          if(stack === "dev") {
            obj.spec.secretTemplate.annotations.reflector.v1.k8s.emberstack.com/reflection-allowed = "true";
          }
        },
```
<img width="922" alt="image" src="https://user-images.githubusercontent.com/52435083/195971479-00762c4a-b98f-4aa0-a65a-e0878acfef05.png">
