### ISSUE TITLE
`pulumi convert` to Go generates incorrect code and `go.mod` for component usage

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#11427]
Creating the default `pulumi new serverless-aws-yaml` and then `pulumi convert --language go --out ./go` fails with this:

```
Installing dependencies...

go: finding module for package github.com/pulumi/pulumi-aws-apigateway/sdk/apigateway/index
go: finding module for package github.com/pulumi/pulumi-aws-apigateway/sdk/apigateway
demo2 imports
        github.com/pulumi/pulumi-aws-apigateway/sdk/apigateway: module github.com/pulumi/pulumi-aws-apigateway/sdk@latest found (v0.0.10), but does not contain package github.com/pulumi/pulumi-aws-apigateway/sdk/apigateway
demo2 imports
        github.com/pulumi/pulumi-aws-apigateway/sdk/apigateway/index: module github.com/pulumi/pulumi-aws-apigateway/sdk@latest found (v0.0.10), but does not contain package github.com/pulumi/pulumi-aws-apigateway/sdk/apigateway/index
error: installing dependencies failed; rerun manually to try again, then run `pulumi up` to perform an initial deployment: `go mod tidy` failed to install dependencies: exit status 1

```

The code it generates is also wrong in referencing `github.com/pulumi/pulumi-aws-apigateway/sdk/apigateway/index` and in using unqualified references to types from `apigateway` like `RouteArgs`.

```go
package main

import (
	"encoding/json"

	"github.com/pulumi/pulumi-aws-apigateway/sdk/apigateway"
	"github.com/pulumi/pulumi-aws-apigateway/sdk/apigateway/index"
	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws"
	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/iam"
	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/lambda"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		tmpJSON0, err := json.Marshal(map[string]interface{}{
			"Version": "2012-10-17",
			"Statement": []map[string]interface{}{
				map[string]interface{}{
					"Action": "sts:AssumeRole",
					"Effect": "Allow",
					"Principal": map[string]interface{}{
						"Service": "lambda.amazonaws.com",
					},
				},
			},
		})
		if err != nil {
			return err
		}
		json0 := string(tmpJSON0)
		role, err := iam.NewRole(ctx, "role", &iam.RoleArgs{
			AssumeRolePolicy: pulumi.String(json0),
			ManagedPolicyArns: pulumi.StringArray{
				pulumi.String("arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"),
			},
		})
		if err != nil {
			return err
		}
		fn, err := lambda.NewFunction(ctx, "fn", &lambda.FunctionArgs{
			Runtime: pulumi.String("python3.8"),
			Handler: pulumi.String("handler.handler"),
			Role:    role.Arn,
			Code:    pulumi.NewFileArchive("./function"),
		})
		if err != nil {
			return err
		}
		api, err := apigateway.NewRestAPI(ctx, "api", &apigateway.RestAPIArgs{
			Routes: []RouteArgs{
				&RouteArgs{
					Path:      "/",
					LocalPath: "www",
				},
				&RouteArgs{
					Path:         "/date",
					Method:       index.MethodGET,
					EventHandler: fn.ID(),
				},
			},
		})
		if err != nil {
			return err
		}
		ctx.Export("url", api.Url)
		return nil
	})
}
```

The YAML source code from the default template is this:

```yaml
name: demo2
description: A serverless app on AWS API Gateway and Lambda
runtime: yaml
resources:
    # An execution role to use for the Lambda function
    role:
        type: aws:iam:Role
        properties:
            assumeRolePolicy:
                fn::toJSON:
                    Version: 2012-10-17
                    Statement:
                        - Action: sts:AssumeRole
                          Effect: Allow
                          Principal:
                            Service: lambda.amazonaws.com
            managedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    # A Lambda function to invoke
    fn:
        type: aws:lambda:Function
        properties:
            runtime: python3.8
            handler: handler.handler
            role: ${role.arn}
            code:
                fn::fileArchive: ./function
    # A REST API to route requests to HTML content and the Lambda function
    api:
        type: aws-apigateway:RestAPI
        properties:
            routes:
                - path: /
                  localPath: www
                - path: /date
                  method: GET
                  eventHandler: ${fn}
outputs:
    # The URL at which the REST API will be served.
    url: ${api.url}
```
