### ISSUE TITLE
upsert: true option leads to dataloss, when stack can't be selected/decrypted

### ISSUE THREAD

**Issue by jalmeroth** [pulumi/pulumi#11502]
### What happened?

Hi 👋,

I have a Pulumi project, where a Azure BlobStorage is used as backend and a Azure Keyvault as secret provider. We use a Service Principal for pipeline execution.

The `Pulumi.yaml` project file has the following config:
```YAML
backend:
  url: azblob://<container>?storage_account=<storage_account>
```

The `Pulumi.bootstrap.yaml` stack file has the following config:
```YAML
secretsprovider: azurekeyvault://<keyvault_name>.vault.azure.net/keys/<key_name>
```

Our Github `workflow.yaml` looks like this:
```YAML
# - name: Azure Login
#   if: ${{ inputs.azure_keyvault_auth_via_cli == 'true' }}
#   uses: azure/login@v1
#   with:
#     creds: ${{ secrets.AZURE_CREDENTIALS }}
- uses: pulumi/actions@v3
  env:
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    ARM_LOCATION_NAME: ${{ inputs.azure_location }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    AZURE_LOCATION_NAME: ${{ inputs.azure_location }}
    AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    AZURE_KEYVAULT_AUTH_VIA_CLI: ${{ inputs.azure_keyvault_auth_via_cli }}
  with:
    stack-name: ${{ inputs.stack_name }}
    command: ${{ inputs.pulumi_command }}
    work-dir: ${{ inputs.pulumi_workdir }}
    upsert: true
    diff: true
```

In a situation, where the Azure CLI is not available (commented out) and the env variable `AZURE_KEYVAULT_AUTH_VIA_CLI=true` pulumi is probably not able to select/decrypt the stack and overwrites the existing stack in the remote backend.

When setting `upsert: false` you will get the following error message:
> error: getting secrets manager: open keeper azurekeyvault://<keyvault_name>.vault.azure.net/keys/<key_name>: failed to Dial default KeyVault: Invoking Azure CLI failed with the following error: ERROR: Please run 'az login' to setup account.

### Steps to reproduce

See issue description for general setup. Set `AZURE_KEYVAULT_AUTH_VIA_CLI=true` and `upsert: true` while azure cli is not available. Run a `preview` action.

### Expected Behavior

Display the same error message as when `upsert: false` is set.

### Actual Behavior

Pulumi creates a new stack even if the command is `preview` and wants to re-create all existing resources.

### Additional context

We realized that not defining `AZURE_KEYVAULT_AUTH_VIA_CLI` and not having azure cli installed works as expected. So the backend can be found and the stack can be decrypted.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
