### ISSUE TITLE
Support a config hierarchy

### ISSUE THREAD

**Issue by Frassle** [pulumi/pulumi#11550]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Extend config to more hierarchy than just the project. We expect to have a key like hierarchy in the project that will define other sources of data to fetch. Very early thinking but something like:

```
hierarchy:
 - type: vault
   host: {org:vault_host}
   token: 
     secure: <encrypted vault token, at project level by project passphrase secrets>
 - type: http
   url: https://coolcats.company/api/config
   authorization:{vault:keys[“coolcats”]}
 - type: file
   path: ../data/data.yaml
```
