### ISSUE TITLE
How to set a list of strings for a key in config-map

### ISSUE THREAD

**Issue by jalmeroth** [pulumi/pulumi#11649]
Howdy! I'm trying to find a way to set a list of strings for a key via the [pulumi/actions](https://github.com/pulumi/actions) `config-map` property. This is a follow-up on the [discussion in Slack](https://app.slack.com/client/T85C88L30/C019YSXN04B).

I tried to set it with: `"some-key":{"value":["some-value-a","some-value-b"]}` which leads to a comma-separated string `some-value-a,some-value-b` in the Pulumi.stack.yaml.

I also tried to send: `{"some-other-key":[{"value":"some-other-value-a"},{"value":"some-other-value-b"}]}` which leads to a string `undefined`  in the Pulumi.stack.yaml.

What I would like to see is:

```YAML
<pulumi-project>:some-key:
  - some-value-a
  - some-value-b
```

This could be defined via cli with `pulumi config set --path "some-key[0]" "some-value-a"` but how do you do it via automation api?

**Comment by AaronFriel** [comment]
@jalmeroth thanks for reporting this. If I have this right, you have an @pulumi/actions job like so:

```

      - uses: pulumi/actions@v3
        with:
          config-map:
            some-key:
              value: 
                - some-value-a
                - some-value-b
```

And when the program runs, this is being turned into a string, or something like that?

**Comment by jalmeroth** [comment]
> @jalmeroth thanks for reporting this. If I have this right, you have an @pulumi/actions job like so:
> 
> ```
>       - uses: pulumi/actions@v3
>         with:
>           config-map:
>             some-key:
>               value: 
>                 - some-value-a
>                 - some-value-b
> ```
> 
> And when the program runs, this is being turned into a string, or something like that?

@AaronFriel thanks for digging into this.

No, I think one needs to provide a string here, otherwise it breaks the GH Workflow syntax.

What we provide looks like this:
```yaml
- uses: pulumi/actions@v3
  with:
    config-map: "some-key": {"value": ["some-value-a", "some-value-b"]}
  "some-other-key": [{"value": "some-other-value-a"}, {"value": "some-other-value-b"}]
```

**Comment by jalmeroth** [comment]
Ha, I finally found it! The problematic code is [here](https://github.com/pulumi/pulumi/blob/v3.50.0/sdk/nodejs/automation/localWorkspace.ts#L469-L477).

This line uses Template literals to convert the list of strings into a comma-seperated str:
```typescript
args = [...args, secretArg, `${key}=${value.value}`];
```

I'm not into Typescript at all, but I wrote some pseudo-code that could fix the issue:
```typescript
    async setAllConfig(stackName: string, config: ConfigMap): Promise<void> {
        let args = ["config", "set-all", "--stack", stackName];
        for (const [key, value] of Object.entries(config)) {
            const secretArg = value.secret ? "--secret" : "--plaintext";
            if (Array.isArray(value.value)) {
                args = [...args, "--path"];
                value.value.forEach((value, index) => {
                    args.push(secretArg);
                    args.push(`"${key}[${index}]"=${value}`);
                });
            } else {
                args = [...args, secretArg, `${key}=${value.value}`];
            }
        }

        await this.runPulumiCmd(args);
    }
```

**Comment by c-brooks** [comment]
Hello 👋 any updates on this? Currently, we're able to work around this issue by using comma-separated string, but it would be great to be able to pass in an actual array to the config-map.
```yaml
      - uses: pulumi/actions@v5
        with:
          command: up
          upsert: true
          config-map: "{ S3TargetArns: { value: "arn1,arn2,arn3", secret: false } }"
```
