### ISSUE TITLE
Pulumi plugin 403 error

### ISSUE THREAD

**Issue by Moon1706** [pulumi/pulumi#11743]
### What happened?

When I try to use [`@pulumiverse/time`](https://github.com/pulumiverse/pulumi-time) in my code
```js
import * as time from '@pulumiverse/time';
const saKeyRotationTime = new time.Rotating('gcp-sa-key-rotation', {
  rotationDays: 60,
});
```
and apply changes with [Pulumi GitHub Actions](https://github.com/pulumi/actions) on GitHub Enterprise runner with `amd64` processor
```yaml
pulumi:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: "Setup Cloud SDK"
        uses: google-github-actions/setup-gcloud@v0
      - name: "Auth to GCP Dev env"
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ env.WLI_PROVIDER_DEV }}
          service_account: ${{ env.SERVICE_ACCOUNT_DEV }}
      - name: "Setup NodeJs"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION_DEV }}
      - name: "Install NPM requirements"
        run: npm --prefix ./pulumi install ./pulumi
      - name: "Create Dev stack"
        uses: pulumi/actions@v3
        with:
          command: up
          work-dir: ./pulumi
          stack-name: ${{ env.STACK_NAME_DEV }}
          cloud-url: ${{ env.CLOUD_URL_DEV }}
          upsert: true
          color: always
          config-map: |
            env:
              value: develop
              secret: false
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE_DEV }}
```
 I really frequently get the following error:
```sh
Error: code: -2
   stdout: 
   stderr: Command failed with exit code 255: pulumi preview --diff --parallel 2147483647 --exec-agent pulumi/actions@v3 --color always --exec-kind auto.local --event-log /tmp/automation-logs-preview-i23Z4e/eventlog.txt --stack XXXXXXXXXXXXX --non-interactive
  error: could not load plugin for time provider 'urn:pulumi:XXXXXXXXXXXXXXXXX::gcp-ts-gke::pulumi:providers:time::default_0_0_9_github_/api.github.com/pulumiverse/pulumi-time': Could not automatically download and install resource plugin 'pulumi-resource-time' at version v0.0.9, install the plugin using `pulumi plugin install resource time v0.0.9`.
  Underlying error: error downloading plugin time to file: failed to download plugin: time-0.0.9: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-time-v0.0.9-linux-amd64.tar.gz
  Previewing update (XXXXXXXXXXXXXXXX):
   err?: Error: Command failed with exit code 255: pulumi preview --diff --parallel 2147483647 --exec-agent pulumi/actions@v3 --color always --exec-kind auto.local --event-log /tmp/automation-logs-preview-i23Z4e/eventlog.txt --stack XXXXXXXXXX --non-interactive
  error: could not load plugin for time provider 'urn:pulumi:XXXXXXXXXXXXXXXXXXXX::gcp-ts-gke::pulumi:providers:time::default_0_0_9_github_/api.github.com/pulumiverse/pulumi-time': Could not automatically download and install resource plugin 'pulumi-resource-time' at version v0.0.9, install the plugin using `pulumi plugin install resource time v0.0.9`.
  Underlying error: error downloading plugin time to file: failed to download plugin: time-0.0.9: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-time-v0.0.9-linux-amd64.tar.gz
```
Funny, that I can't download plugin on my local machine:
```sh
% pulumi plugin install resource time 0.0.9 --reinstall
[resource plugin time-0.0.9] installing
warning: A new version of Pulumi is available. To upgrade from version '3.48.0' to '3.50.2', run 
   $ curl -sSL https://get.pulumi.com | sh
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
error: [resource plugin time-0.0.9] downloading from : failed to download plugin: time-0.0.9: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-time-v0.0.9-linux-amd64.tar.gz
```
but sometimes I get correct result in GitHub Workflow:
```yaml
+ time:index/rotating:Rotating: (create)
          [urn=urn:pulumi:artifactory-prod::gcp-ts-gke::time:index/rotating:Rotating::gcp-sa-key-rotation]
          [provider=urn:pulumi:xxxxxxxxxxxx::gcp-ts-gke::pulumi:providers:time::default_0_0_9_github_/api.github.com/pulumiverse/pulumi-time::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
          rotationDays: 60
```
So, could you explain me what happened and how I can fix it? Only with independent plugin installation? If yes, it's not a problem, I've already created [the PR with this feature](https://github.com/pulumi/actions/pull/812).

### Steps to reproduce

1. Install `@pulumiverse/time`  with version `0.0.9` from NPM
2. Add code with plugin functionality
3. Start GitHub Workflow

### Expected Behavior

Apply new resource

### Actual Behavior

Got 403 error

### Output of `pulumi about`

Tough to say. From pipeline I see only:
```
Configured range: ^3
Matched version: v3.50.2
Install destination is /home/runner/.pulumi
Successfully deleted pre-existing /home/runner/.pulumi/bin
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Hi there @Moon1706 thank you filing the issue! 

> could you explain me what happened?

This is how Pulumi downloads the plugin which seems to be missing _sometimes_ in the Github workflow:

When you run`npm install`, the nodejs package [`@pulumiverse/time`](https://github.com/pulumiverse/pulumi-time) is downloaded. Then it triggers the `postinstall` action on the package as seen [here](https://github.com/pulumiverse/pulumi-time/blob/main/sdk/nodejs/package.json#L15) which in turns runs the following command to download the provider _binary_ from Github:
```
pulumi plugin install resource time --server github://api.github.com/pulumiverse/pulumi-time
```
You should be able to run this locally and get the latest binary plugin 

It is unfortunate that the error message doesn't include the `--server` argument which is required when downloading plugin binaries from sources like github repositories other than official Pulumi repos (Pulumiverse being community-driven)

> how I can fix it?

You already mention installing the plugin individually and that would be alright. However given that is _sometimes_ does work suggests that installing the plugin is flaky. We do have a [_retry_ mechanism](https://github.com/pulumi/pulumi/blob/master/sdk/go/common/workspace/plugins.go#L997) in place when downloading plugins for these case but it seems insufficient at sometimes. 

It could be that the Pulumi CLI is tripping up when trying to install multiple providers at once from `postinstall` events of npm packages, how many providers are you using for your program if I may ask?

**Comment by Moon1706** [comment]
@Zaid-Ajaj 
package.json
```json
{
    "@pulumi/gcp": "6.41.0",
    "@pulumi/kubernetes": "3.22.1",
    "@pulumi/pulumi": "3.46.1",
    "@pulumiverse/time": "0.0.9"
}
```

**Comment by Moon1706** [comment]
Also, command
```sh
pulumi plugin install resource time --server github://api.github.com/pulumiverse/pulumi-time
```
works correctly on the local machine and GH runners.

**Comment by Moon1706** [comment]
@Zaid-Ajaj 
Hm, I also have some thoughts about why it can happen. GH job didn't install Pulumi, but NPM tried to set up plugin, therefore plugin just didn't install with command `pulumi plugin install`. But sometimes the process from the NPM step intersects with Pulumi GitHub Action. That's super strange, because `@pulumiverse/pulumi-time` use [`childProcess.spawnSync`](https://github.com/pulumiverse/pulumi-time/blob/main/sdk/nodejs/scripts/install-pulumi-plugin.js). Do you have any ideas about this behavior?

**Comment by Moon1706** [comment]
@Zaid-Ajaj 
Unfortunately, installation Pulumi before NPM didn't help. I checked the connectivity between GH runners and api.github.com and saw 403 error. So, I suppose that github://... this problem really relates to the retry mechanism. But if I use command:
```sh
pulumi plugin install resource time 0.0.9 --server https://github.com/pulumiverse/pulumi-time/releases/download/v0.0.9
```
all will work correctly.

**Comment by Frassle** [comment]
I think this might be https://github.com/pulumi/pulumi/issues/10882.
There are definitely some code paths that lose the download url along the way and so work fine for official plugins but lead to errors like this for third party plugins.

**Comment by Moon1706** [comment]
@Frassle 
Hmmm, interesting. Is Pulumi going to investigate and fix this problem?

**Comment by Moon1706** [comment]
As I outline before, here is [my solution](https://github.com/terraform-gitlab-modules/actions/tree/v3.21.0) and [the PR to official repo](https://github.com/pulumi/actions/pull/812).

**Comment by Zaid-Ajaj** [comment]
> GH job didn't install Pulumi, but NPM tried to set up plugin,

@Moon1706 GH runners have Pulumi installed by default but `pulumi/actions@v3` overrides that AFAIK so you get the latest version and you need it to actually install the plugins after `npm install`

> As I outline before, here is [my solution](https://github.com/terraform-gitlab-modules/actions/tree/v3.21.0) and https://github.com/pulumi/actions/pull/812.

As much as I like this PR, it actually shouldn't be needed in the first place and Pulumi CLI should get the required installed correctly.

> Is Pulumi going to investigate and fix this problem?

Yes, we will look into it. I think we should start by making the `pulumi plugin install` more visible:
```js
var res = childProcess.spawnSync("pulumi", ["plugin", "install", "--server", "github://api.github.com/pulumiverse/pulumi-time"].concat(args), {
    // before: hidden logs
    // stdio: ["ignore", "inherit", "inherit"]
    stdio: "inherit"
});
```
Which should show the logs. 

Then investigate why we fallback to the main plugin source when we have provided an alternative`--server` source

**Comment by Moon1706** [comment]
@Zaid-Ajaj 
Thank you for your comment https://github.com/pulumi/pulumi/issues/11743#issuecomment-1367363884.
1. Unfortunately, we use GH Enterprise self-hosted runners which don't have Pulumi by default.
2. Should I create PR with changing `childProcess.spawnSync` in the [pulumiverse/pulumi-time](https://github.com/pulumiverse/pulumi-time)?

**Comment by Zaid-Ajaj** [comment]
> Should I create PR with changing childProcess.spawnSync in the [pulumiverse/pulumi-time](https://github.com/pulumiverse/pulumi-time)?

@Moon1706 unfortunately this code in `scripts/install-pulumi-plugin.js` is auto-generated by our codegen tooling. Changing it by a manual PR will get overridden the next time we regenerate the SDKs. This changes needs to either be global: always enabled for all nodejs providers or be optional by setting a new option in the pulumi schema. The latter being probably the better course of action but it requires extending the schema definition and making our nodejs-codegen tooling respect this new option

**Comment by jbrunton** [comment]
Btw, I was also seeing this when using the Pulumi GitHub action. It seems this was because I was hitting the GitHub rate limiter, because the Pulumi action won't, by default, run in an environment with the `GITHUB_TOKEN` variable set. This can be fixed by setting it explicitly when running the Pulumi action, which will significantly increase the rate limit:

```yaml
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE_DEV }}
```
