### ISSUE TITLE
Project configuration (Pulumi.yaml) option to suppress outputs

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi#11828]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

In `Pulumi.yaml`, you can add an option to `refresh` automatically. In the same way, it would be nice to suppress the outputs on every action, or just on `pulumi preview`.

For example:

```yaml
options:
  suppressOutputs: true
  suppressPreviewOutputs: true
```

### Affected area/feature

Program Config
