### ISSUE TITLE
Invalid plugin overrides panic on startup

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#11864]
### What happened?

Running `pulumi up` with an invalid `Pulumi.yaml["plugins"]["providers"]` causes a panic before main.

### Steps to reproduce

Run `pulumi up` with:

```yaml
name: csharp-artifactory
runtime: dotnet
description: A minimal C# Pulumi program
plugins:
  providers:
    - name: artifactory
      bin: ../../../bin # key should be 'path'
```

### Expected Behavior

A useful error message.

### Actual Behavior

```
X pulumi up
panic: fatal: could not find provider folder at path 

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.AssertNoError({0x102720ae0?, 0xc0004c3990?})
        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/assert.go:40 +0x88
github.com/pulumi/pulumi/pkg/v3/codegen/schema.newPulumiPackage()
        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/mock_pulumi_schema.go:41 +0x42d
github.com/pulumi/pulumi/pkg/v3/codegen/schema.init()
        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/mock_pulumi_schema.go:45 +0x11f
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
