### ISSUE TITLE
pulumi new fails when project name is numeric

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#12136]
### What happened?

`pulumi new` flow errors when a numeric name is provided probably because YAML numerics are assumed to be numbers.

[![asciicast](https://asciinema.org/a/fmb4HTN6jZzNnjRXsLE4etIE9.svg)](https://asciinema.org/a/fmb4HTN6jZzNnjRXsLE4etIE9)

### Expected Behavior

Pulumi.yaml to be saved as

```yaml
name: "12345"
description: A minimal JavaScript Pulumi program
runtime:
  name: nodejs
  options:
    typescript: false
template:
  description: A minimal JavaScript Pulumi program
```

### Steps to reproduce

See asciinema recording.

`pulumi up` also fails with a poor error message

```
error: could not get cloud url: could not load current project: could not validate '/home/kdixler/foo/Pulumi.yaml': project is missing a non-empty string 'name' attribute
```

```yaml
name: 12345
description: A minimal JavaScript Pulumi program
runtime:
  name: nodejs
  options:
    typescript: false
template:
  description: A minimal JavaScript Pulumi program
```

### Output of `pulumi about`

```
CLI          
Version      3.54.1-dev.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       arch
Version  22.0.2
Arch     x86_64

This project is written in nodejs: executable='/home/kdixler/.nvm/versions/node/v14.19.1/bin/node' version='v14.19.1'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/dixler
User           dixler
Organizations  dixler, EpicGames, organization, pulumi

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the Pulumi program's dependencies: could not find either /home/kdixler/foo/yarn.lock or /home/kdixler/foo/package-lock.json
warning: Failed to get information about the current stack: No current stack
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
