### ISSUE TITLE
Easier config secret encryption in CLI

### ISSUE THREAD

**Issue by jesseduffield** [pulumi/pulumi#12819]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently when I want to add an encrypted secret to a yaml file I need to work out the path to that secret and then add the secret on the command line e.g.:
```
pulumi config set --secret --path path.to.secret my-secret-value
```

I'd much prefer to add the secret directly in the yaml in plaintext

```yml
path:
  to:
    secret: my-secret-value
```

and then run
```
pulumi config encrypt-secrets
```
to end up with
```yml
path:
  to:
    secret:
      secure: 12lk09lkasd91jdlsk
```

### Affected area/feature

I think this is just a CLI thing
