### ISSUE TITLE
Overriding a single property in a structured config object overrides the entire object

### ISSUE THREAD

**Issue by nick-catalist** [pulumi/pulumi#13176]
### What happened?

Given the following project config:

`Pulumi.yaml`
```yaml
name: project
runtime:
  name: python
  options:
    virtualenv: venv
description: GCP universe definition
config:
  # Defaults for GCP-wide configuration
  gcp:region:
    description: The GCP region
    value: us-central1
  gcp:zone:
    description: The GCP zone
    value: us-central1-a

  # project-db-lite MySQL instance
  project:project-db-lite-mysql-instance:
    description: MySQL instance
    value:
      name: project-db-lite
      version: MYSQL_8_0
      disk-size: 10
      availability: REGIONAL
      tier: db-custom-1-3840
      databases:
        - name: project-db
      users:
        - name: project-developer
```

and the following stack config:

`Pulumi.dev.yaml`
```yaml
#Dev-specific overrides
config:
  gcp:project: project-test-01
  project:project-db-lite-mysql-instance:
      availability: ZONAL
```

The output for `config.require_object(project-db-lite-mysql-instance)` is `{'availability': 'ZONAL'}`.

### Expected Behavior

I would expect only the overridden property to be changed, with the rest of the object intact. That is:

`{'availability': 'ZONAL', 'databases': [{'name': 'project-db'}], 'disk-size': 10, 'name': 'project-db-lite', 'tier': 'db-custom-1-3840', 'users': [{'name': 'project-developer'}], 'version': 'MYSQL_8_0'}`

### Steps to reproduce

Run any pulumi command with the above configurations.

### Output of `pulumi about`

```
CLI          
Version      3.71.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME    VERSION
gcp     6.58.0
python  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in python: executable='/home/nick/code/project/pulumi-repo/venv/bin/python3' version='3.10.6
'

Current Stack: org/project/dev

TYPE                       URN
pulumi:pulumi:Stack        urn:pulumi:dev::project::pulumi:pulumi:Stack::catalist-dev
pulumi:providers:gcp       urn:pulumi:dev::project::pulumi:providers:gcp::default_6_58_0


Found no pending operations associated with project/dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/nick-catalist
User           nick-catalist
Organizations  nick-catalist, [redacted]

Dependencies:
NAME        VERSION
pip         23.1.2
pulumi-gcp  6.58.0
setuptools  67.8.0
wheel       0.40.0

Pulumi locates its logs in /tmp by default
```

### Additional context

Slack thread: https://pulumi-community.slack.com/archives/C84L4E3N1/p1686853422841729

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
