### ISSUE TITLE
file name too long

### ISSUE THREAD

**Issue by 23ewrdtf** [pulumi/pulumi#13295]
### What happened?

I run pulumi in Gitlab CICD.

GOOGLE_APPLICATION_CREDENTIALS is available as a VAR.

I use 3.71.0 as 3.73.0 is not available as a docker image.

```
    - export PULUMI_SELF_MANAGED_STATE_NO_LEGACY_WARNING=1
    - export PULUMI_CONFIG_PASSPHRASE=""
    - export GITHUB_TOKEN=${PULUMI_TOKEN_GITHUB}
    - pulumi login gs://bucketstate
warning: A new version of Pulumi is available. To upgrade from version '3.71.0' to '3.73.0', visit https://pulumi.com/docs/install/ for manual instructions and release notes.
error: problem logging in: missing google credentials: unable to find gcp credentials: google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: open {
  "type": "service_account",
  "project_id": "redacted",
  "private_key_id": "redacted",
  "private_key": "-----BEGIN PRIVATE KEY-----\redacted\n-----END PRIVATE KEY-----\n",
  "client_email": "redacted@redacted",
  "client_id": "redacted",
  "auth_uri": "redacted",
  "token_uri": "redacted",
  "auth_provider_x509_cert_url": "redacted",
  "client_x509_cert_url": "redacted",
  "universe_domain": "redacted"
}: file name too long
```

### Expected Behavior

i expect for Pulumi to use GOOGLE_APPLICATION_CREDENTIALS and login to the bucket holding the state files.

### Steps to reproduce

Run above commands in gitlab cicd.

### Output of `pulumi about`

```
pulumi about
CLI          
Version      3.71.0
Go Version   go1.20.4
Go Compiler  gc
Plugins
NAME  VERSION
gcp   unknown
yaml  unknown
Host     
OS       debian
Version  11.7
Arch     x86_64
This project is written in yaml
No dependencies found
Pulumi locates its logs in /tmp by default
warning: A new version of Pulumi is available. To upgrade from version '3.71.0' to '3.73.0', visit https://pulumi.com/docs/install/ for manual instructions and release notes.

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Hey, thanks for reaching out. I was searching for the error message you got and it looks like someone had a similar issue when working with google creds.

It seems that `GOOGLE_APPLICATION_CREDENTIALS` is expecting a filepath whereas `GOOGLE_CREDENTIALS` expects the contents.

```
$ GOOGLE_CREDENTIALS=$(cat account.json) GOOGLE_APPLICATION_CREDENTIALS="account.json" ...
```

source: https://github.com/hashicorp/terraform/issues/17975

Let me know if this helps!

**Comment by 23ewrdtf** [comment]
Hi, thanks for this, here is something interesting.

This is my gitlab CI that works perfectly:

```
rnd-preview:
  stage: rnd-preview
  script:
    - echo ${SERVICE_ACCOUNT} > key.json
    - export GOOGLE_APPLICATION_CREDENTIALS="$(cat key.json)"
    - rm key.json
    - export PULUMI_SELF_MANAGED_STATE_NO_LEGACY_WARNING=1
    - export PULUMI_CONFIG_PASSPHRASE=""
    - export GITHUB_TOKEN=${PULUMI_TOKEN_GITHUB}
    - pulumi login ${PULUMI_STATE_BUCKET}
    - pulumi stack select $STACK
    - pulumi config set gcp:project ${GCP_PROJECT}
    - pulumi config set gcp:region ${GCP_REGION}
    - pulumi preview
```

If I do the same on my Mac I get the `File too long` error.

I haven't restarted my laptop in a while so it could be that...
