### ISSUE TITLE
PRs are failing in CI building binaries while running goreleaser

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#13312]
The `CI / build binaries (linux, amd64, ubuntu-latest) / linux-amd64` Package step is failing running goreleaser:

https://github.com/pulumi/pulumi/actions/runs/5407938467/jobs/9827830564#step:11:28

```
+ cat .goreleaser.yml
+ goreleaser release -f - -p 5 --skip-validate --rm-dist --snapshot
+ go run github.com/t0yv0/goreleaser-filter@v0.3.0 -goos linux -goarch amd64
Flag --rm-dist has been deprecated, please use --clean instead
  • by using this software you agree with its EULA, available at https://goreleaser.com/eula
  • running goreleaser v1.19.0-pro
  • skipping license check on snapshot
  • starting release...
  • loading config from stdin
  ⨯ release failed after 0s                  error=failed to load config: yaml: unmarshal errors:
  line 14: field replacements not found in type config.Archive
```

This is the output I get running locally:

```
$ cat .goreleaser.yml | go run github.com/t0yv0/goreleaser-filter@v0.3.0 -goos linux -goarch amd64 > out.yml
```

```yml
archives:
- files:
  - dst: .
    src: bin/{{ .Os }}/*
    strip_parent: true
  - dst: .
    src: bin/{{ .Os }}-{{ .Arch }}/*
    strip_parent: true
  format_overrides:
  - format: zip
    goos: windows
  id: pulumi
  name_template: '{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
  replacements:
    amd64: x64
  wrap_in_directory: pulumi{{ if eq .Os "windows" }}/bin{{ end }}
builds:
- binary: pulumi
  dir: pkg
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goamd64:
  - v1
  goarch:
  - amd64
  gobinary: ../scripts/go-wrapper.sh
  goos:
  - linux
  id: pulumi
  ldflags:
  - -X github.com/pulumi/pulumi/pkg/v3/version.Version={{.Tag}}
  main: ./cmd/pulumi
  mod_timestamp: '{{ .CommitTimestamp }}'
- binary: pulumi-language-go
  dir: sdk/go/pulumi-language-go
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goamd64:
  - v1
  goarch:
  - amd64
  gobinary: ../../../scripts/go-wrapper.sh
  goos:
  - linux
  id: pulumi-language-go
  ldflags:
  - -X github.com/pulumi/pulumi/pkg/v3/version.Version={{.Tag}}
  main: ./
  mod_timestamp: '{{ .CommitTimestamp }}'
- binary: pulumi-language-nodejs
  dir: sdk/nodejs/cmd/pulumi-language-nodejs
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goamd64:
  - v1
  goarch:
  - amd64
  gobinary: ../../../../scripts/go-wrapper.sh
  goos:
  - linux
  id: pulumi-language-nodejs
  ldflags:
  - -X github.com/pulumi/pulumi/pkg/v3/version.Version={{.Tag}}
  main: ./
  mod_timestamp: '{{ .CommitTimestamp }}'
- binary: pulumi-language-python
  dir: sdk
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goamd64:
  - v1
  goarch:
  - amd64
  gobinary: ../scripts/go-wrapper.sh
  goos:
  - linux
  id: pulumi-language-python
  ldflags:
  - -X github.com/pulumi/pulumi/pkg/v3/version.Version={{.Tag}}
  main: ./python/cmd/pulumi-language-python
  mod_timestamp: '{{ .CommitTimestamp }}'
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'
dist: goreleaser
project_name: pulumi
snapshot:
  name_template: '{{ .Version }}-SNAPSHOT'
```

GoReleaser [v1.19.0](https://github.com/goreleaser/goreleaser/releases/tag/v1.19.0) was just released earlier today.
