### ISSUE TITLE
Azure OIDC failures with Azure Keyvault Secrets & Azure Blob Storage Backend

### ISSUE THREAD

**Issue by mdhomer** [pulumi/pulumi#13476]
### What happened?

Trying to authenticate and run pulumi preview/up from Github Actions using an Azure OIDC AppRegistration/ServicePrincipal.

Our setup consists of:
- Azure Blob Storage state management
- Azure KeyVault secret encryption
- Azure Resources

I'm specifying the required OIDC options, based on the docs:
```
ARM_CLIENT_ID: <>
ARM_TENANT_ID: <>
ARM_SUBSCRIPTION_ID: <>
ARM_USE_OIDC: true
&
AZURE_KEYVAULT_AUTH_VIA_CLI: <>
```
And performing pulumi-login via:
`pulumi login "azblob://pulumi-state?storage_account=<my>infraconfig"`
The [documentation](https://www.pulumi.com/docs/concepts/state/#azure-blob-storage) indicates that the above connection string should use the active Azure CLI login to connect to the storage account. However I have been unable to login to the state without using `AZURE_KEYVAULT_AUTH_VIA_CLI`.

Attempt1:

`AZURE_KEYVAULT_AUTH_VIA_CLI: false`
```
+ pulumi login 'azblob://pulumi-state?storage_account=<my>infraconfig'
Logged in to fv-az564-1 as runner (azblob://pulumi-state?storage_account=<my>infraconfig)
+ pulumi preview --stack developmentuk-applicationenvironment
error: unable to open bucket azblob://pulumi-state: azureblob: Options.AccountName is required
```

Attempt2:
`AZURE_KEYVAULT_AUTH_VIA_CLI: true`
```
...
azure-native:resources:ResourceGroup developmentuk-monitoring  error: building auth config: Authenticating using the Azure CLI is only supported as a User (not a Service Principal).
...
Diagnostics:
  azure-native:resources:ResourceGroup (developmentuk-monitoring):
    error: building auth config: Authenticating using the Azure CLI is only supported as a User (not a Service Principal).
    
    To authenticate to Azure using a Service Principal, you can use the separate 'Authenticate using a Service Principal'
    auth method - instructions for which can be found here: https://www.pulumi.com/docs/intro/cloud-providers/azure/setup/#service-principal-authentication
    
    Alternatively you can authenticate using the Azure CLI by using a User Account.
```
I think this is some incompatibility with using Azure Keyvault CLI credentials alongside the OIDC configuration.

### Expected Behavior

1. Connectivity via `AZURE_KEYVAULT_AUTH_VIA_CLI`, shouldn't affect the OIDC configuration when later performing the pulumi preview/up operations.

2. Using Pulumi CLI v3.41.1 with: `pulumi login azblob://<container-path>?storage_account=account_name` should use Azure CLI Authentication without specifying the `AZURE_KEYVAULT_AUTH_VIA_CLI` option. However the above error look as if the cli still expects some AZURE_STORAGE_ACCOUNT/KEY related configuration.

### Steps to reproduce

Outlined in "What happened", no code is required apart from a Pulumi stack & some azure-native resources.

GithubActions steps:
```
    permissions:
      contents: read
      id-token: write  # required for OIDC auth
      
      ...
      
      - name: az cli login
        uses: azure/login@v1
        with:
          client-id: <>
          tenant-id: <>
          subscription-id: <>
          
      ...
      
      - name: Run Pulumi Preview
        env:
          ARM_CLIENT_ID: <>
          ARM_TENANT_ID: <>
          ARM_SUBSCRIPTION_ID: <>
          # this option uses ACTIONS_ID_TOKEN_REQUEST_TOKEN & ACTIONS_ID_TOKEN_REQUEST_URL, provided by ghactions
          ARM_USE_OIDC: true
          AZURE_KEYVAULT_AUTH_VIA_CLI: <>
        working-directory: ${{ inputs.stackDirectory }}
        run: |
          set -x
          # pulumi v3.41.1+ uses the acccount notion to connect via azure CLI
          pulumi about
          pulumi login "azblob://pulumi-state?storage_account=<my>infraconfig"
          pulumi preview --stack developmentuk-${{ inputs.stackName }}

```

### Output of `pulumi about`

```
+ pulumi about
running 'dotnet build -nologo .'
  Determining projects to restore...

  Restored
  ...


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:[20](https://github.com/.../actions/runs/5541219075/jobs/10114342231#step:8:21).49

'dotnet build -nologo .' completed successfully
warning: Failed to get information about the current stack: No current stack
CLI          
Version      3.74.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
azure         4.14.0
azure-native  1.80.0
azuread       5.6.0
dotnet        unknown
random        4.3.1
sentry        0.0.8
tls           4.0.0

Host     
OS       ubuntu
Version  [22](https://github.com/.../actions/runs/5541219075/jobs/10114342231#step:8:23).04
Arch     x86_64

This project is written in dotnet: executable='/usr/bin/dotnet' version='7.0.305'

Backend        
Name           fv-az1[25](https://github.com/.../actions/runs/5541219075/jobs/10114342231#step:8:26)6-112
URL            azblob://pulumi-state
User           runner
Organizations  

No dependencies found

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
