### ISSUE TITLE
the `pulumi new` prompt shows a secret value in plain text

### ISSUE THREAD

**Issue by desteves** [pulumi/pulumi#14110]
### What happened?

When running `pulumi new` against a template that has a config variable with the `secret` flag, the prompt shows the inputted value as plain text.

I'd expect the input to not be displayed at all (or replaced with *'s) given it's a _secret_.

### Example

Pulumi.yaml

```
name: ${PROJECT}
description: ${DESCRIPTION}
runtime: nodejs
template:
  description: A TypeScript program to deploy a serverless application on Cloudflare.
  config:
    cloudflare:apiToken:
      secure: true # <<<<<<<------ look here
```

And see the last line from this `pulumi new` prompt:

```
This command will walk you through creating a new Pulumi project.

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name (serverless-cloudflare):  
project description (A TypeScript program to deploy a serverless application on Cloudflare.):  
Created project 'serverless-cloudflare'

Please enter your desired stack name.
To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`).
stack name (dev):  
Created stack 'dev'

cloudflare:apiToken: abcabc123123 
````

### Output of `pulumi about`

```
pulumi about                                                                      
CLI          
Version      3.86.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.5.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v20.8.0'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
