### ISSUE TITLE
pulumi convert for csharp with a DependsOn array is wrong 

### ISSUE THREAD

**Issue by desteves** [pulumi/pulumi#14462]
### What happened?

I ran `pulumi convert --generate-only --language csharp --out result` with a working, simple yaml file (shown below) for which there's a resource with two DependsOn. However, the generated csharp code contained an error when attempting to run it.

### Example

Pulumi.yaml contents
```yaml
name: quickstart
runtime: yaml
description: A minimal AWS Pulumi YAML program

variables:
  homepage:
    fn::fileAsset: ./index.html

resources:
  my-bucket:
    type: aws:s3:Bucket
    properties:
      website:
        indexDocument: index.html

  ownership-controls:
    type: aws:s3:BucketOwnershipControls
    properties:
      bucket: ${my-bucket.id}
      rule:
        objectOwnership: ObjectWriter

  public-access-block:
    type: aws:s3:BucketPublicAccessBlock
    properties:
      bucket: ${my-bucket.id}
      blockPublicAcls: false

  index.html:
    type: aws:s3:BucketObject
    properties:
      bucket: ${my-bucket.id}
      source: ${homepage}
      contentType: text/html
      acl: public-read
    options:
      dependsOn:
        - ${public-access-block}
        - ${ownership-controls}

outputs:
  bucketName: ${my-bucket.id}
  bucketEndpoint: http://${my-bucket.websiteEndpoint}

```

Version of the same code after running it through `pulumi convert`
```csharp
using Pulumi;
using Pulumi.Aws.S3;
using Pulumi.Aws.S3.Inputs;
using System.Collections.Generic;

return await Deployment.RunAsync(() =>
{
    var bucket = new Bucket("my-bucket", new()
    {
        Website = new BucketWebsiteArgs
        {
            IndexDocument = "index.html",
        },
    });

    var ownershipControls = new BucketOwnershipControls("ownership-controls", new()
    {
        Bucket = bucket.Id,
        Rule = new BucketOwnershipControlsRuleArgs
        {
            ObjectOwnership = "ObjectWriter",
        },
    });

    var publicAccessBlock = new BucketPublicAccessBlock("public-access-block", new()
    {
        Bucket = bucket.Id,
        BlockPublicAcls = false,
    });

    var indexHtml = new BucketObject("index.html", new()
    {
        Bucket = bucket.Id,
        Source = new FileAsset("./index.html"),
        ContentType = "text/html",
        Acl = "public-read",
    }, new CustomResourceOptions
    {
        DependsOn = new []
        {
            publicAccessBlock,
            ownershipControls,
        },
    });

    return new Dictionary<string, object?>
    {
        ["bucketName"] = bucket.Id,
        ["bucketEndpoint"] = bucket.WebsiteEndpoint.Apply(websiteEndpoint => $"http://{websiteEndpoint}"),
    };
});
```

### Output of `pulumi about`

```bash
pulumi about
CLI          
Version      3.91.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME  VERSION
aws   unknown
yaml  unknown

Host     
OS       darwin
Version  14.0
Arch     arm64

This project is written in yaml```

### Additional context

A small fix to the csharp code worked by explicitly typing the array.

Working code snippet:

```csharp
    var indexHtml = new BucketObject("index.html", new()
    {
        Bucket = bucket.Id,
        Source = new FileAsset("./index.html"),
        ContentType = "text/html",
        Acl = "public-read",
    }, new CustomResourceOptions
    {
        DependsOn = new Resource[].  // <------------ FIX -------------
        {
            publicAccessBlock,
            ownershipControls,
        },
    });

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
