### ISSUE TITLE
`pulumi convert` uses a *very* old version of the Pulumi Go SDK

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#14613]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When we generate an example with Pulumi convert in Go, we should target a new version of Go and a new version of the Pulumi Go SDK.

Right now these values are hardcoded with `go 1.20` and `sdk/v3 v3.30.0`. Ideally we would generate an SDK version inline with the codegen version released, but we should at least bump the hardcoded version to `v3.94.2` (current).

https://github.com/pulumi/pulumi/blob/273951bb17ef45efeeebfe25be174c6df10c1e08/pkg/codegen/go/gen_program.go#L483-L488

### Affected area/feature

Go Codegen.

**Comment by desteves** [comment]
Here's a small yaml program being convereted to go. Depending on the usage of the `--generate-only` flag, the go versions differ. 

```yaml
# Pulumi.yaml               
name: quickstart
runtime: yaml
description: A minimal AWS Pulumi YAML program

resources:
  my-bucket:
    type: aws:s3:Bucket
    properties:
      website:
        indexDocument: index.html

  ownership-controls:
    type: aws:s3:BucketOwnershipControls
    properties:
      bucket: ${my-bucket.id}
      rule:
        objectOwnership: ObjectWriter

  public-access-block:
    type: aws:s3:BucketPublicAccessBlock
    properties:
      bucket: ${my-bucket.id}
      blockPublicAcls: false

  index.html:
    type: aws:s3:BucketObject
    properties:
      bucket: ${my-bucket.id}
      source:
        fn::fileAsset: ./index.html
      contentType: text/html
      acl: public-read
    options:
      dependsOn:
        - ${public-access-block}
        - ${ownership-controls}

outputs:
  bucketName: ${my-bucket.id}
  bucketEndpoint: http://${my-bucket.websiteEndpoint}


```


```bash
➜   pulumi convert --language go --out gogenonly --generate-only 
Converting from yaml...
Using version 1.4.3 for pulumi-converter-yaml
Converting to go...
➜   pulumi convert --language go --out goconvert                
Converting from yaml...
Using version 1.4.3 for pulumi-converter-yaml
Converting to go...
Installing dependencies...

Finished installing dependencies

➜   diff -y goconvert/go.mod gogenonly/go.mod
module quickstart                                                       module quickstart

go 1.21                                                         |       go 1.20

toolchain go1.21.4                                              <       
                                                                <       
require (                                                               require (
                                                                >               github.com/pulumi/pulumi/sdk/v3 v3.30.0
        github.com/pulumi/pulumi-aws/sdk/v6 v6.13.3                             github.com/pulumi/pulumi-aws/sdk/v6 v6.13.3
        github.com/pulumi/pulumi/sdk/v3 v3.96.2                 |       )
\ No newline at end of file

)                                                               <       
                                                                <       
require (                                                       <       
        dario.cat/mergo v1.0.0 // indirect                      <       
        github.com/Microsoft/go-winio v0.6.1 // indirect                <       
        github.com/ProtonMail/go-crypto v0.0.0-20230828082       <       
        github.com/acomagu/bufpipe v1.0.4 // indirect           <       
        github.com/aead/chacha20 v0.0.0-20180709150244-8b1       <     
        //... more stuff
```
