### ISSUE TITLE
Pulumi up delete every resource in stack

### ISSUE THREAD

**Issue by BenjaminZ** [pulumi/pulumi#14838]
### What happened?

`pulumi up` deleted every resource in the stack.

In one case `preview` and `up` have same outputs `52 deleted`

In another case they ave different output. `preview` showing `5 changes, 51 unchanged`, while `up` ends up `50 deleted`.

### Example

There is no clear way to reproduce this problem. We've run workflows lots of times so far and this issue happened 3 times.

### Output of `pulumi about`

```
Version      3.95.0
Go Version   go1.21.4
Go Compiler  gc
Plugins
NAME          VERSION
azure-native  2.21.2
azuread       5.46.0
dotnet        unknown
random        4.15.0
Host     
OS       ubuntu
Version  22.04
Arch     x86_64
This project is written in dotnet: executable='/usr/share/dotnet/dotnet' version='8.0.100'
Backend        
Name           fv-az[43](https://github.com/WillowInc/Infrastructure-and-Application-Deployment/actions/runs/7189412215/job/19580884337#step:7:43)6-936
URL            file://~
User           runner
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
@BenjaminZ, are you specifying any other flags, like `pulumi up --refresh`? Can you list the types of the 52 and 50 deleted resources?

**Comment by BenjaminZ** [comment]
We are using [Pulumi GH actions](https://github.com/pulumi/actions), the input is

```
with:
    command: up
    work-dir: Applications/***
    stack-name: ***
    secrets-provider: azurekeyvault://***.vault.azure.net/keys/pulumi
    cloud-url: azblob://pulumi/twin/infra?storage_account=***
    refresh: true
    comment-on-pr: true
    upsert: true
    diff: true
    pulumi-version: 3.95.0)
    comment-on-summary: false
    github-token: ***
    expect-no-changes: false
    target-dependents: false
    remove: false
    edit-pr-comment: true
    color: auto
    exclude-protected: false
```

types:

```
azure-native:authorization:RoleAssignment
azure-native:eventgrid:EventSubscription
azure-native:eventgrid:SystemTopicEventSubscription
azure-native:storage:BlobContainer
azure-native:storage:Queue
azure-native:web:WebApp
azure-native:kusto:DatabasePrincipalAssignment
azure-native:storage:Queue
azure-native:web:AppServicePlan
azure-native:keyvault:Vault
azure-native:kusto:Script
azure-native:storage:StorageAccount
azure-native:datafactory:Factory
pulumi:providers:azure-native
azure-native:sql:FirewallRule
azure-native:eventgrid:Topic
```

everything except for the stack references
