### ISSUE TITLE
ESC: multiple environments in stack config don't work 

### ISSUE THREAD

**Issue by ThorKarlsson** [pulumi/pulumi#14848]
### What happened?

I was trying to break up my config into several ESC environments and then import them individually into my Stack config. When more than one environment was set, previous configurations became undefined. This seems to be because one of my environments contained an import. If none of the environments have an import the configuration works as expected but as soon as there is an import then only the environment with the import loads and the others are undefined.

```yaml
# Pulumi.dev.yaml
environment:
  - api-auth-dev
  - api-billing-dev
  - api-documents-dev
config:
  aws:profile: dev
  aws:region: ap-southeast-2
  ...
```

### Example

Environments:
```yaml
# env-a
values:
  pulumiConfig:
    foo: env-a-config
```

```yaml
# env-b
values:
  pulumiConfig:
    bar: env-b-config
```

```yaml
# Pulumi.dev.yaml
environment:
  - env-a
  - env-b
config:
 ...
```

```typescript
// index.ts

const config = new pulumi.Config();

console.log(`config.get("foo"): ${config.get("foo")}`)
console.log(`config.get("bar"): ${config.get("bar")}`)
```
```
Output:
  pulumi:pulumi:Stack (myhr-fullenv-dev):
    config.get("foo"): env-a-config
    config.get("bar"): env-b-config
```

This works as expected - but now if I import something in env-b, env-a will become undefined.

```yaml
# env-b
imports:
  - env-c-secrets
values:
  pulumiConfig:
    bar: env-b-config
```

```yaml
# env-c-secrets
values:
  password: 12345
```

Run the code again this is my output:
```
  pulumi:pulumi:Stack (myhr-fullenv-dev):
    config.get("foo"): undefined
    config.get("bar"): env-b-config
```

### Output of `pulumi about`

```
pulumi about

CLI
Version      3.96.2
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME     VERSION
aws      6.13.0
command  0.9.2
nodejs   unknown

Host
OS       darwin
Version  14.1
Arch     x86_64

This project is written in nodejs: executable='/Users/thor/.nvm/versions/node/v20.10.0/bin/node' version='v20.10.0'

Current Stack: myhr/myhr-fullenv/dev
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pierskarsenbarg** [comment]
Just wanted to add some extra output as discussed in our internal slack around this and using some of the examples above.

So with the following environments:

```yaml
# env-a
values:
  pulumiConfig:
    foo: env-a-config
```

```yaml
# env-b
imports:
  - env-c
values:
  pulumiConfig:
    bar: env-b-config
```

```yaml
# env-c
values:
  password: 12345
```

This gives the following output from `pulumi env open pierskarsenbarg/env-a -f detailed`:

```json
{
  "value": {
    "pulumiConfig": {
      "value": {
        "foo": {
          "value": "env-a-config",
          "trace": {
            "def": {
              "environment": "env-a",
              "begin": {
                "line": 4,
                "column": 10,
                "byte": 41
              },
              "end": {
                "line": 4,
                "column": 22,
                "byte": 53
              }
            }
          }
        }
      },
      "trace": {
        "def": {
          "environment": "env-a",
          "begin": {
            "line": 4,
            "column": 5,
            "byte": 36
          },
          "end": {
            "line": 4,
            "column": 22,
            "byte": 53
          }
        }
      }
    }
  },
  "trace": {
    "def": {
      "begin": {
        "line": 0,
        "column": 0,
        "byte": 0
      },
      "end": {
        "line": 0,
        "column": 0,
        "byte": 0
      }
    }
  }
}
```

for `pulumi env open pierskarsenbarg/env-b -f detailed`:

```json
{
  "value": {
    "password": {
      "value": 12345,
      "trace": {
        "def": {
          "environment": "env-c",
          "begin": {
            "line": 3,
            "column": 13,
            "byte": 36
          },
          "end": {
            "line": 3,
            "column": 18,
            "byte": 41
          }
        }
      }
    },
    "pulumiConfig": {
      "value": {
        "bar": {
          "value": "env-b-config",
          "trace": {
            "def": {
              "environment": "env-b",
              "begin": {
                "line": 6,
                "column": 10,
                "byte": 60
              },
              "end": {
                "line": 6,
                "column": 22,
                "byte": 72
              }
            }
          }
        }
      },
      "trace": {
        "def": {
          "environment": "env-b",
          "begin": {
            "line": 6,
            "column": 5,
            "byte": 55
          },
          "end": {
            "line": 6,
            "column": 22,
            "byte": 72
          }
        }
      }
    }
  },
  "trace": {
    "def": {
      "begin": {
        "line": 0,
        "column": 0,
        "byte": 0
      },
      "end": {
        "line": 0,
        "column": 0,
        "byte": 0
      }
    }
  }
}
```

and for `pulumi env open pierskarsenbarg/env-c -f detailed`:

```json
{
  "value": {
    "password": {
      "value": 12345,
      "trace": {
        "def": {
          "environment": "env-c",
          "begin": {
            "line": 3,
            "column": 13,
            "byte": 36
          },
          "end": {
            "line": 3,
            "column": 18,
            "byte": 41
          }
        }
      }
    }
  },
  "trace": {
    "def": {
      "begin": {
        "line": 0,
        "column": 0,
        "byte": 0
      },
      "end": {
        "line": 0,
        "column": 0,
        "byte": 0
      }
    }
  }
}
```

and running the following typescript:

```typescript
import * as pulumi from "@pulumi/pulumi";
const config = new pulumi.Config();

console.log(`config.get("foo"): ${config.get("foo")}`)
console.log(`config.get("bar"): ${config.get("bar")}`)
```

with the following `Pulumi.dev.yaml`:

```yaml
environment:
  - env-a
  - env-b
```

gives the following output:

```bash
Updating (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/pierskarsenbarg/esc-bug/dev/updates/3

     Type                 Name         Status     Info
     pulumi:pulumi:Stack  esc-bug-dev             2 messages

Diagnostics:
  pulumi:pulumi:Stack (esc-bug-dev):
    config.get("foo"): undefined
    config.get("bar"): env-b-config

Resources:
    1 unchanged

Duration: 3s
```

(so the same as @ThorKarlsson)
