### ISSUE TITLE
Issue with GCP provider and managing topic subscriptions

### ISSUE THREAD

**Issue by jondkelley** [pulumi/pulumi#15051]
### What happened?

Pulumi up

     Type                        Name                              Plan     Info
     pulumi:pulumi:Stack         org-identity-pubsub-uk-dev           36 messages
     └─ gcp:pubsub:Subscription  identity-change-detection-sub              1 error

Diagnostics:
  pulumi:pulumi:Stack (org-identity-pubsub-uk-dev):
    panic: interface conversion: interface {} is bool, not string
    goroutine 167 [running]:
    github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource.SetLabelsDiff({0x140071fb350?, 0x140071fb260?}, 0x140071d13b0?, {0x109d67ee0?, 0x140066cea80})
    	/home/runner/work/pulumi-gcp/pulumi-gcp/upstream/google-beta/tpgresource/labels.go:84 +0x678
    github.com/hashicorp/terraform-provider-google-beta/google-beta/services/pubsub.ResourcePubsubSubscription.All.func1({0x109df2e68, 0x10db7d5e0}, 0x10857628f?, {0x109d67ee0, 0x140066cea80})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230912190043-e6d96b3b8f7e/helper/customdiff/compose.go:53 +0x98
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0x14000e6e210, {0x109df2e68, 0x10db7d5e0}, 0x140017d3790, 0x14007183bf0, 0x14000d66ba0, {0x109d67ee0, 0x140066cea80}, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230912190043-e6d96b3b8f7e/helper/schema/schema.go:698 +0x3b8
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x0?, {0x109df2e68?, 0x10db7d5e0?}, 0x140017d3790, 0x140017d3380?, {0x109d67ee0?, 0x140066cea80?})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230912190043-e6d96b3b8f7e/helper/schema/resource.go:967 +0x9c
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.simpleDiff({0x14000cc7200?, {0x140014cedb0?, 0x140017ced00?, 0x1a?}}, 0x0?, 0x8000103?, 0x0?, 0xffffffffffffffff?, {{{0x109df3568?, 0x140065415b8?}}, ...}, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.66.0/pkg/tfshim/sdk-v2/provider_diff.go:101 +0x808
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Diff({0x14000cc7200?, {0x0?, 0x0?, 0x0?}}, {0x1085bbc83, 0x1a}, {0x109df33a8?, 0x14002073728}, {0x109dc2b20, 0x14007183bf0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.66.0/pkg/tfshim/sdk-v2/provider_diff.go:63 +0x1fc
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Diff(0x1400071d340, {0x109df2d88?, 0x140071833b0?}, 0x14007123880)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.66.0/pkg/tfbridge/provider.go:672 +0x4a4
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Diff.func1({0x109e0ba48?, 0x1400071d340?})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.7-0.20230801203955-5d215c892096/muxer.go:338 +0x3c
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.resourceMethod[...](0x1400120b220?, 0x14006e13778, 0x14006e13758?)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.7-0.20230801203955-5d215c892096/muxer.go:303 +0xc4
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Diff(0x14006e137b8?, {0x109df2d88?, 0x140071833b0?}, 0x10947c7c0?)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.7-0.20230801203955-5d215c892096/muxer.go:337 +0x5c
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler.func1({0x109df2d88, 0x140071833b0}, {0x109b64e20?, 0x14007123880})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.94.2/proto/go/provider_grpc.pb.go:575 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x109df2d88, 0x14007182f90}, {0x109b64e20, 0x14007123880}, 0x14007190500, 0x14002073518)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler({0x109d1b980?, 0x1400120b220}, {0x109df2d88, 0x14007182f90}, 0x14007039730, 0x1400006e6a0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.94.2/proto/go/provider_grpc.pb.go:577 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x140007d0000, {0x109e06480, 0x140059e61a0}, 0x1400718b440, 0x140065e1bc0, 0x10db2a4c8, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1374 +0xb44
    google.golang.org/grpc.(*Server).handleStream(0x140007d0000, {0x109e06480, 0x140059e61a0}, 0x1400718b440, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1751 +0x7c4
    google.golang.org/grpc.(*Server).serveStreams.func1.1()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:986 +0xb4
    created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 102
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:997 +0x160

### Example

Happened when changing a resource with a TTL value to TTL ""

```
name: org-identity-pubsub
runtime: yaml
config:
  vanta_label_contains_user_data:
    type: string
  vanta_label_non_prod:
    type: string
resources:
  identity-change-detection-topic:
    type: gcp:pubsub:Topic
    properties:
      name: identity-change-detection
      project: ${project}
    options:
      protect: true
  identity-change-detection-sub:
    type: gcp:pubsub:Subscription
    properties:
      labels:
        vanta-contains-user-data: '${vanta_label_contains_user_data}'
        vanta-description: shared-data-across-services
        vanta-non-prod: '${vanta_label_non_prod}'
        vanta-owner: owner
      ackDeadlineSeconds: 10
      expirationPolicy:
        ttl: ""
      messageRetentionDuration: 86400s
      name: identity-change-detection-sub
      project: ${project}
      topic: projects/${project}/topics/identity-change-detection
    options:
      protect: true
      dependsOn: 
        - ${identity-change-detection-topic}
```

Stack config

```
config:
  gcp:project: com-org-uk-dev-9aa9cc53
  org-identity-pubsub:project: com-org-uk-dev-9aa9cc53
  org-identity-pubsub:vanta_label_contains_user_data: "false"
  org-identity-pubsub:vanta_label_non_prod: "true"
```

### Output of `pulumi about`

```
CLI
Version      3.99.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME  VERSION
yaml  unknown

Host
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in yaml

Current Stack: company/org-identity-pubsub/us-rain

TYPE                                  URN
pulumi:pulumi:Stack                   urn:pulumi:us-rain::org-identity-pubsub::pulumi:pulumi:Stack::activtrak-identity-pubsub-us-rain
pulumi:providers:gcp                  urn:pulumi:us-rain::org-identity-pubsub::pulumi:providers:gcp::default
gcp:pubsub/topic:Topic                urn:pulumi:us-rain::org-identity-pubsub::gcp:pubsub/topic:Topic::identity-change-detection-topic
gcp:pubsub/subscription:Subscription  urn:pulumi:us-rain::org-identity-pubsub::gcp:pubsub/subscription:Subscription::identity-change-detection-sub
gcp:pubsub/subscription:Subscription  urn:pulumi:us-rain::activtrak-identity-pubsub::gcp:pubsub/subscription:Subscription::identity-user-creation-sub

```

### Additional context

Geoff in support said:

I have been working on this and I do think it is due to a bug. I don't think you're doing anything wrong. I was able to get them both to create at one point. But even then it was doing weird things as you can see from the preview plan output below. One was "0" and "1" and the other was "true" and "false". For the same type of resource that's weird behavior. I also can't get it to repeat after I destroyed it. I was playing with substituting hard values instead of resources. I'll keep playing with it but I wanted to give you an update.

```
~ gcp:pubsub/subscription:Subscription: (update) 🔒
[id=projects/myprojectid/subscriptions/identity-user-creation-sub]
[urn=urn:pulumi:dev::activtrak-identity-pubsub::gcp:pubsub/subscription:Subscription::identity-user-creation-sub]
~ labels: {
~ vanta-contains-user-data: "0" => "false"
~ vanta-non-prod : "1" => "true"
}
~ gcp:pubsub/subscription:Subscription: (update) 🔒
[id=projects/myprojectid/subscriptions/identity-change-detection-sub]
[urn=urn:pulumi:dev::activtrak-identity-pubsub::gcp:pubsub/subscription:Subscription::identity-change-detection-sub]
~ labels: {
~ vanta-contains-user-data: "true" => false
~ vanta-non-prod : "false" => true
}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
