### ISSUE TITLE
Resource creation fails but state is updated

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi#15066]
### What happened?

When I run `pulumi up` with the following program, the `NodePool` resource creation fails but the engine marks it as created.

Subsequent `pulumi up` mark it for update but the update 404s since it can't find the resource.

### Example

```
name: cluster
runtime: yaml
description: A minimal Google Cloud Pulumi YAML program
resources:
  some-provider:
    type: pulumi:providers:gcp
    defaultProvider: true
    options:
      version: 7.3.1
      # pluginDownloadUrl: 
  serviceAccount:
    type: gcp:serviceaccount:Account
    properties:
      accountId: service-account-1234
      displayName: Service Account
  primary:
    type: gcp:container:Cluster
    properties:
      location: us-central1
      # We can't create a cluster with no node pool defined, but we want to only use
      #   # separately managed node pools. So we create the smallest possible default
      #   # node pool and immediately delete it.
      removeDefaultNodePool: true
      initialNodeCount: 1
  primaryPreemptibleNodes:
    type: gcp:container/nodePool:NodePool
    properties:
      location: us-central1
      cluster: ${primary.name}
      nodeCount: 1
      nodeConfig:
        preemptible: true
        machineType: e2-medium
        serviceAccount: ${serviceAccount.email}
        oauthScopes:
          - https://www.googleapis.com/auth/cloud-platform
```

### Output of `pulumi about`

CLI          
Version      3.94.2
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME  VERSION
gcp   7.3.1
yaml  unknown
```
Host     
OS       darwin
Version  14.1.1
Arch     arm64

This project is written in yaml

Current Stack: organization/cluster/dev

TYPE                                URN
pulumi:pulumi:Stack                 urn:pulumi:dev::cluster::pulumi:pulumi:Stack::cluster-dev
pulumi:providers:gcp                urn:pulumi:dev::cluster::pulumi:providers:gcp::some-provider
gcp:container/cluster:Cluster       urn:pulumi:dev::cluster::gcp:container/cluster:Cluster::primary
gcp:serviceaccount/account:Account  urn:pulumi:dev::cluster::gcp:serviceaccount/account:Account::serviceAccount
gcp:container/nodePool:NodePool     urn:pulumi:dev::cluster::gcp:container/nodePool:NodePool::primaryPreemptibleNodes


Found no pending operations associated with dev

Backend        
Name           Venelins-MBP.london.markovcloud.com
URL            file://~
User           vvm
Organizations  
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/82/nqnqw81s1h56l5nv940f9mq00000gn/T/ by default
```

### Additional context

[out.txt](https://github.com/pulumi/pulumi/files/13842530/out.txt)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
