### ISSUE TITLE
Add a `details` or equivalent field to Pulumi Project File's template options for additional information or instructions

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi#15360]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would be nice to have the ability to display additional instruction or information to users once they have selected a template. The description field gets displayed on template selection, but can be limited in how much information it can display for a user.

### Code
```yaml
name: ${PROJECT}
description: ${DESCRIPTION}
runtime: nodejs
template:
  description: A Description
  important: true
```
### Output
```bash
Please choose a template (16/227 shown):
 azure-typescript                   A Description
 
Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name (pulumi-new-test):  
project description (A Description):  
```
### Code

```yaml
name: ${PROJECT}
description: ${DESCRIPTION}
runtime: nodejs
template:
  description: A Description
  details: Here are some additional instructions that will guide you to use this template
  important: true
```

```bash
Please choose a template (16/227 shown):
 azure-typescript                   A Description
 
Here are some additional instructions that will guide you to use this template

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name (pulumi-new-test):  
project description (A Description):  
```
### Affected area/feature
CLI
