### ISSUE TITLE
`description:` in Project File overrides the `template:description` field when using a Pulumi template

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi#15361]
### What happened?

When attempting to use a Pulumi template, I noticed if `description:` contained a value other than `${DESCRIPTION}` it would override the value of `template:description`. This doesn't reflect what I would expect to happen when attempting to provide a template to users.

### Project.yaml
```yaml
name: ${PROJECT}
description: A Foo Description
runtime: nodejs
template:
  description: A Bar Description
```
### Console Output
```
Please choose a template (16/227 shown):
 azure-typescript                   A Foo Description
This command will walk you through creating a new Pulumi project.

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name (pulumi-new-test):  
project description (A Foo Description): 
```

### Output of `pulumi about`

```
CLI          
Version      3.102.0
Go Version   go1.21.6
Go Compiler  gc

Host     
OS       darwin
Version  14.2.1
Arch     arm64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/zbuchheit-pulumi-corp
User           zbuchheit-pulumi-corp
Organizations  zbuchheit-pulumi-corp, team-ce, demo, pulumi
Token type     personal

Pulumi locates its logs in /var/folders/lh/l71cdh810xb33t0jc7qmt5_80000gn/T/ by default

```

### Project.yaml
```yaml
name: ${PROJECT}
description: A Foo Description
runtime: nodejs
template:
  description: A Bar Description
```
### Console Output
```
Please choose a template (16/227 shown):
 azure-typescript                   A Foo Description
This command will walk you through creating a new Pulumi project.

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name (pulumi-new-test):  
project description (A Bar Description): 
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
