### ISSUE TITLE
Make `pulumi login` respect configuration in `Pulumi.yaml`

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi#15413]
While working on https://github.com/pulumi/actions/issues/1081, we noticed that `pulumi login` wasn't respecting the configuration in `Pulumi.yaml`, and thus errored out when no `cloud-url` was given in the action.  We should improve `pulumi login`, so it takes the setting in `Pulumi.yaml` into account if that file is available to reduce confusion for users.

/xref https://github.com/pulumi/home/issues/3298

**Comment by renannprado** [comment]
I'm facing the same issue.

Workaround:

```yaml
- id: prepare
  run: |
    cloudUrl=`cat Pulumi.yaml | yq '.backend.url'`
    echo "cloudUrl=$cloudUrl" >> $GITHUB_OUTPUT
```
