### ISSUE TITLE
Credentials for 'pulumi up' differ between AWS and GCP

### ISSUE THREAD

**Issue by arunkumar611** [pulumi/pulumi#15474]
When using Pulumi Deployments and ESC with AWS,  the credentials are picked up from environment variables. 

But with GCP, you have to define the credential in pulumiConfig. This means the credentials are stored in the state ID - which isn't desirable. 

ESC Definition for AWS:
```

values:
  aws:
    login:
      fn::open::aws-login:
        oidc:
          duration: 1h
          roleArn:  *****
          sessionName: pulumi-environments-session
    region: us-west-2
  environmentVariables:
    AWS_ACCESS_KEY_ID: ${aws.login.accessKeyId}
    AWS_SECRET_ACCESS_KEY: ${aws.login.secretAccessKey}
    AWS_SESSION_TOKEN: ${aws.login.sessionToken}
    
```
    
   ESC Definition for GCP

```
values:
  gcp:
    login:
      fn::open::gcp-login:
        project: ***
        oidc:
          workloadPoolId: pulumi-oidc-new
          providerId: pulumi
          serviceAccount:  ***
  pulumiConfig:
    gcp:accessToken: ${gcp.login.accessToken}
```
