### ISSUE TITLE
Referencing an externally defined type in a function definition input adds an `Args` suffix

### ISSUE THREAD

**Issue by UnstoppableMango** [pulumi/pulumi#15670]
### What happened?

I am attempting to define a function in a provider schema that accepts an input for a type defined in pulumi/pulumi-tls. The generated nodejs SDK references the type but with an additional `Args` suffix applied to the type name. This fails because that type is not defined with an `Args` suffix in pulumi/pulumi-tls.

Referencing the same type as a resource input does not cause any errors.

While attempting to put together a minimal example to tie to this issue, I noticed the reverse seems to happen in .NET in some circumstances. Nodejs properly names the input, but .NET expects a type with the `Args` suffix. I am able to trigger this by removing the function outputs. These two things don't seem to be related, so I'm not sure why this happens. I suppose because outputs by convention wouldn't an `Args` suffix and inputs would? Is this perhaps being globally applied, while different language SDKs have different conventions?

### Example

[Here](https://github.com/UnstoppableMango/pulumi-kubernetes-the-hard-way/commit/b6fad6df2894e62d441bb465de70b00c9af90bbd) is a commit that can reproduce the .NET SDK error, and [here](https://github.com/UnstoppableMango/pulumi-kubernetes-the-hard-way/commit/f2963d97e32165f4d4cec7514f88f44c7f4a4552) is a commit that can reproduce the nodejs SDK error. I apologize the first diff is not very clean, but the 2nd diff should illustrate how changing the outputs seems to affect it.

A hopefully minimal slice of a schema that can reproduce this. The full schema should be available in the commits above.

Produces nodejs error:

```yaml
functions:
  kubernetes-the-hard-way:index:getAdminCertificate:
    description: Creates a Certificate configured for the cluster admin.
    inputs:
      properties:
        subject:
          $ref: "/tls/v5.0.1/schema.json#/types/tls:index/CertRequestSubject:CertRequestSubject"
    outputs:
      properties:
        cert:
          type: string
      required:
        - cert
```

Produces .NET error:

```yaml
functions:
  kubernetes-the-hard-way:index:getAdminCertificate:
    description: Creates a Certificate configured for the cluster admin.
    inputs:
      properties:
        subject:
          $ref: "/tls/v5.0.1/schema.json#/types/tls:index/CertRequestSubject:CertRequestSubject"
```

### Output of `pulumi about`

My `schema.yaml` references pulumi/tls v5.0.1 and pulumi/command v0.9.2. I also encountered this with tls v5.0.0 and command v0.9.0

```shell
$ pulumi about                                                                                                                                                                                                                  
CLI          
Version      3.109.0
Go Version   go1.22.0
Go Compiler  gc

Host     
OS       darwin
Version  14.3.1
Arch     arm64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/UnstoppableMango
User           UnstoppableMango
Organizations  UnstoppableMango
Token type     personal
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
