### ISSUE TITLE
Referencing an externally defined type in a function input generates an empty module

### ISSUE THREAD

**Issue by UnstoppableMango** [pulumi/pulumi#15672]
### What happened?

I am attempting to define a function in a provider schema that accepts an input for a type defined in pulumi/pulumi-command. When a function output is also defined, the generated nodejs SDK includes an empty `remote` module which fails to compile because it doesn't define anything.

```text
sdk/nodejs/
  remote/
    index.ts # Empty
```

When the function outputs are removed, this module is no longer generated

### Example

The diff is not the cleanest, but [this commit](https://github.com/UnstoppableMango/pulumi-kubernetes-the-hard-way/commit/87be361d5382de46a9b77c0d80fdf8fc3fbe3f8d) introduces the error.

A hopefully minimal example that produces this:

```yaml
functions:
  kubernetes-the-hard-way:index:installOn:
    inputs:
      properties:
        connection:
          $ref: "/command/v0.9.0/schema.json#/types/command:remote:Connection"
    outputs:
      properties:
        file:
          type: string
```

### Output of `pulumi about`

My `schema.yaml` references pulumi/tls v5.0.1 and pulumi/command v0.9.2. I also encountered this with tls v5.0.0 and command v0.9.0

```shell
$ pulumi about                                                                                                                                                                                                                  
CLI          
Version      3.109.0
Go Version   go1.22.0
Go Compiler  gc

Host     
OS       darwin
Version  14.3.1
Arch     arm64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/UnstoppableMango
User           UnstoppableMango
Organizations  UnstoppableMango
Token type     personal
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
