### ISSUE TITLE
Support for "side-by-side" providers

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#15943]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Built-in support for referencing local providers. Something like:

```yaml
name: "my-pulumi-project"
runtime: go
plugins:
  providers:
    - name: mycomponent
      path: ./mycomponent
      run: go run ./...
      write-sdks-to: ./mycomponent/sdk
```

This would allow users to write their own quick "dynamic-like" providers by writing a genuine provider in a framework like [pulumi-go-provider](https://github.com/pulumi/pulumi-go-provider) and bundle the provider with their pulumi program.

Supersedes:
- https://github.com/pulumi/pulumi/issues/9434
- https://github.com/pulumi/pulumi/issues/7534
- https://github.com/pulumi/pulumi/issues/3825
