### ISSUE TITLE
Don't delete a physical id if it was just created

### ISSUE THREAD

**Issue by blampe** [pulumi/pulumi#15982]
There are situations where Pulumi can plan a Create/Delete that result in a resource being created and then immediately deleted in the same operation. I'm proposing that we detect these situations and no-op the delete.

For example in https://github.com/pulumi/pulumi-kubernetes/issues/2948 a new resource is created and an old one is deleted, but their inputs are such that the operation is effectively an update. This isn't something the provider can detect at diff time, but it _is_ something the engine can detect because the physical ID returned by the provider is unchanged.

Our current behavior seems to assume Create will always return a new physical id distinct from anything we plan on deleting. If the provider's Create returns an id that already exists in our state, we should recognize that a new physical resource was _not_ created so there is nothing "old" to delete.

I can't think of a situation where the current behavior is valid or expected, but if we're concerned about preserving backwards-compatibility we could allow providers to opt-in to this new behavior via Configure.

Edge cases to think through:
* deleteBeforeReplace - I think this behavior would be unchanged.
* pending deletes - if we're interrupted between the Create/Delete I don't think we have enough information to determine if the pending delete is "normal" or if it corresponds to one of these problematic cases. We could either: prune pending deletions immediately after a Create completes, or store some additional information like the IDs we had created before we were interrupted.

Related https://github.com/pulumi/pulumi/issues/918
Related https://github.com/pulumi/pulumi/issues/6078
Internal https://pulumi.slack.com/archives/CVC1YFDNX/p1713468828983919?thread_ts=1713303598.172839&cid=CVC1YFDNX
Internal https://docs.google.com/document/d/1Tvz1rUvEMnBwOAPlLsnnmGmx_dzUUmA5iK0PrtqKdD8/edit#heading=h.cc4w6v2hqyxt

**Comment by EronWright** [comment]
Is this essentially reference counting for ids? We'd persist a map of id to ref count.  Seems to solve the "interruption" case.

**Comment by EronWright** [comment]
Here's a valid use-case where multiple logical resources refer to the same physical resource. A Pulumi YAML program using "patch" resources, with two `ConfigMapPatch` resources pointing to a ConfigMap named `example`:

```yaml
name: myprogram
resources:
  cm1:
    type: kubernetes:core/v1:ConfigMapPatch
    properties:
      metadata:
        name: example
      data:
        foo: bar
  cm2:
    type: kubernetes:core/v1:ConfigMapPatch
    properties:
      metadata:
        name: example
      data:
        biz: bam
```

If `cm2` were to be removed, we expect the `Delete` RPC call to clear the `biz` field and to not delete the object.
