### ISSUE TITLE
`pulumi:template` tag in Pulumi.yaml is blank for new projects created from template

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi#16037]
This is using pulumi v3.113.3.

Running `pulumi new` and choosing a template manually (`aws-typescript` in my case), the resulting Pulumi.yaml has this section:
```yaml
config:
  pulumi:tags:
    value:
      pulumi:template: ""
```

On the other hand, running `pulumi new aws-typescript --yes`, it looks as expected:
```yaml
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
```
