### ISSUE TITLE
How do I configure the pulumi backen with china azure Blob?

### ISSUE THREAD

**Issue by mo-silent** [pulumi/pulumi#16305]
### What happened?

I want to configure the China azure blob as a Pulumi backend to store my stack. But Pulumi gives an error:
`error: error listing stacks: could not list bucket: blob (code=NotFound): Get "https://shaprdcne2tfbkendsa.blob.core.windows.net/alicloud-iac?comp=list&delimiter=%2F&maxresults=1000&prefix=pulumi-test%2F.pulumi%2Fstacks%2F&restype=container&sGX%2FSQlwRDQzc9yy+oivGAQskvGRIk3QCjTL9ySTlq3XNG7ZSw6rXabbmc2QBS9GnZ9tBfIvh9Fz3sqrVD624w=%3D": dial tcp: lookup shaprdcne2tfbkendsa.blob.core.windows.net: no such host`

As you can see from the error, Pulumi goes to Global azure to find blobs, so how should I get Pulumi to find blobs in China azure.

### Example

Pulumi.yaml
```yaml
name: aliyun-test
runtime: python
description: test aliyun
version: 0.0.1-beta
# main: module-file/
# stackConfigDir: config/
backend:
  url: azblob://alicloud-iac/pulumi-test?storage_account=shaprdcne2tfbkendsa
config:
  azure-native::location: chinaeast2
  azure-native:environment: china
  azure-native:tenantId: xxxxx
  azure-native:subscriptionId: xxx
  azure-native::msiEndpoint: blob.core.chinacloudapi.cn
```

### Output of `pulumi about`

> pulumi about
CLI
Version      3.116.1
Go Version   go1.22.2
Go Compiler  gc

Plugins
KIND      NAME      VERSION
resource  alicloud  3.55.1
language  python    unknown

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22631 Build 22631
Arch     x86_64

This project is written in python: executable='D:\python\test\testenv\Scripts\python.exe' version='3.12.1'

Dependencies:
NAME             VERSION
pip              23.2.1
pulumi_alicloud  3.55.1
sampleproject    3.0.0

Pulumi locates its logs in C:\Users\silent.mo\AppData\Local\Temp by default
warning: Could not access the backend: error listing stacks: could not list bucket: blob (code=NotFound): Get "https://shaprdcne2tfbkendsa.blob.core.windows.net/alicloud-iac?comp=list&delimiter=%!F(MISSING)&maxresults=1000&prefix=pulumi-test%!F(MISSING).pulumi%!F(MISSING)stacks%!F(MISSING)&restype=container&sGX%!F(MISSING)SQlwRDQzc9yy+oivGAQskvGRIk3QCjTL9ySTlq3XNG7ZSw6rXabbmc2QBS9GnZ9tBfIvh9Fz3sqrVD624w=%!D(MISSING)": dial tcp: lookup shaprdcne2tfbkendsa.blob.core.windows.net: no such host

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
