### ISSUE TITLE
Pulumi Convert fails on complex YAML program

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi#16372]
### What happened?

I tried to convert the below example program into five languages (python, typescript, java, go, csharp). Most of the generated programs failed to compile, for various reasons.

### Example

```yaml
name: argocd
runtime: yaml
description: Deploys ArgoCD using the Helm v4 Chart resource.
resources:
  argocd-ns:
    type: kubernetes:core/v1:Namespace
    properties:
      metadata:
        name: argocd

  argocd-redis-password:
    type: random:RandomPassword
    properties:
      length: 16

  argocd-redis-secret:
    type: kubernetes:core/v1:Secret
    properties:
      metadata:
        name: argocd-redis
        namespace: ${argocd-ns.metadata.name}
      type: Opaque
      stringData:
        auth: ${argocd-redis-password.result}
    options:
      retainOnDelete: true

  argocd-chart:
    type: kubernetes:helm.sh/v4:Chart
    properties:
      chart: argo-cd
      version: "6.11.1"
      namespace: ${argocd-ns.metadata.name}
      repositoryOpts:
        repo: https://argoproj.github.io/argo-helm
      values:
        fullnameOverride: ""

  guestbook:
    type: kubernetes:yaml/v2:ConfigGroup
    properties:
      objs:
      - apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: guestbook
          namespace: ${argocd-ns.metadata.name}
        spec:
          project: default
          source:
            repoURL: https://github.com/argoproj/argocd-example-apps.git
            targetRevision: HEAD
            path: guestbook
          destination:
            server: https://kubernetes.default.svc
            namespace: default
    options:
      dependsOn:
      - ${argocd-chart}

outputs:
  redisPassword: ${argocd-redis-password.result}
```

Run conversion and observe compilation errors:
```
pulumi convert --language python --out python
pulumi convert --language typescript --out typescript
pulumi convert --language java --out java
pulumi convert --language go --out go
pulumi convert --language csharp --out csharp
```

### Output of `pulumi about`

```
❯ p about
CLI          
Version      3.117.0
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME        VERSION
language  java        unknown
resource  kubernetes  4.13.1
resource  random      4.16.2

Host     
OS       darwin
Version  14.4.1
Arch     arm64
```

### Additional context

The specific problems that I encountered:
1. Go: Mishandled a stringptr.
2. Java: erroneously assumes that `SecretArgsBuilder` has `.stringData(String key, Output<String> data)`.
3. Java: wrong packages were imported.
4. Java/CSharp: erroneously used CustomResourceOptions instead of ComponentResourceOptions.
5. Java: failed to handle Optional output property correctly.
6. Python: failed to enable the venv runtime option.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
