### ISSUE TITLE
Running `pulumi up -f -y --continue-on-error` hangs indefinitely

### ISSUE THREAD

**Issue by rquitales** [pulumi/pulumi#16373]
### What happened?

`pulumi up -f -y --continue-on-error` will run continuously until it is interrupted with `Ctrl+C` if a resource errors when it needs to be updated, or created.
If the resource in question is to be deleted, then the command terminates as expected.

### Example

This has been reproduced in 2 different providers: pulumi-github and pulumi-kubernetes.

The following is a repro with the Pulumi Kubernetes YAML:

1. Create a stack and run `pulumi up -f -y` on the following:
```yaml
name: kubernetes-yaml
runtime: yaml
description: A minimal Kubernetes Pulumi YAML program
config:
  pulumi:tags:
    value:
      pulumi:template: kubernetes-yaml
outputs:
  name: ${deployment.metadata.name}
resources:
  deployment:
    properties:
      spec:
        replicas: 1
        selector:
          matchLabels: ${appLabels}
        template:
          metadata:
            labels: ${appLabels}
          spec:
            containers:
              - image: nginx
                name: nginx
    type: kubernetes:apps/v1:Deployment
variables:
  appLabels:
    app: nginx
```

2. Update the Pulumi.yaml file with the following program and run `pulumi up -f -y --continue-on-error`. This forces the update operation to fail, as it'll take longer than 2 seconds to spin up the new replicas. Notice that this operation runs indefinitely.
```yaml
name: kubernetes-yaml
runtime: yaml
description: A minimal Kubernetes Pulumi YAML program
config:
  pulumi:tags:
    value:
      pulumi:template: kubernetes-yaml
outputs:
  name: ${deployment.metadata.name}
resources:
  deployment:
    properties:
      spec:
        replicas: 100
        selector:
          matchLabels: ${appLabels}
        template:
          metadata:
            labels: ${appLabels}
          spec:
            containers:
              - image: nginx
                name: nginx
    type: kubernetes:apps/v1:Deployment
    options:
    # Set a really small custom timeout so we gurantee the deployment will error as it will take longer than 2s to spin up 100 replicas.
      customTimeouts:
        create: 2s
        update: 2s
        delete: 2s
variables:
  appLabels:
    app: nginx
```

3. To simulate a replacement (delete before create) operation, you can use the following program which also hangs with `--continue-on-error`:
```yaml
name: kubernetes-yaml
runtime: yaml
description: A minimal Kubernetes Pulumi YAML program
config:
  pulumi:tags:
    value:
      pulumi:template: kubernetes-yaml
outputs:
  name: ${deployment.metadata.name}
resources:
  deployment:
    properties:
      spec:
        replicas: 100
        selector:
          matchLabels: ${appLabels}
        template:
          metadata:
            labels: ${appLabels}
          spec:
            containers:
              - image: nginx
                name: nginx
    type: kubernetes:apps/v1:Deployment
    options:
    # Set a really small custom timeout so we gurantee the deployment will error as it will take longer than 2s to spin up 100 replicas.
      customTimeouts:
        create: 2s
        update: 2s
        delete: 2s
variables:
  appLabels:
    app: nginx
    newapp: newvalue
```

### Output of `pulumi about`

CLI          
Version      3.118.0
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  kubernetes  unknown
language  yaml        unknown

Host     
OS       darwin
Version  13.3.1
Arch     arm64

This project is written in yaml

TYPE                           URN
pulumi:pulumi:Stack            urn:pulumi:dev::kubernetes-yaml::pulumi:pulumi:Stack::kubernetes-yaml-dev
pulumi:providers:kubernetes    urn:pulumi:dev::kubernetes-yaml::pulumi:providers:kubernetes::default
kubernetes:apps/v1:Deployment  urn:pulumi:dev::kubernetes-yaml::kubernetes:apps/v1:Deployment::deployment

Found no pending operations associated with dev

### Additional context

Originally identified from this minimal repro: https://github.com/pulumi/pulumi-command/issues/435#issuecomment-2114250614

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
