### ISSUE TITLE
Unmatched styling for `pyproject.toml` generated by Pulumi's CLI

### ISSUE THREAD

**Issue by garysassano** [pulumi/pulumi#16657]
### What happened?

When using `pulumi new python`, Pulumi generates a `pyproject.toml` file with the following file structure:

```toml
[build-system]
  requires = ["poetry-core"]
  build-backend = "poetry.core.masonry.api"

[tool]
  [tool.poetry]
    package-mode = false
    [tool.poetry.dependencies]
      pulumi = ">=3.0.0,<4.0.0"
      python = "^3.8"
```

It would be much more pleasant if the `pyproject.toml` generated by Pulumi's CLI followed the same standard as Poetry's CLI:

```toml
[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
pulumi = ">=3.0.0,<4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Example

see above

### Output of `pulumi about`

see above

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
