### ISSUE TITLE
`pulumi new python` fails when installed Poetry version <1.8.0

### ISSUE THREAD

**Issue by garysassano** [pulumi/pulumi#16656]
### What happened?

```sh
❯ pulumi install
Installing dependencies...


'name'
error: installing dependencies: exit status 1
```

### Example

see above

### Output of `pulumi about`

see above

### Additional context

When creating a new Python project using the `pulumi new python` CLI command and selecting `poetry` as the toolchain option, Pulumi generates a `pyproject.toml` file with the following content:

```toml
[build-system]
  requires = ["poetry-core"]
  build-backend = "poetry.core.masonry.api"

[tool]
  [tool.poetry]
    package-mode = false
    [tool.poetry.dependencies]
      pulumi = ">=3.0.0,<4.0.0"
      python = "^3.8"
```

The issue arises from the use of the `package-mode` key, which was introduced in [Poetry 1.8.0](https://python-poetry.org/blog/announcing-poetry-1.8.0/#better-support-for-non-package-projects). Users with older versions of Poetry installed will encounter an error when attempting to create a new Python project with Pulumi using the `poetry` toolchain.

The docs should clearly state that Poetry version >= 1.8.0 is required to use the `poetry` toolchain in Pulumi.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
