### ISSUE TITLE
Plain resource input properties inputtified in nodejs, Go and python

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi#16810]
Resource properties which are marked as "plain" in the schema are generated with "inputty" types for the Go, Node.js and Python SDKs after switching from generating the SDKs using a custom generation program depending on `pulumi/pkg` `v3.107.0` to using the `pulumi package gen-sdk` command using `3.113.2` or greater (tested up to `3.126.0`) of the pulumi CLI resource.

Original discovery thread: https://github.com/pulumi/pulumi-aws-apigateway/pull/161#discussion_r1692036683

### Schema definition

```yaml
 routes: 
   type: array 
   items: 
     "$ref": "#/types/aws-apigateway:index:Route" 
     plain: true 
   plain: true 
```

### Go SDK diff
```diff
-	Routes []RouteArgs
+	Routes []RouteInput
```

### Node.js SDK diff
```diff
-    routes?: inputs.RouteArgs[];
+    routes?: pulumi.Input<inputs.RouteArgs>[];
```

### [Python SDK diff](https://github.com/pulumi/pulumi-aws-apigateway/pull/161/files#diff-7c1ad26dc335e265df39b34fffce67ffb016447560ec31f0242a88b0c8a1e2e8)
```diff
-    def routes(self, value: Optional[Sequence['RouteArgs']]):
+    def routes(self, value: Optional[Sequence[pulumi.Input['RouteArgs']]]):
```
