### ISSUE TITLE
Pulumi CLI hangs on MacOS 14.5

### ISSUE THREAD

**Issue by AndrewBarba** [pulumi/pulumi#16871]
### What happened?

When running `pulumi up` on MacOS 14.5 the program hangs with:

```
Updating (prod):
     Type                 Name                        Status      Info
     pulumi:pulumi:Stack  swift-cloud-demo-prod-prod  running     (CodeFragmentMetadata.cpp:48 instruction_extents_for_arm_address)
```

This happens 1 every 5 or so attempts. Then I'm forced to kill the process, run `pulumi cancel` and try again.

### Example

```
PULUMI_CONFIG_PASSPHRASE=passphrase pulumi up --skip-preview --yes --stack prod
```

```
name: swift-cloud-demo-prod
runtime: yaml
backend:
  url: file:///Users/andrewbarba/Code/SwiftCloud/swift-cloud/.cloud/state
resources:
  my-new-bucket-ownershipcontrols:
    type: aws:s3:BucketOwnershipControls
    properties:
      bucket: ${my-new-bucket}
      rule:
        objectOwnership: ObjectWriter
  my-new-bucket-publicaccessblock:
    type: aws:s3:BucketPublicAccessBlock
    properties:
      blockPublicAcls: false
      bucket: ${my-new-bucket}
  my-new-bucket:
    type: aws:s3:Bucket
outputs:
  bucketName: ${my-new-bucket.id}
```

### Output of `pulumi about`

```
CLI          
Version      3.127.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME  VERSION
resource  aws   unknown
language  yaml  unknown

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in yaml

Current Stack: organization/swift-cloud-demo-prod/prod

TYPE                                                    URN
pulumi:pulumi:Stack                                     urn:pulumi:prod::swift-cloud-demo-prod::pulumi:pulumi:Stack::swift-cloud-demo-prod-prod
pulumi:providers:aws                                    urn:pulumi:prod::swift-cloud-demo-prod::pulumi:providers:aws::default
aws:s3/bucket:Bucket                                    urn:pulumi:prod::swift-cloud-demo-prod::aws:s3/bucket:Bucket::my-new-bucket
aws:s3/bucketPublicAccessBlock:BucketPublicAccessBlock  urn:pulumi:prod::swift-cloud-demo-prod::aws:s3/bucketPublicAccessBlock:BucketPublicAccessBlock::my-new-bucket-publicaccessblock
aws:s3/bucketOwnershipControls:BucketOwnershipControls  urn:pulumi:prod::swift-cloud-demo-prod::aws:s3/bucketOwnershipControls:BucketOwnershipControls::my-new-bucket-ownershipcontrols


Found no pending operations associated with prod

Backend        
Name           M1-Max-MacBook-Pro.local
URL            file:///Users/andrewbarba/Code/SwiftCloud/swift-cloud/.cloud/state
User           andrewbarba
Organizations  
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/q3/hx0xy_b9031033w2mnzp_z9w0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
