### ISSUE TITLE
Pulumi convert name shadowing import modules with variable names

### ISSUE THREAD

**Issue by brandonpollack23** [pulumi/pulumi#17008]
### What happened?

Pulumi convert on:

```yaml
name: awsx
runtime: yaml
resources:
  cluster:
    type: aws:ecs:Cluster
  lb:
    type: awsx:lb:ApplicationLoadBalancer
  nginx:
    type: awsx:ecs:FargateService
    properties:
      cluster: ${cluster.arn}
      taskDefinitionArgs:
        container:
          image: nginx:latest
          cpu: 512
          memory: 128
          portMappings:
            - containerPort: 80
              targetGroup: ${lb.defaultTargetGroup}
outputs:
  url: ${lb.loadBalancer.dnsName}
```

generates 

```go
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v6/go/aws/ecs"
	awsxecs "github.com/pulumi/pulumi-awsx/sdk/v2/go/awsx/ecs"
	"github.com/pulumi/pulumi-awsx/sdk/v2/go/awsx/lb"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		cluster, err := ecs.NewCluster(ctx, "cluster", nil)
		if err != nil {
			return err
		}
		lb, err := lb.NewApplicationLoadBalancer(ctx, "lb", nil)
		if err != nil {
			return err
		}
		_, err = awsxecs.NewFargateService(ctx, "nginx", &awsxecs.FargateServiceArgs{
			Cluster: cluster.Arn,
			TaskDefinitionArgs: &awsxecs.FargateServiceTaskDefinitionArgs{
				Container: &awsxecs.TaskDefinitionContainerDefinitionArgs{
					Image:  pulumi.String("nginx:latest"),
					Cpu:    pulumi.Int(512),
					Memory: pulumi.Int(128),
					PortMappings: awsxecs.TaskDefinitionPortMappingArray{
						&awsxecs.TaskDefinitionPortMappingArgs{
							ContainerPort: pulumi.Int(80),
							TargetGroup:   loadBalancer.DefaultTargetGroup,
						},
					},
				},
			},
		})
		if err != nil {
			return err
		}
		ctx.Export("url", lb.LoadBalancer.ApplyT(func(loadBalancer *lb.LoadBalancer) (string, error) {
			return loadBalancer.DnsName, nil
		}).(pulumi.StringOutput))
		return nil
	})
}
```

(after applying #17005, which fixes #9664 )

There is still another issue which is the ApplicationLoadBalancer with the name overlap `lb`.

There are 2 issues:

1. Name overlap lb conflicts with package import
2. Type of the input to the applyT'd function should be `lb.ApplicationLoadBalancer` not `lb.Loadbalancer`

I thought this could be solved by renaming the loadbalancer from "lb" to something else, but the generated code still incorrectly passes a lambda with an input of a non existent type `lb.LoadBalancer` that should be `lb.ApplicationLoadBalancer`

Workaround for problem 1:
Rename your resources

There is no workaround for problem 2, I suspect it happens because there hsould be another (aliased) import that is missing for aws/lb (alb also works)

### Example

See above

### Output of `pulumi about`

See above

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
