### ISSUE TITLE
Output Types are not generated correctly in nested outputs (eg awsx.lb.LoadBalancer.HostName)

### ISSUE THREAD

**Issue by brandonpollack23** [pulumi/pulumi#17011]
### What happened?

As observed in https://github.com/pulumi/pulumi/issues/17008#issuecomment-2296729332 genApply in gen_program_expression.go for the go generator does not differentiate between primitives and pulumi.* output styles, resulting in non executable `pulumi convert` programs.

### Example

pulumi generate on

```
name: awsx
runtime: yaml
resources:
  cluster:
    type: aws:ecs:Cluster
  loadBalancer:
    type: awsx:lb:ApplicationLoadBalancer
  nginx:
    type: awsx:ecs:FargateService
    properties:
      cluster: ${cluster.arn}
      taskDefinitionArgs:
        container:
          image: nginx:latest
          cpu: 512
          memory: 128
          portMappings:
            - containerPort: 80
              targetGroup: ${loadBalancer.defaultTargetGroup}
outputs:
  url: ${loadBalancer.loadBalancer.dnsName}
```

results in an export of:

```go
		ctx.Export("url", loadBalancer.LoadBalancer.ApplyT(func(loadBalancer *awslb.LoadBalancer) (string, error) {
			return loadBalancer.DnsName, nil
		}).(pulumi.StringOutput))
```

Which should use pulumi.StringOutput for the inner lambda return value.

### Output of `pulumi about`

na

### Additional context

I believe we need to add more context to the generator it can carry with it so it is aware if it is generating an output expression or not, but I must admit I'm not familiar enough with the system yet to know for sure.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
