### ISSUE TITLE
bug: `pulumi install` fails with `flag provided but not defined: -refresh` when using option `refresh: always`

### ISSUE THREAD

**Issue by tmeckel** [pulumi/pulumi#17261]
### What happened?

When specifying `refresh: always` in Pulumi.yaml the command `pulumi install` will fail with the error:

`flag provided but not defined: -refresh`

 

### Example

1. `Pulumi.yaml`:

```yaml
name: test-preview-import
runtime:
  name: nodejs
  options:
    refresh: always
    packagemanager: yarn
description: Pulumi program to test to create import.json in preview
config:
  pulumi:tags:
    value:
      pulumi:template: typescript

```

1. `pulumi install`

```
pulumi install
flag provided but not defined: -refresh

Usage of /home/vagrant/.pulumi/bin/pulumi-language-nodejs:
```

### Output of `pulumi about`

```
CLI          
Version      3.132.0
Go Version   go1.23.1
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

Current Stack: organization/test-preview-import/default

TYPE                    URN
pulumi:pulumi:Stack     urn:pulumi:default::test-preview-import::pulumi:pulumi:Stack::test-preview-import-default
pulumi:providers:azure  urn:pulumi:default::test-preview-import::pulumi:providers:azure::test-provider


Found no pending operations associated with default

Backend        
Name           pulumi
URL            file://./.stacks
User           vagrant
Organizations  
Token type     personal
```

### Additional context

Seems that **all** commands that do not specify the `--refresh` command line option are affected by the error.

`pulumi about` yields the same error for example:

```
pulumi about
flag provided but not defined: -refresh

Usage of /home/vagrant/.pulumi/bin/pulumi-language-nodejs:
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
@tmeckel, looks like you've nested `refresh: always` under the _runtime_ options, when it needs to be a level higher, e.g.:

```yaml
name: test-preview-import
options:
  refresh: always
runtime:
  name: nodejs
  options:
    packagemanager: yarn
description: Pulumi program to test to create import.json in preview
config:
  pulumi:tags:
    value:
      pulumi:template: typescript
```
