### ISSUE TITLE
Engine marking non-secret values as secret

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#17440]
### What happened?

As part of diagnosing https://github.com/pulumi/pulumi-digitalocean/issues/308, I saw this diff:

```
Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::dev-yaml::pulumi:pulumi:Stack::dev-yaml-dev]
    ~ digitalocean:index/app:App: (update)
        [id=acfa96e1-7680-4dae-bd2d-3317ff15b24c]
        [urn=urn:pulumi:dev::dev-yaml::digitalocean:index/app:App::topic]
      ~ spec: {
          ~ services: [
              ~ [0]: {
                      ~ envs            : [
                          ~ [0]: {
                                  ~ key  : [secret] => "CA_CERT"
                                  ~ scope: [secret] => "RUN_AND_BUILD_TIME"
                                  ~ value: [secret] => [secret]
                                }
                        ]
                      - instanceCount   : [secret]
                      - instanceSizeSlug: [secret]
                    }
            ]
        }
```

Only `value` should be a secret. `instanceCount` and `instanceSizeSlug` should not be secrets.

### Example

Run `pulumi up` with the `providers.all` ESC env on this program:

```yaml
name: dev-yaml
runtime: yaml
resources:
  topic:
    type: digitalocean:App
    properties:
      spec:
        region: ams
        name: app
        services:
          - name: service-name
            git:
              repoCloneUrl: "https://github.com/digitalocean/sample-golang.git"
              branch: main
            envs:
              - key: CA_CERT
                scope: RUN_AND_BUILD_TIME
                type: GENERAL
                value: "my-secret-value"
```

After the program is created, run `pulumi preview --diff` to see the extra secrets.

### Output of `pulumi about`

CLI          
Version      3.134.2-dev.0
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  digitalocean  unknown
language  yaml          unknown

Host     
OS       darwin
Version  14.6.1
Arch     arm64

This project is written in yaml

Current Stack: pulumi/dev-yaml/dev

TYPE                           URN
pulumi:pulumi:Stack            urn:pulumi:dev::dev-yaml::pulumi:pulumi:Stack::dev-yaml-dev
pulumi:providers:digitalocean  urn:pulumi:dev::dev-yaml::pulumi:providers:digitalocean::default
digitalocean:index/app:App     urn:pulumi:dev::dev-yaml::digitalocean:index/app:App::topic

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ian-pulumi-corp
User           ian-pulumi-corp
Organizations  ian-pulumi-corp, pulumi
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/fg/_1q36r4j6yx0rwz2fbhjd5y40000gn/T/ by default

### Additional context

I'm running against digitalocean v4.33.0.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
