### ISSUE TITLE
pulumi convert loses InvokeOptions silently

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#17525]
### What happened?

pulumi convert translating from YAML to TypeScript loses InvokeOptions silently on invokes.

### Example

Here is a valid AWS program:

```
name: invoke-eprov
runtime: yaml
description: A minimal AWS Pulumi YAML program

resources:
  provider:
    type: pulumi:providers:aws
    properties:
      region: us-west-2

variables:
  cur-region:
    fn::invoke:
      arguments: {}
      function: aws:getRegion
      options:
        provider: ${provider}

outputs:
  cur-region: ${cur-region}

```

As I try to convert it to TypeScript I get:

```
pulumi convert --from yaml --language typescript --generate-only
```

This program:

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

export = async () => {
    const curRegionVar = aws.getRegionOutput({});
    const provider = new aws.Provider("provider", {region: "us-west-2"});
    return {
        "cur-region": curRegionVar,
    };
}

```

That is not correct as InvokeOptions for getReginOutput are lost.

No warnings, no error. Passig --strict does not help.

### Output of `pulumi about`

```
CLI          
Version      3.130.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME  VERSION
resource  aws   unknown
language  yaml  unknown

Host     
OS       darwin
Version  14.6.1
Arch     arm64

This project is written in yaml

Current Stack: anton-pulumi-corp/invoke-eprov/dev

TYPE                  URN
pulumi:pulumi:Stack   urn:pulumi:dev::invoke-eprov::pulumi:pulumi:Stack::invoke-eprov-dev
pulumi:providers:aws  urn:pulumi:dev::invoke-eprov::pulumi:providers:aws::provider


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/anton-pulumi-corp
User           anton-pulumi-corp
Organizations  anton-pulumi-corp, moolumi, demo, pulumi
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/gd/3ncjb1lj5ljgk8xl5ssn_gvc0000gn/T/com.apple.shortcuts.mac-helper// by default

```

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
