### ISSUE TITLE
Project Level Config: If using structured config, stack-level config overwrites the entire object and not just the given fields

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi#17948]
### What happened?

I have a project level config like this:
```
config:
  randomstuff:
    value:
      prefix: alpha 
      length: 3
``` 

And I have a stack level config like this:
```
config:
  randomstuff:
    prefix: omega
```

I have this code:
```
import pulumi
config = pulumi.Config()
pulumi.export("config", config.get_object("randomstuff"))
```

Which outputs:
```
    config: {
        prefix: "omega"
    }
```

As you can see it is missing the `length` property from the stack level config.

I would expect the stack level config to overlay on the project level config instead of replacing the entire object.

### Example

See above

### Output of `pulumi about`

CLI          
Version      3.142.0
Go Version   go1.23.3
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  python  unknown
resource  random  4.16.7

Host     
OS       darwin
Version  15.1
Arch     x86_64

Backend        
Name           pulumi.com

Dependencies:
NAME           VERSION
pip            24.3.1
pulumi_random  4.16.7
setuptools     75.6.0
wheel          0.45.1

### Additional context

If I use an ESC environment instead of project level config, it works as expected and overlays the local value.
So if I have an environment like:
```
values:
  randomSettings:
    prefix: env
    length: 4
  pulumiConfig:
    randomstuff:
      prefix: ${randomSettings.prefix}
      length: ${randomSettings.length}
```
And include that in my stack config file above, the code outputs:
```
    config: {
        length: 4
        prefix: "omega"
    }
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
