### ISSUE TITLE
Autonaming isn't resolved to the top level for provider resources

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#18033]
### What happened?

Founds the first bug in autonaming configuration... luckily this is well before any user can hit it.

Here is my sample program for Azure Native:

```yaml
name: autonaming
description: Autonaming configuration example
runtime: yaml
config:
  pulumi:autonaming:
    value:
      pattern: ${project}-${stack}-${name}
      providers:
        azure-native:
          resources:
            azure-native:storage:StorageAccount:
              pattern: ${project}${stack}${name}${alphanum(6)}
resources:
  rg:
    type: azure-native:resources:ResourceGroup
  sa:
    type: azure-native:storage:StorageAccount
    properties:
      resourceGroupName: ${rg.name}
      sku:
        name: Standard_LRS
      kind: StorageV2
outputs:
  rgName: ${rg.name}
  saName: ${sa.name}
```

Expected result: both resource group and storage account are named as specified.
Actual result: resource group is named according to our default policy, not user's configuration.

It starts working correctly if I specify the provider pattern explicitly:

```
...
pattern: ${project}-${stack}-${name}
  providers:
    azure-native:
      pattern: ${project}-${stack}-${name}
...
```

### Output of `pulumi about`

CLI 3.143.0, a custom version of Azure Native

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
