### ISSUE TITLE
Consider failing fast on gen-sdk when schema has dangling type references

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#18120]
### What happened?

This comes from a chat in Community Slack. The user was confused why this schema under `pulumi package gen-sdk ./schema.yaml --language nodejs` was generating non-compiling TypeScript code:

```
import {RepositoryEncryptionConfiguration} from "RepositoryEncryptionConfiguration";
```

Bad schema:

```
name: 'echobox'
resources:
  echobox:ecr:repository:
    properties:
      encryptionConfigurations:
        type: array
        items:
          "$ref": "#/types/aws:ecr%2FRepositoryEncryptionConfiguration:RepositoryEncryptionConfiguration"
      imageScanningConfiguration:
        "$ref": "#/types/aws:ecr%2FRepositoryImageScanningConfiguration:RepositoryImageScanningConfiguration"
```

The correct schema works well:

```
name: 'echobox'
resources:
  echobox:ecr:repository:
    properties:
      encryptionConfigurations:
        type: array
        items:
          "$ref": "/aws/v6.65.0/schema.json#/types/aws:ecr%2FRepositoryEncryptionConfiguration:RepositoryEncryptionConfiguration"
      imageScanningConfiguration:
        "$ref": "/aws/v6.65.0/schema.json#/types/aws:ecr%2FRepositoryImageScanningConfiguration:RepositoryImageScanningConfiguration"
```

It took some time though to see that. It would be nice if the dangling references were detected early though and at least warned about so that it's clear at authoring time something is not right with the schema. 

### Example

See above.

### Output of `pulumi about`

```
CLI          
Version      3.141.0
Go Version   go1.23.3
Go Compiler  gc

Host     
OS       darwin
Version  14.6.1
Arch     arm64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/anton-pulumi-corp
User           anton-pulumi-corp
Organizations  anton-pulumi-corp, moolumi, demo, pulumi
Token type     personal

Pulumi locates its logs in /var/folders/gd/3ncjb1lj5ljgk8xl5ssn_gvc0000gn/T/com.apple.shortcuts.mac-helper// by default

```

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Makes sense. The only thing we need to be careful about is that you can reference a type that doesn't exist in a schema, an "opaque token type" ([ref](https://github.com/pulumi/pulumi/blob/6f113c26c1f3965bf6866ede711786e6a88fb174/pkg/codegen/schema/schema.go#L292-L299)), which historically has been used to refer to "overlay" types that don't exist in the schema. I don't know how prevalent those are these days now that we've schematized more of those things. If we're able to do it in a way that doesn't affect those, we probably will want to emit a warning first for a while, before considering making it an error (as an aside, it'd be nice if we also had a "strict" mode that folks could opt-in to to treat warnings as errors).

**Comment by iwahbe** [comment]
We should be able to safely validate that type references either start with an allowed token prefix for the package, or are correctly external:

```yaml
name: 'echobox'
resources:
  echobox:ecr:repository:
    properties:
      shouldError:
        type: array
        items:
          # Always invalid, since no type in `echobox` can start with `aws:`
          "$ref": "#/types/aws:ecr%2FRepositoryEncryptionConfiguration:RepositoryEncryptionConfiguration" 
      isOk:
        type: array
        items:
          # This is a dangling type reference, but it could be valid. Making this error is a breaking change
          "$ref": "#/types/echobox:ecr%2FRepositoryEncryptionConfiguration:RepositoryEncryptionConfiguration"
      correctlyExternal:
        # This is an external type, how we validate external types is a separate discussion
        "$ref": "/aws/v6.65.0/schema.json#/types/aws:ecr%2FRepositoryImageScanningConfiguration:RepositoryImageScanningConfiguration"
```
