### ISSUE TITLE
Kubeconfig does not apply

### ISSUE THREAD

**Issue by matterai** [pulumi/pulumi#18456]
1. There is a Github Action with such step:
```yaml
      - id: get-credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ vars.GKE_CLUSTER_NAME }}
          location: ${{ vars.GOOGLE_LOCATION }}-a
```
According [the doc](https://github.com/google-github-actions/get-gke-credentials/tree/v2/?tab=readme-ov-file#outputs) it setting `$KUBECONFIG` env variable.
Then I use `pulumi config` to set up variables and `pulumi up` to create a namespace in my GKE cluster:
```yaml
      - id: set_pulumi_config
        name: set pulumi config
        working-directory: ./mirai/pulumi
        run: |
          pulumi stack select --create gke.monitoring
          pulumi config set gcp:project ${{ vars.GOOGLE_PROJECT_ID }}
          pulumi config set gcp:region ${{ vars.GOOGLE_LOCATION }}
          pulumi config set mirai:pulumiOrg ${{ vars.PULUMI_ORG }}
          pulumi config set mirai:githubSha ${{ github.sha }}
          pulumi config set gke_monitoring:grafanaAdminPassword --secret ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
          pulumi config set gke_monitoring:grafanaDomain ${{ vars.GRAFANA_DOMAIN }}
          pulumi config set gke_monitoring:githubOrg ${{ github.repository_owner }}
          pulumi config set gke_monitoring:githubOauthClientId ${{ vars.GH_OAUTH_CLIENT_ID }}
          pulumi config set gke_monitoring:githubOauthSecret --secret ${{ secrets.GH_OAUTH_SECRET }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - id: pulumi_up
        name: pulumi up
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: gke.monitoring
          work-dir: ./mirai/pulumi
          refresh: true
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```
Pulumi stack running on `pulumi up`:
```
export class GkeMonitoringStack extends pulumi.ComponentResource {
  public static readonly stackName = 'gke.monitoring';

  constructor(
    name: string,
    args: {
      gcpProjectId: string;
      gcpRegion: string;
      grafanaPassword: string;
      grafanaDomain: string;
      githubOrg: string;
      githubOauthClientId: string;
      githubOauthSecret: string;
      devDomain: pulumi.Output<any>;
      githubSha: string;
    },
    opts?: pulumi.ComponentResourceOptions,
  ) {
    super(
      'mirai:stacks:GkeMonitoringStack',
      GkeMonitoringStack.stackName,
      args,
      opts,
    );

    const grafanaIp = new gcp.compute.GlobalAddress(`${name}-grafana-ip`, {
      name: `${name}-grafana-ip`,
    });

    const provider = new k8s.Provider(`${name}-monitoring-provider`, {});

    const namespace = new k8s.core.v1.Namespace(
      `${name}-monitoring-namespace`,
      { metadata: { name: `monitoring` } },
      { dependsOn: [provider], provider: provider },
    );
...
```
According [the doc](https://www.pulumi.com/registry/packages/kubernetes/api-docs/provider/#kubeconfig_python) it can source config from `KUBECONFIG`. 
But when I run my action, I got an error:
```
    kubernetes:core/v1:Namespace (mirai-monitoring-namespace):
      warning: configured Kubernetes cluster is unreachable: failed to parse kubeconfig data in `kubernetes:config:kubeconfig`- couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct *** APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" ***
      error: failed to read resource state due to unreachable cluster. If the cluster was deleted, you can remove this resource from Pulumi state by rerunning the operation with the PULUMI_K8S_DELETE_UNREACHABLE environment variable set to "true"
```
What am I doing wrong?

I also tried to configure `kubernetes:config:kubeconfig` and pass kubeconfig JSON to it directly, but nothing helps.

**Comment by lunaris** [comment]
Hi @matterai, I'm not 100% sure of all the interactions going on here, but at first glance I'm wondering if setting `KUBECONFIG` in the `env` of the Pulumi action works for you? E.g.:

```
      - id: pulumi_up
        name: pulumi up
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: gke.monitoring
          work-dir: ./project/pulumi
          refresh: true
          upsert: true
        env:
          KUBECONFIG: ${{ env.KUBECONFIG }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```
