### ISSUE TITLE
Bug when branch reference is changed in Pulumi Stack declaratively

### ISSUE THREAD

**Issue by namanChaturvedi** [pulumi/pulumi#18492]
### What happened?

Updated Stack.yaml to change branch reference decoratively, and applied to be synced via operator. The logs message appeared during reconciliation about bug. 

### Example

Updated Stack.yaml branch reference

BEFORE -

```yaml
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: stage
  namespace: pulumi-operator
spec:
  backend: >-
    s3://DeployerStateStore?endpoint=example.com&disableSSL=false&s3ForcePathStyle=true&region=region1
  branch: refs/heads/xyz_branch #ToDo change this
  destroyOnFinalize: true
  envRefs:
    AWS_ACCESS_KEY_ID:
      secret:
        key: AWS_ACCESS_KEY_ID
        name: pulumi-aws-secrets
      type: Secret
    AWS_DEFAULT_REGION:
      literal:
        value: region1
      type: Literal
    AWS_SECRET_ACCESS_KEY:
      secret:
        key: AWS_SECRET_ACCESS_KEY
        name: pulumi-aws-secrets
      type: Secret
    DEPLOYER_ENABLE_ARGO_MONITORING:
      literal:
        value: 'true'
      type: Literal
  gitAuth:
    sshAuth:
      sshPrivateKey:
        secret:
          key: sshPrivateKey
          name: git-secret
        type: Secret
  projectRepo: enterprisegiturl/org/repo.git
  repoDir: /
  stack: stage-env
```

AFTER -

```yaml
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: stage
  namespace: pulumi-operator
spec:
  backend: >-
    s3://DeployerStateStore?endpoint=example.com&disableSSL=false&s3ForcePathStyle=true&region=region1
  branch: refs/heads/master #changed the branch
  destroyOnFinalize: true
  envRefs:
    AWS_ACCESS_KEY_ID:
      secret:
        key: AWS_ACCESS_KEY_ID
        name: pulumi-aws-secrets
      type: Secret
    AWS_DEFAULT_REGION:
      literal:
        value: region1
      type: Literal
    AWS_SECRET_ACCESS_KEY:
      secret:
        key: AWS_SECRET_ACCESS_KEY
        name: pulumi-aws-secrets
      type: Secret
    DEPLOYER_ENABLE_ARGO_MONITORING:
      literal:
        value: 'true'
      type: Literal
  gitAuth:
    sshAuth:
      sshPrivateKey:
        secret:
          key: sshPrivateKey
          name: git-secret
        type: Secret
  projectRepo: enterprisegiturl/org/repo.git
  repoDir: /
  stack: stage-env
```

### Output of `pulumi about`
```
{
    "level": "error",
    "ts": "2025-02-07T16:27:26.233Z",
    "logger": "controller_stack",
    "msg": "Failed to update Stack",
    "Request.Namespace": "pulumi-operator",
    "Request.Name": "stage",
    "Stack.Name": "stage",
    "error": "failed to run update: exit status 255\ncode: 255\nstdout: Updating (stage):\n\nstderr: error: The Pulumi CLI encountered a snapshot integrity error. This is a bug!\n\n================================================================================\nWe would appreciate a report: https://github.com/pulumi/pulumi/issues/\nPlease provide all of the below text in your report.\n================================================================================\nPulumi Version:    v3.130.0\nGo Version:        go1.22.6\nGo Compiler:       gc\nArchitecture:      amd64\nOperating System:  linux\nCommand:           pulumi up --yes --skip-preview --exec-kind=auto.local --exec-agent=pulumi-kubernetes-operator/v1.16.0 --stack stage --non-interactive\nError:             resource urn:pulumi:stage::deployer::onedevx:deployer:Workload$onedevx:deployer:Component$kubernetes:apps/v1:Deployment::release-manager-onedevx-release-manager's dependency urn:pulumi:stage::deployer::onedevx:deployer:Workload$onedevx:deployer:Component$kubernetes:batch/v1:Job::release-manager-onedevx-release-manager-pg-prov refers to missing resource\n\nStack Trace:\n\ngoroutine 1 [running]:\nruntime/debug.Stack()\n\t/opt/hostedtoolcache/go/1.22.6/x64/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x2d16148?, 0x99?}, {0xc002a1d910?, 0x99?, 0x40?})\n\t/home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:313 +0x34\ngithub.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0xc002262cf0)\n\t/home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:217 +0x127f\ngithub.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).getSnapshot(0xc001e421b0, {0x37b10a8, 0x4f0c020}, {0x37891e0, 0x4f0c020}, 0xc002338b40)\n\t/home/runner/work/pulumi/pulumi/pkg/backend/diy/state.go:180 +0x106\ngithub.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyStack).Snapshot(0xc000fde378, {0x37b10a8, 0x4f0c020}, {0x37891e0, 0x4f0c020})\n\t/home/runner/work/pulumi/pulumi/pkg/backend/diy/stack.go:62 +0x85\ngithub.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).getTarget(0xc001e421b0, {0x37b10a8, 0x4f0c020}, {0x37891e0, 0x4f0c020}, 0xc002338b40, 0xc001049260, {0x7f184e5d5498, 0x4f0c020})\n\t/home/runner/work/pulumi/pulumi/pkg/backend/diy/state.go:128 +0xd1\ngithub.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).newUpdate(, {, }, {, }, , {0xc00226c0b0, {0xc0021f2c40, 0x33}, {0x0, ...}, ...})\n\t/home/runner/work/pulumi/pulumi/pkg/backend/diy/state.go:101 +0xbd\ngithub.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).apply(, {, }, {, }, {, }, {0xc00226c0b0, {0xc0021f2c40, 0x33}, ...}, ...)\n\t/home/runner/work/pulumi/pulumi/pkg/backend/diy/backend.go:1058 +0x2de\ngithub.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({, }, {, }, {, }, {0xc00226c0b0, {0xc0021f2c40, 0x33}, {0x0, ...}, ...}, ...)\n\t/home/runner/work/pulumi/pulumi/pkg/backend/apply.go:272 +0x22d\ngithub.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).Update(, {, }, {, }, {0xc00226c0b0, {0xc0021f2c40, 0x33}, {0x0, 0x0, ...}, ...})\n\t/home/runner/work/pulumi/pulumi/pkg/backend/diy/backend.go:943 +0x1e9\ngithub.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({, }, {, }, {0xc00226c0b0, {0xc0021f2c40, 0x33}, {0x0, 0x0, 0x0}, ...})\n\t/home/runner/work/pulumi/pulumi/pkg/backend/stack.go:96 +0x9e\ngithub.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyStack).Update(, {, }, {0xc00226c0b0, {0xc0021f2c40, 0x33}, {0x0, 0x0, 0x0}, 0xc0021fb1b8, ...})\n\t/home/runner/work/pulumi/pulumi/pkg/backend/diy/stack.go:89 +0x6a\nmain.newUpCmd.func1({, _}, {{{0x4f0c020, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x20, 0x0, ...}, ...}, ...)\n\t/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:187 +0xead\nmain.newUpCmd.func3(0xc001bb7208, {0xc000e296c0, 0x0, 0x0?})\n\t/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:531 +0xc2e\nmain.newUpCmd.runCmdFunc.func4(0x0?, {0xc000e296c0?, 0x0?, 0x0?})\n\t/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/errors.go:31 +0x1c\nmain.newUpCmd.runCmdFunc.RunFunc.func7(0xc001bb7208, {0xc000e296c0, 0x0, 0x7})\n\t/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x3b\ngithub.com/spf13/cobra.(*Command).execute(0xc001bb7208, {0xc000e29650, 0x7, 0x7})\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1\ngithub.com/spf13/cobra.(*Command).ExecuteC(0xc0010b0608)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff\ngithub.com/spf13/cobra.(*Command).Execute(...)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\nmain.main()\n\t/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:55 +0x58\n\n\n\n",
    "stacktrace": "github.com/pulumi/pulumi-kubernetes-operator/pkg/controller/stack.(*ReconcileStack).Reconcile\n\t/home/runner/work/pulumi-kubernetes-operator/pulumi-kubernetes-operator/pkg/controller/stack/stack_controller.go:892\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214"
}
```

### Additional context

This error occurred when using Pulumi operator image pulumi/pulumi-kubernetes-operator:v1.16.0

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
