### ISSUE TITLE
Access auto-generated name in resource arguments

### ISSUE THREAD

**Issue by kwohlfahrt** [pulumi/pulumi#18550]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Pulumi [auto-generates names](https://www.pulumi.com/docs/iac/concepts/resources/names/#autonaming) for resources, if they are not explicitly specified. It would be useful to have access to this auto-generated name when filling in the resource's arguments. I think this issue can be generalized to all Pulumi resources, but my specific use-case is for a kubernetes custom resource (description below).

I have a Kubernetes custom resource, where a field has to match the resources `metadata.name`. This is currently not possible with an auto-named resource.
 
```yaml
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
spec:
  deployment:
    spec:
      template:
        spec:
          volumes:
          - name: grafana-data
            persistentVolumeClaim:
              # The claimName must be named `${metadata.name}-pvc`
              claimName: grafana-pvc  
  persistentVolumeClaim:
    spec:
      accessModes: ["ReadWriteOnce"]
      resources: { requests: { storage: "5Gi" } }
```

I would suggest this can be done in `opts.transformations`, by populating the resource's name before calling the transformation. Currently, `props.metadata.name` is `undefined` in the transformation. But I'm not set on this, perhaps there are better ways to implement this feature.
