### ISSUE TITLE
Alternative to ts-node

### ISSUE THREAD

**Issue by re-thc** [pulumi/pulumi#18574]
**What would you like?**
Use a modern maintained tool e.g. [unjs/jiti](https://github.com/unjs/jiti) or [tsx](https://github.com/privatenumber/tsx) or anything else.

**Why is this needed?**
The last stable release of ts-node was over a year ago (2023): https://github.com/TypeStrong/ts-node/releases/tag/v10.9.2
There seems to be a clear maintenance problem, as can be seen here: https://github.com/TypeStrong/ts-node/issues/2077

There are bugs, possibly breakages from newer Node releases etc, and so Pulumi needs a better alternative.

**Comment by lunaris** [comment]
Hi @re-thc. Thanks for raising this. Our use of `ts-node`, and the risks around it, are definitely on our radar. We've not come around to something satisfactory yet but I'll see if we can reignite discussions around it.

**Comment by Zamiell** [comment]
Hey lunaris,

I would like to recommend `tsx`, as most of the TypeScript ecosystem seems to be moving towards it as a de-facto standard. `tsx` has 10.9K GitHub stars at of the time of this writing, while `ts-node` has 13.1K.

One other benefit of `tsx` is that it handles ESM automatically, so all the annoying ESM instructions located [here](https://www.pulumi.com/docs/iac/languages-sdks/javascript/#native-esm-support) could just be deleted entirely!

**Comment by pjlunardelli** [comment]
This is needed. Is there any workaround?

**Comment by lunaris** [comment]
Hi @pjlunardelli. From what I understand, you may be already able to use e.g. `tsx` using custom runtime options in your `Pulumi.yaml`, e.g.:

```yaml
runtime:
  name: nodejs
  options:
    # Disable built-in TypeScript support
    typescript: false
    # Manually set arguments for the Node interpreter to use a custom loader
    nodeargs: "--import tsx/esm"
```
