### ISSUE TITLE
PluginDownloadURL option doesn't seem to work for git sources

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#18638]
### What happened?

I'm trying to point a provider to my git repo with `pluginDownloadURL`:

```yaml
name: nsg-component-yaml
runtime: yaml
resources:
  azure-nsg:
    type: pulumi:providers:azure-nsg
    defaultProvider: true
    options:
      pluginDownloadURL: git://github.com/mikhailshilkov/pulumi-azure-nsg
  example:
    type: azure-nsg:NetworkSecurityGroup
    properties:
      ...
```

It seems to create a folder `resource-azure-nsg-v0.0.1` in my plugins (note lack of github.com in it) but still fails with

```
Diagnostics:
  pulumi:providers:azure-nsg (azure-nsg):
    error: no resource plugin 'pulumi-resource-github.com_mikhailshilkov_pulumi-azure-nsg.git' found in the workspace or on your $PATH

  pulumi:pulumi:Stack (nsg-component-yaml-dev):
    Downloading provider: azure-nsg
```

while fixing it, let's make sure that the option works on a resource itself:

```yaml
resources:
  example:
    type: azure-nsg:NetworkSecurityGroup
    options:
      pluginDownloadURL: git://github.com/mikhailshilkov/pulumi-azure-nsg
```

### Example

See above

### Output of `pulumi about`

CLI 3.150.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
