### ISSUE TITLE
Error when attempting to use new style components

### ISSUE THREAD

**Issue by automagic** [pulumi/pulumi#18805]
### What happened?

It appears the changes in https://github.com/pulumi/pulumi/pull/18786 have broken the new components behavior somehow:

![Image](https://github.com/user-attachments/assets/be20f096-a26b-43cc-9218-b3f84b31d7ff)

### Example

`pulumi install` 
-or-
`pulumi package add https://github.com/pulumi-initech/pulumi-java-component-acm-dnsvalidatedcertificate@v1.0.0`

sdks/acm/acm-1.0.0.yaml
```
packageDeclarationVersion: 1
name: acm
version: 1.0.0
downloadUrl: git://github.com/pulumi-initech/pulumi-java-component-acm-dnsvalidatedcertificate
```

Pulumi.yaml
```
name: web-components-test
description: Test
runtime: yaml
resources:
  cert:
    type: acm:index:DnsValidatedCertificate
    properties:
      domainName: ${subdomain}.${hostedZoneName}
      zoneName: ${hostedZoneName}
```

`pulumi preview`

### Output of `pulumi about`

3.153.2-alpha (dev release)

### Additional context

Additionally if I run the commands from the error, they work, but install the component in the incorrect place again.

<img width="1572" alt="Image" src="https://github.com/user-attachments/assets/0b588e5d-b575-4c51-be0e-5bcc6633970d" />

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
