### ISSUE TITLE
project config validation: array of objects

### ISSUE THREAD

**Issue by awoimbee** [pulumi/pulumi#18813]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I want to create a schema for my pulumi config. I have arrays of objects in my config.

What I would like:

```yaml
name: mystack
runtime:
  name: nodejs
config:
  mystack:somethingUsername:
    description: mystack something username
    type: string
    default: null
  mystack:somethingPassword:
    description: mystack something password
    type: string
    default: null
  mystack:defaultUsers:
    description: List of default users to create
  mystack:defaultUsers.default.clown:
    type: boolean
    value: false
    description: "Give 'clown' role to all default users"
  # --- where it stops working ---
  mystack:defaultUsers.users:
    type: array
  mystack:defaultUsers.*.email:
    type: string
  mystack:defaultUsers.*.clown:
    type: boolean
```

or 

```yaml
#[...]
  mystack:defaultUsers.users:
    type: array
    items:
      object: 
        email:
          type: string
        clown:
          type: boolean
```

Errors I get: 
 
* `'mystack:defaultUsers.users' declares an array but does not specify the underlying type via the 'items' attribute`
* `defaultUsers.users["*"]: key for an array must be an int` <- I don't remember how, can't reproduce
* `missing configuration value 'mystack:defaultUsers.*.email'`

### Affected area/feature

Project's `config` (https://www.pulumi.com/docs/iac/concepts/projects/project-file/#schemas).

BTW I found no doc for the `mystack:defaultUsers.default.clown:` syntax !

Relates to https://github.com/pulumi/pulumi/issues/16056 https://github.com/pulumi/pulumi/issues/11321
