### ISSUE TITLE
python components: properties of classes not mapped correctly

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi#18846]
Say we have a component such as

```
class SubArgs(TypedDict):
    name: str
    def_ghi: Optional[pulumi.Input[str]]

class MyComponentArgs(TypedDict):
    abc_def: Optional[pulumi.Input[List[SubArgs]]]

class MyComponent(pulumi.ComponentResource):
    def __init__(self, name: str, args: MyComponentArgs, opts: Optional[pulumi.ResourceOptions] = None):
        super().__init__("mycomp:index:MyComponent", name, {}, opts)
        pulumi.log.info(f"{args}")
```

and a yaml program consuming it:

```
name: test-new
runtime: yaml
variables: {}
plugins:
  providers:
    - name: mycomp
      path: ../python-provider
resources:
  my-resource:
    type: mycomp:index:MyComponent
    properties:
      abcDef:
        - name: 'bla'
          defGhi: 'abc'
        - name: 'abc'
```

The properties of the `SubArgs` class don't get mapped back to the `snake_case` version of the property correctly.  The above component logs

```
    {'abc_def': [{'defGhi': 'abc', 'name': 'bla'}, {'name': 'abc'}]}
```

while it should be logging

```
    {'abc_def': [{'def_ghi': 'abc', 'name': 'bla'}, {'name': 'abc'}]}
```
