### ISSUE TITLE
Introduce a `packages` section to Pulumi.yaml

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#18918]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Introduce a new `packages` section to the Pulumi.yaml file to declare dependencies on packages, defining the sources for both binaries and SDK generation. Each item in the packages list mimics the arguments of the `pulumi package add` command.

The section is used for two main scenarios:

- To resolve local provider locations during `pulumi up` etc
- To generate SDKs on `pulumi install` command

Let’s take an example which includes all three 3rd-party scenarios + a parameterized provider:

```
runtime: yaml
packages:
  lbrlabs-eks:
    source: github://api.github.com/lbrlabs
  azure-nsg:
    source: git://github.com/mikhailshilkov/pulumi-azure-nsg
    version: 0.0.1
  planetscale:
    source: terraform-provider
    version: 0.3.0
    arguments: planetscale/planetscale
  cloudrun:
    source: ./local/path
resources:
  mycluster:
    type: lbrlabs-eks:Cluster
  mynsg:
    type: azure-nsg:NetworkSecurityGroup
  mydatabase:
    type: planetscale:Database
  myservice:
    type: cloudrun:Service
```

The CLI should handle them the following way.

`lbrlabs-eks:Cluster`:

- Check if the plugins folder contains a lbrlabs-eks plugin of the latest version (the GitHub plugin source allows resolving latest versions).
- If not, download it from the source to the plugins folder.
- Run the plugin binary to get its schema, register resources, etc.

`azure-nsg:NetworkSecurityGroup`:

- Check if the plugins folder contains a github.com_mikhailshilkov_pulumi-azure-nsg plugin of the version 0.0.1.
- If not, clone the repo to the plugins folder.
- Run the plugin with RunPlugin to get its schema, register resources, etc.

`planetscale:Database`:

- Resolve the parameterized provider’s binary the same way as a “normal” provider (there could be a source defined for it, but in this case the provider is 1st party, so it’s auto-resolved).
- Run the resolved provider with parameterization arguments to generate the sdks file. For starters, we may skip this step and require users to run pulumi install explicitly same as for other SDKs (see the next section)
- Use the sdks files to run the parameterized provider with parameter value.

`cloudrun:Service`:

- Run the plugin with RunPlugin pointing to the folder ./local/path, do not copy it to plugins.

The packages section can be edited manually or by running a `pulumi package add` command.

YAML programs using the current mechanisms will continue to work without changes; the packages approach is additive rather than replacing existing functionality.

In the future, we may want to consider allowing ranges in the version field and lock files to store the concrete installed version.

Additionally, as a short-form syntactic sugar, support this format:

```
runtime: yaml
packages:
  lbrlabs-eks: "github://api.github.com/lbrlabs"
  azure-nsg: "git://github.com/mikhailshilkov/pulumi-azure-nsg@0.0.1"
  planetscale: "terraform-provider@0.3.0 planetscale/planetscale"
  cloudrun: "./local/path"
  ?azure-native: pulumi-azure-native@2.2.0
```

### Affected area/feature

- Pulumi.yaml project format
- YAML runtime
- `pulumi package add`
- `pulumi install`
