### ISSUE TITLE
Preserve comments when converting from Yaml

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi#19031]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Given this Yaml program that has a number of comments:

```yaml
name: generic-yaml
description: An Azure Native Pulumi YAML program demonstrating the generic resource
runtime: yaml
resources:
  resourceGroup:
    type: azure-native:resources:ResourceGroup

  # Create another Storage Account using the generic resource
  generic:
    type: azure-native:resources:Resource
    properties:
      # These properties are required.
      resourceGroupName: ${resourceGroup.name}
      resourceProviderNamespace: Microsoft.Storage
      resourceType: storageAccounts
      apiVersion: "2022-09-01"
      # This property is required even when empty.
      parentResourcePath: ""

      # These properties are optional and are defined because many resources have a kind or a SKU.
      kind: StorageV2
      sku:
        name: Standard_LRS

      # This is a generic property bag for all other properties of the targeted resource.
      properties:
        allowBlobPublicAccess: false%    
```

When converting it to any other language, e.g., `pulumi convert --language go --out ../go/`, the resulting program will not have any of the comments.

```
pulumi version
v3.158.0
```
