### ISSUE TITLE
`pulumi package add ... --save` option

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi#19142]
It would be nifty if we could do something like this:

```bash
pulumi package add terraform-provider hashicorp/random --save
```

And then this gets added to the project config file:

```yaml
packages: # Add if not already added
  random:
    source: terraform-provider
    parameters:
      - hashicorp/random
```

And this gets added to `.gitignore`:

```
sdks/random
```

And then the SDK gets generated/installed.

Note that we will need to update the docs if we implement this feature and https://github.com/pulumi/docs/pull/14692 is merged. Feel free to task me with this update.

I was also thinking about whether `pulumi package freeze` would be worth the effort...
