### ISSUE TITLE
Cannot import gcp.vertex.AiEndpoint: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.

### ISSUE THREAD

**Issue by hnykda** [pulumi/pulumi#19252]
### What happened?

I have an existing VertexAI endpoint and I cannot manage to import it. I tried many variants, none of that work. 

**Description:**
**Verification that resource exists in GCP:**

```bash
$ gcloud ai endpoints describe 1234567890123456789 --region=europe-west4
```

**Output:**
```yaml
createTime: '2024-04-17T15:30:05.689120Z'
deployedModels:
- createTime: '2024-04-17T15:30:05.689120Z'
  dedicatedResources:
    machineSpec:
      acceleratorCount: 4
      acceleratorType: NVIDIA_H100_80GB
      machineType: a3-highgpu-4g
      reservationAffinity:
        reservationAffinityType: NO_RESERVATION
    maxReplicaCount: 1
    minReplicaCount: 1
  displayName: Example Model
  enableAccessLogging: true
  id: '1234567890123456789'
  model: projects/123456789012/locations/europe-west4/models/example-model
  modelVersionId: '1'
  status:
    availableReplicaCount: 1
displayName: example-endpoint-name
etag: ABCdef123XYZ...
labels:
  label-key-1: label-value-1
  label-key-2: label-value-2
  label-key-3: label-value-3
name: projects/123456789012/locations/europe-west4/endpoints/1234567890123456789
trafficSplit:
  '1234567890123456789': 100
updateTime: '2024-04-17T15:59:43.199498Z'
```

but running:

```
pulumi import gcp:vertex/aiEndpoint:AiEndpoint gemma-3 projects/<project-name>/locations/europe-west4/endpoints/example-endpoint-name
```

always yields:
```
Previewing import (main):
     Type                      Name        Plan       Info
     pulumi:pulumi:Stack       infra-main             1 error
 =   └─ gcp:vertex:AiEndpoint  gemma-3     import     2 errors

Diagnostics:
  pulumi:pulumi:Stack (infra-main):
    error: preview failed

  gcp:vertex:AiEndpoint (gemma-3):
    error:   sdk-v2/provider2.go:515: sdk.helper_schema: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.: provider=google-beta@8.14.0
    error: Preview failed: refreshing urn:pulumi:main::infra::gcp:vertex/aiEndpoint:AiEndpoint::gemma-3: 1 error occurred:
    	* Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
```

**Attempted Solutions:**

I tried speccing the definition with e.g.:

```
export const gemma3Endpoint = new gcp.vertex.AiEndpoint("gemma-3", {
  name: "gemma-3-iota",
  displayName: "gemma-3-iota",
  location: "europe-west4",
  region: "europe-west4",
  project: project,
  labels: {
    "mg-one-click-deploy": "publishers-google-models-gemma3",
    "mg-one-click-deploy-task-name": "sglang-128k-context",
    "versioned-mg-one-click-deploy": "publishers-google-models-gemma3-gemma-3-27b-it"
  },
  trafficSplit: JSON.stringify({
    "....": 100
  })
});
``` 

but I get same error. 

### Example

(as per above)

### Output of `pulumi about`

CLI
Version      3.162.0
Go Version   go1.24.2
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.50.1
resource  gcp           8.14.0
language  nodejs        3.162.0

Host
OS       darwin
Version  15.3.2
Arch     arm64
