### ISSUE TITLE
pulumi with a private github package is confused when access is not enabled

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#19325]
### What happened?

1. Create a private github repo with a component provider
2. Create a Pulumi.yaml file

```yaml
name: tmp5
runtime: yaml
packages:
  container-app: github.com/pulumi/my-private-repo/components/container-app@0.1.0
resources:
  app:
    type: container-app:index:ContainerApp
    properties:
      foo: bar
```
3. Without setting a GITHUB_TOKEN env variable, try `pulumi preview`

```
no folder at path '/Users/mikhailshilkov/go/src/github.com/pulumi/play/tmp5/github.com/pulumi/my-private-repo/components/container-app'
```

The error should complain about not being able to access the repo, not about the folder path.

Adding the token `GITHUB_TOKEN=$(gh auth token) pulumi preview` fixes it.

### Example

See above

### Output of `pulumi about`

```
CLI          
Version      3.163.0
Go Version   go1.24.2
Go Compiler  gc

Host     
OS       darwin
Version  15.3.2
Arch     arm64

Current Stack: mikhail-pulumi-corp/tmp5/dev3

Found no resources associated with dev3

Found no pending operations associated with dev3

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/mikhail-pulumi-corp
User           mikhail-pulumi-corp
Organizations  mikhail-pulumi-corp, pulumi
Token type     personal
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
