### ISSUE TITLE
Package version constraints for Pulumi YAML

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi#19350]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I have Pulumi YAML programs and components in a git repository and I want to ensure that they're deployable in the long-term future. I'm concerned that if one of the providers has a new major release, my program will break because it is designed to work with the previous major version. To my knowledge, there's no guarantee of compatibility across major versions.

For example, my program was designed to use azure-native 2.x, and uses a resource that is known to be removed in 3.x.  How can I ensure that my program is deployed with the 2.x provider?

~A known workaround is to define an explicit provider, or to set resource-level options.  Perhaps one could define an alternative default provider with an explicit version.~

Update: another workaround is to set the provider version using the `packages` block, but it doesn't support ranges.

**Comment by tgummerer** [comment]
>  Perhaps one could define an alternative default provider with an explicit version.

I'm confused, you can already do this in a YAML program, described in the docs you linked, setting `defaultProvider: true` on the provider.  Do you mean something else here?

**Comment by EronWright** [comment]
@tgummerer, yes it is similar but insufficient and inconvenient:
1. the documented approach allows the user to specify a specific version like `3.2.0`, but I am seeking a version range like `3.x` (see [package.json](https://docs.npmjs.com/cli/v11/configuring-npm/package-json#dependencies)).
2. a provider with `defaultProvider: true` does not seem to pick up the default provider configuration.

I'm suggesting something that looks more like a "dependency" not a provider declaration. Something that we would feel comfortable adding to the "new program" templates. Hypothetically:

```yaml
name: issue-19350
description: Demonstrates a versioned dependency
runtime: yaml
packages:
  azure-native:
    version: 3.x
resources:
  resourceGroup:
    type: azure-native:resources:ResourceGroup
config:
  azure-native:location: WestUS2
```

I did try the `defaultProvider` option and, for whatever reason, the default provider configuration wasn't picked up.  Here's a repro showing the above limitations:

```yaml
name: issue-19350
description: Demonstrates an alternative default provider with configuration
runtime: yaml
resources:
  azure-native:
    type: pulumi:providers:azure-native
    defaultProvider: true
    options:
      version: 3.2.0  # <--- cannot be a constraint
  # properties:        
  #   location: WestUS2

  resourceGroup:
    type: azure-native:resources:ResourceGroup

outputs:
  location: ${resourceGroup.location}
config:
  azure-native:location: WestUS2        # <--- not effective on the above provider

```

**Comment by iwahbe** [comment]
@EronWright To explain (2): `defaultProvider: true` doesn't make the provider the "default provider", it makes it the provider used by resources. The following program is equivalent to the second example program in https://github.com/pulumi/pulumi/issues/19350#issuecomment-2835801789:

```yaml
name: issue-19350
description: Demonstrates an alternative default provider with configuration
runtime: yaml
resources:
  azure-native:
    type: pulumi:providers:azure-native
    options:
      version: 3.2.0
  resourceGroup:
    type: azure-native:resources:ResourceGroup
    options:
        provider: ${azure-native}

outputs:
  location: ${resourceGroup.location}
config:
  azure-native:location: WestUS2        # <--- not effective on the above provider
```

To pass `location: WestUS2` to the above provider, you would need to set it in the `properties`  field of `pulumi:providers:azure-native`.

**Comment by EronWright** [comment]
Odd to see a bifurcation between "the default provider" in a configuration sense and in a programming model sense. (update: see https://github.com/pulumi/pulumi/issues/2059)

Going back to the high-level goal, it is to stabilize Pulumi YAML programs that are in source control, by declaring the major version of the provider(s) they depend on, e.g. azure-native v2. Similarly, that the program templates be pinned to a major version, as is the case for languages other than YAML.

I think we have confirmed that `defaultProvider: true` is not an effective solution.  Basically I'm advocating for:
```yaml
name: issue-19350
description: versioned dependency
runtime: yaml
packages:
  azure-native:
    version: 3.x
resources:
  resourceGroup:
    type: azure-native:resources:ResourceGroup
```

**Comment by automagic** [comment]
defaultProvider is a very odd option indeed, if its not the default provider (or a replacement thereof), why call it defaultProvider?

**Comment by iwahbe** [comment]
Because it is the provider used by default when no other explicit provider is specified. The pain comes the the fact that Pulumi YAML has a default provider... and the Pulumi Engine has an unrelated concept of a default provider. Unifying these concepts would require https://github.com/pulumi/pulumi/issues/2059.

**Comment by ashish111333** [comment]
hi @iwahbe  can i work on #2059 is it being worked on internally ? i would like to help I think there was already a PR by @tgummerer  Idk why it was closed.

**Comment by Frassle** [comment]
@ashish111333 why are you asking about #20205 on #19350? Did you mean to ask about this issue, or #2059?

**Comment by ashish111333** [comment]
@Frassle  sorry that's a typo, I was  mentioning #2059.

**Comment by Frassle** [comment]
#2059 is likely a very large design and amount of work, feel free to give it some thought but it'll probably need a lot of comments back and forth on the issue to come to a satisfactory design.

**Comment by ashish111333** [comment]
We can discuss on slack, on contribute channel.  I am  on pulumi slack.

**Comment by EronWright** [comment]
To recap, am advocating for a way in Pulumi YAML to pin to a given major version of a provider, to avoid spontaneous breakage when a new major version is released.  Give the user an opportunity to perform migrations.  Also, that we update the Pulumi templates accordingly.

Something like:
```yaml
name: issue-19350
description: versioned dependency
runtime: yaml
packages:
  azure-native:
    version: 3.x
resources:
  resourceGroup:
    type: azure-native:resources:ResourceGroup
```

Important that the solution be applicable to the default providers (those that are configured via stack configuration, e.g. `aws:region: uscentral1`).  Default providers are most important because they're easiest to configure with Pulumi ESC and consequently with Neo.
