### ISSUE TITLE
YAML templates don't support optional configuration

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi#19366]
I have a template that has two configuration values, only one of which can be defined. 

```yaml
name: ${PROJECT}
description: ${DESCRIPTION}
runtime: yaml
template:
  config:
    foo:
      description: only foo or bar can be set.
    bar:
      description: only bar or foo can be set.
  resources:
    my-resource:
      type: blah:blah:blah
      properties:
        foo: ${foo}
        bar: ${bar}
```

^ This does not work. There appears to be no way to configure an optional configuration value (with no default). Even passing an empty string as the default value for the optional configuration does not work. 

I expect to be able to have optional configuration properties with no defaults in my templates.

**Comment by mikhailshilkov** [comment]
It looks like maybe this isn't possible with core YAML. Here is a repro `Pulumi.yaml` that I tried:

```yaml
name: tmp11
runtime: yaml
packages:
  container-app: github.com/pulumi/pulumiup-2025-keynote-demo/components/container-app@0.6.0
config:
  aws:region: us-west-2
  app_port: "8080"
  app_path: ./app
  image:
    description: The Docker image to use. Either this or app_path must be provided, but not both.
  environment: dev
  desired_count: "1"
  cpu: "256"
  memory: "512"
  openai_api_key: bla
resources:
  app:
    type: container-app:index:ContainerApp
    properties:
      appPath: ${app_path}
      image: ${image}
      appPort: ${app_port}
      cpu: ${cpu}
      memory: ${memory}
      env:
        ENVIRONMENT: ${environment}
      desiredCount: ${desired_count}
      secrets:
        OPENAI_API_KEY: ${openai_api_key}
outputs:
  url: ${app.url}
  metricsUrl: ${app.metricsUrl}
```

and then a Pulumi.dev.yaml:

```yaml
config:
  tmp11:image: null
```

We do accept a null here but then we end up sending an empty string over the wire

```
{
  "method": "/pulumirpc.ResourceProvider/Construct",
  "request": {
    "project": "tmp11",
    "stack": "dev",
    "config": {
      "aws:region": "us-west-2",
      "tmp11:app_path": "./app",
      "tmp11:app_port": "8080",
      "tmp11:cpu": "256",
      "tmp11:desired_count": "1",
      "tmp11:environment": "dev",
      "tmp11:image": "",
      "tmp11:memory": "512",
      "tmp11:openai_api_key": "bla"
    },
    "dryRun": true,
    "parallel": 48,
    "monitorEndpoint": "127.0.0.1:53999",
    "type": "container-app:index:ContainerApp",
    "name": "app",
    "parent": "urn:pulumi:dev::tmp11::pulumi:pulumi:Stack::tmp11-dev",
    "inputs": {
      "appPath": "./app",
      "appPort": 8080,
      "cpu": 256,
      "desiredCount": 1,
      "env": {
        "ENVIRONMENT": "dev"
      },
      "image": "",
      "memory": 512,
      "secrets": {
        "OPENAI_API_KEY": "bla"
      }
    },
    "inputDependencies": {
      "appPath": {
        
      },
      "appPort": {
        
      },
      "cpu": {
        
      },
      "desiredCount": {
        
      },
      "env": {
        
      },
      "image": {
        
      },
      "memory": {
        
      },
      "secrets": {
        
      }
    },
    "customTimeouts": {
      
    },
    "acceptsOutputValues": true
  },
  "errors": [
    "rpc error: code = Canceled desc = grpc: the client connection is closing"
  ],
  "metadata": {
    "kind": "resource",
    "mode": "client",
    "name": "container-app"
  }
}
```

**Comment by julienp** [comment]
I might be wrong, but playing around with this and looking at the code, we don't see to have a way to represent a `nil` or `null` value in the config.

In regular YAML,

```yaml
test:
# or equivalent `test: null`
```

is parsed as `map[test:<nil>]`.

However in Pulumi config, an empty value is parsed into an empty string.

When using the following config

```yaml
config:
  yaml-template:prefix:
```

We get a property.Map with an empty string

```
configMap=resource.PropertyMap{"yaml-template:prefix": {}}
// config := resource.FromResourcePropertyMap(configMap)
config=property.NewMap(map[string]property.Value{"yaml-template:prefix":property.New("")})
```

**Comment by julienp** [comment]
I think this is because we define

```go
type Value struct {
	value  string
	secure bool
	object bool
	typ    Type
}

type Map map[Key]Value
```

and use it
```go
type ProjectStack struct {
...
	Config config.Map `json:"config,omitempty" yaml:"config,omitempty"`
}
```

When unmarshalling a config, it will create a map entry for each key in the actual YAML, using an empty `Value`, which ends up being interpreted as a string property with `value = ""`.

**Comment by julienp** [comment]
Aside from the lack of support for real `null`, and forcing the use of empty strings or some other marker value, you can make it work by specifying project level config defaults in the template:

```yaml
name: ${PROJECT}
description: ${DESCRIPTION}
runtime: yaml
config:                      # <- project level config will be copied over to `Pulumi.yaml`
  prefix:
    default: ""
  separator:
    default: ""
template:
  config:
    prefix:
      description: the thing
    separator:
      description: the other thing
resources:
  my-resource:
    type: random:RandomPet
    properties:
      prefix: ${prefix}
      separator: ${separator}
outputs:
  my-resource: ${my-resource.id}
```

Using this as a template will prompt for `prefix` and `separator`. If one or both of the options are left blank during `pulumi new`, they won't be added to the stack level config. When running `pulumi up`, we'll fall back to the project level config with the defaults.

Once we have `null` support, I could also see us providing some form of syntax or operator that lets you for example write `someproperty: ${value?}` (JUST AN EXAMPLE, NOT REAL SYNTAX, DONT YELL AT ME!), where the `?` would indicate that the key `value` might not be set in the config and we're ok with this being `null`.
