### ISSUE TITLE
Policy packs are installed in the system Python path, not in a virtual environment

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi#19568]
### What happened?

When Python policy packs are downloaded & installed locally, since Pulumi v3.170.0 these are now installed in the python path of the system python interpreter, not in a virtual environment how it used to be.

Narrowing it down to the case when `PulumiPolicy.yaml` doesn't contain any `virtualenv` settings.

### Example

Policy pack not containing a `virtualenv` setting:

```yaml
runtime:
  name: python
version: 0.0.2
description: A minimal Policy Pack for AWS using Python.
```

### Output of `pulumi about`

Pulumi v3.170.0

### Additional context

Possible culprit: https://github.com/pulumi/pulumi/pull/19477

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
