### ISSUE TITLE
Installing multiple component plugins from the same monorepo fails

### ISSUE THREAD

**Issue by julienp** [pulumi/pulumi#19630]
If we have a monorepo with a layout:
```
  monorepo/foo
  monorepo/bar
  monorepo/baz
```

and use multiple components from the same version/sha

```
packages:
  foo: github.com/acme/monorepo/foo@123467
  bar: github.com/acme/monorepo/bar@123467
  baz: github.com/acme/monorepo/baz@123467
```

only the package that was installed last seems to work.
