### ISSUE TITLE
Pulumi changes config value when using project level configuration

### ISSUE THREAD

**Issue by 0xd3e** [pulumi/pulumi#19690]
### What happened?

I have a config setting in the project level configuration (`Pulumi.yaml`) where the value is `251985589757358482`.

For some reason, when this value is accessed, it turns into `251985589757358500`.

This doesn't happen if the stack level configuration (`Pulumi.<stack>.yaml`) is used.

### Example

**Pulumi.yaml**

```yaml
name: test
description: A minimal JavaScript Pulumi program
runtime:
  name: nodejs
  options:
    typescript: false
    packagemanager: npm
config:
  test:some-number: "251985589757358482"
  pulumi:tags:
    value:
      pulumi:template: javascript
```

**index.js**

```javascript
"use strict";
const pulumi = require("@pulumi/pulumi");

const config = new pulumi.Config();

console.log(config.require("some-number"));
```

### Output of `pulumi about`

CLI
Version      3.173.0
Go Version   go1.24.3
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  3.173.0

Host
OS       darwin
Version  15.3.2
Arch     x86_64

This project is written in nodejs: executable='/Users/danieltrautmann/.nix-profile/bin/node' version='v20.19.0'

Current Stack: danieltrautmann/test/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/danieltrautmann
User           danieltrautmann
Organizations  danieltrautmann
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.173.0

Pulumi locates its logs in /var/folders/nv/q27l04ws581f8_6z99gkrk4w0000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
