### ISSUE TITLE
[Regression] Reference to a boolean config value is not converted to a bool when used

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi#19695]
### What happened?

Pulumi 3.170.0 introduced a regression, or variation thereof, of https://github.com/pulumi/pulumi-yaml/issues/495

Programs that work with 3.169.0 are now broken due to this regression.

Running the code  below with the given config will throw this error:
```
Diagnostics:
  pulumi:pulumi:Stack (centegix-issue-dev):
    Error: random:index/randomString:RandomString is not assignable from {length: number, special: string}
      on Pulumi.yaml line 14:
      14:       special: ${randomBool}
    Cannot assign '{length: number, special: string}' to 'random:index/randomString:RandomString':
      special: Cannot assign type 'string' to type 'boolean'
```

### Example

Program:
```
runtime: yaml
config:
  randomBool:
    default: false
    type: boolean
resources:
  random:
    type: random:RandomString
    properties:
      length: 4
      special: ${randomBool}
```

Config file:
```
config:
  # Removing the quotes works, 
  # but this shouldn't be necessary since it worked with quotes before 3.170.0.
  randomBool: "true"
```

### Output of `pulumi about`

CLI          
Version      3.171.0
Go Version   go1.24.3
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  random  unknown
language  yaml    1.19.1

Host     
OS       darwin
Version  15.5
Arch     x86_64

This project is written in yaml

Backend        
Name           pulumi.com

Dependencies:
NAME    VERSION
random  

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
