### ISSUE TITLE
New projects have a template section

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#2044]
After creating a project with `pulumi up`, the `template` section is left behind:

```yaml
name: project-cloudysky
runtime: nodejs
description: An awesome Ruby on Rails app in Google Cloud
template:
  description: A minimal Google Cloud TypeScript Pulumi program
  config:
    gcp:project:
      description: The Google Cloud project to deploy into
```

Unless I'm missing something, I don't see any reason to keep this section.
