### ISSUE TITLE
Undefined value in `pulumi.all` confuses preview that there are always changes to apply

### ISSUE THREAD

**Issue by pbzdyl** [pulumi/pulumi#2313]
I have the following use case:

I create a GKE cluster:

```
const cluster = new gke.Cluster('my-cluster', {
    name: 'my-cluster',
    project: 'my-project',
    ....
})
```

Then I create kubeconfig - notice that in order to support both regional and zonal clusters I use either `cluster.zone` or `cluster.regional` [whichever is available](https://www.terraform.io/docs/providers/google/r/container_cluster.html#zone) to construct the k8s context name (I would like to have the function to create kubeconfig yaml in a utility function which might be called with either types of GKE clusters):

```
const k8sConfig = pulumi.
    all([ cluster.project, cluster.name, cluster.endpoint, cluster.masterAuth, cluster.zone, cluster.region ]).
    apply(([ project, name, endpoint, auth, zone, region ]) => {
        const location = zone || region
        const context = `${project}_${location}_${name}`
        return `apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ${auth.clusterCaCertificate}
    server: https://${endpoint}
  name: ${context}
contexts:
- context:
    cluster: ${context}
    user: ${context}
  name: ${context}
current-context: ${context}
kind: Config
preferences: {}
users:
- name: ${context}
  user:
    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
`;
    });
```

And then I used it to construct my k8s provider and create a configmap:

```
const k8sProvider = new k8s.Provider('k8s-cluster', {
    kubeconfig: k8sConfig
})

const appConfig = new k8s.core.v1.ConfigMap('app-config', {
    data: { 'app-config.txt': 'sample contents'}
}, {
    provider: k8sProvider
})
```

The issue is that if one of the inputs is `undefined` (`region` in my scenario) then whenever I run `pulumi preview` there will be a change detected to be applied even though there was no change in my code. When I remove `region` from `all` and `apply` arguments array and use just `zone` the issue disappears.
