### ISSUE TITLE
Should Asset/Archive constructors support Output<T>?

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#3017]
We currently don't support passing `Output<T>`s to `Asset` or `Archive` constructors.

For example, `StringAsset` accepts a `string | Promise<string>`:

https://github.com/pulumi/pulumi/blob/aac25eabc40f5b73664514abfea76c8e155169f4/sdk/nodejs/asset/asset.ts#L72

Is there any reason these constructors don't simply accept `Input<T>`s?

/cc @CyrusNajmabadi in case he knows.

**Comment by CyrusNajmabadi** [comment]
I don't see any particular reason why this wouldn't work.  Perhaps it was at a time when we handled this stuff earlier on in the pipeline and couldn't handle Outputs if we ran into it.

**Comment by bradleybluebean** [comment]
I am trying to add a file containing property values of Pulumi generated Resources to an archive created with `pulumi.AssetArchive()` (using the Python SDK). If I try to create a `pulumi.StringAsset()` with basic assignment like

```
pulumi.StringAsset(f"project_id: {my_gcp_project.project_id}")
```

The file ends up with content like this

```
project_id: <pulumi.output.Output object at 0x7f8760a22f98>
```

Trying to use any sort of `Output` gives a TypeError, as this Issue indicates. Is there any other way to accomplish what I'm trying to do that I'm not seeing or is this just not possible until Assets support passing `Output` types?

**Comment by chrisglass** [comment]
I'm having a similar problem.

I wrote a custom resource (a dynamic provider) to package my lambda code properly (running pip install on their requirements.txt), and struggle to extract the file/folder filename from the resource: I get an Output<str>, but the various asset classes only accept str, as this bug reports documents.

**Comment by boillodmanuel** [comment]
I encounter this issue today and wonder why StringAsset type is not `pulumi.Input<string>`.

In my use case (a training), I want to create a Blob from a secret, and I have to use `apply` to match the expected type.

```
const config = new pulumi.Config()
const secretFileContent = config.requireSecret('secretFileContent')
const secretFile = new storage.Blob('mon-secret.txt', {
    accountName: storageAccount.name,
    resourceGroupName: resourceGroup.name,
    containerName: blobContainer.name,
    blobName: 'mon-secret.txt',
    source: secretFileContent.apply(secret => new pulumi.asset.StringAsset(secret)),
})
```

This works but this is not as pretty as with `Input` 🙂

**Comment by dferretti** [comment]
@boillodmanuel has your example continued to work well for you? I am doing something similar over here using the C# sdk but inconsistently getting some dotnet serialization errors. I have an `Output<string>` that I `Apply` into an AssetArchive with a StringAsset inside it. That goes on an AWS lambda function Code property. Creating the function works fine, but sometimes the next `up` operation fails. Something about expecting an Archive but finding  `System.String`. The state file looks strange too - when it works the `inputs` and `outputs` include a `code` block with the assets listed along with the text value of my function:

```
"code": {
    "4dabf18193072939515e22adb298388d": "0def7320c3a5731c473e5ecbe6d01bc7",
    "assets": {
        "index.js": {
            "4dabf18193072939515e22adb298388d": "c44067f5952c0a294b673a41bacd8c17",
            "hash": "......",
            "text": "'......"
        }
    },
    "hash": "......"
},
```

But when it fails the `outputs` section of the state for this resource looks like 

```
"code": "/tmp/pulumi-asset-049f885f54552ba53ad1a1c8c477c3681be05baf8e6fb7465fc5a2fdf72ffe18"
```

I'm planning on opening a separate issue once I can repeatedly see this behavior, but just wondering if you have had any issues like this in the meantime.

**Comment by boillodmanuel** [comment]
Hi @dferretti,
I didn't use that code anymore so I can tell if this issue is still there, but the github issue is still open..

**Comment by alastairs** [comment]
I have a related problem, where I am trying to create a `StringAsset` to represent the values file of a Helm release. This "file" is generated using `Output.Format()` which obviously returns an `Output<string>`. When I come to convert this to a `StringAsset`, however, I hit one of two issues:

1. When calling `new StringAsset(output)`, it is "CS1503: Cannot convert from 'Pulumi.Output<string>' to 'string'"
2. When calling `output.Apply(vs => new StringAsset(vs))` it is:
    a. CS1503: Cannot convert from 'Pulumi.Output<Pulumi.StringAsset>' to 'Pulumi.Input<AssetOrArchive>'
    b. CS1950: The best overloaded Add method 'InputList<AssetOrArchive>.Add(params Input<AssetOrArchive>[])' for the collection initializer has some invalid arguments

Using this hacky cast appears to please the compiler but I don't have much confidence at the moment that it'll work at runtime...

```csharp
values.Apply(vs => new StringAsset(vs) as AssetOrArchive)
```

The screenshot below illustrates in the isssues in VS.

<img width="895" alt="image" src="https://user-images.githubusercontent.com/52957/187731251-f9440430-4f16-4043-9a76-1c280a2d3345.png">

**Comment by jkodroff** [comment]
This code seems to work:

```yaml
const environmentYaml = oidcRole.arn.apply(arn => new pulumi.asset.StringAsset(`
values:
  aws:
    login:
      fn::open::aws-login:
        oidc:
          duration: 1h
          roleArn: ${arn}
          sessionName: pulumi-environments
          subjectAttributes:
            - currentEnvironment.name
            - pulumi.user.login
  environmentVariables:
    AWS_ACCESS_KEY_ID: \${aws.login.accessKeyId}
    AWS_SECRET_ACCESS_KEY: \${aws.login.secretAccessKey}
    AWS_SESSION_TOKEN: \${aws.login.sessionToken}
`));

new pulumicloud.Environment("aws-oidc-admin", {
  organization: pulumiOrg,
  name: "aws-oidc-admin",
  yaml: environmentYaml
});
```
