### ISSUE TITLE
NonInteractive Warning when Using Cloud Backend

### ISSUE THREAD

**Issue by rawkode** [pulumi/pulumi#3202]
Logging in
```
#### :tropical_drink: `pulumi --non-interactive login gs://xxx/devrel-automation`
Logged into 5e5fbeed9e5a as root (gs://xxx/devrel-automation)
```

Followed by a stack select

```
#### :tropical_drink: `pulumi --non-interactive stack select production`
error: PULUMI_ACCESS_TOKEN must be set for login during non-interactive CLI sessions
##[error]Docker run failed with exit code 255
```

Fails because using `--no-interactive` forces a check for `PULUMI_ACCESS_TOKEN`

**Comment by rawkode** [comment]
Nevermind. This was due to GitHub Actions running a little strangely.

In-case anyone else hits this:

GitHub Actions run as `root`, which the Linux system reports the home directory of `/root`

GitHub Actions scripting overrides `HOME` within each container / step to `/github/home`

So you need to use the Pulumi CI hack/env to get this working correctly:

```yaml
      - name: Login
        uses: docker://pulumi/actions:v1.0.0
        with:
          args: login gs://xxx
        env:
          PULUMI_CREDENTIALS_PATH: /github/home/.pulumi
```
