### ISSUE TITLE
Docker image: running `pulumi up` on Github Actions causes a helm error for a stack that contains a helm chart installation

### ISSUE THREAD

**Issue by standemchuk** [pulumi/pulumi#3773]
Hello Pulumi team!
First of all, thanks for the super nice tooling!

Having an issue while trying to run `pulumi up` during a Github Actions job using `pulumi/pulumi`. Not using `pulumi/actions` since I want to run `pulumi config` before `pulumi up`, but tried on that image as well, still the same error.

The only helm chart in the stack:

```
const nginx = new kubernetes.helm.v2.Chart('nginx',
  {
    namespace:       'default',
    chart:           'nginx-ingress',
    version:         '1.24.4'
  },
  { providers: { kubernetes: cluster.provider } }
)
```

Github Actions job:

```
deploy:
    if: github.event_name == 'push'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '11.x'
      - name: Install Dependencies
        run: cd infra && npm ci
      - uses: docker://pulumi/pulumi
        with:
          args: config set dockerImageId <docker_image_from_build_step> --non-interactive --cwd infra -s <stack_name>
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - uses: docker://pulumi/pulumi
        with:
          args: up --non-interactive --cwd infra -s <stack_name>
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```

Resulting error:
```
error: Error: Command failed: helm fetch nginx-ingress --untar --version 1.24.4 --destination /tmp/tmp-90Vz8G3rY4sxai
    Error: Couldn't load repositories file (/github/home/.helm/repository/repositories.yaml).
    You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
```

Helm repository directory doesn't seem to be correct but I can't find any reference where that directory is set and as far as I can see from the `Dockerfile`. I also tried running `helm init --client-only` explicitly in the `pulumi`'s `Dockerfile`, but the issue still persists.

Let me know if there's anything else you need from and how can I help in resolving this ASAP.

**Comment by lblackstone** [comment]
Pulumi's Kubernetes provider currently shells out to the system to run the `helm` binary, so that's the source of this error message. Helm needs to be initialized before running `pulumi up`. It looks like it's still helm2 installed in the image, so you'll need to run these commands first:

1. `helm init --client-only`
1. `helm repo update`

**Comment by standemchuk** [comment]
Thanks, @lblackstone, this resolved the issue.

For those who will stumble upon something similar, I got it working after adding the following steps to the deployment job:

```yaml
- name: Configure AWS Credentials
  uses: aws-actions/configure-aws-credentials@v1
  with:
    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
- uses: prepor/action-aws-iam-authenticator@master
- name: Run Kubernetes tools
  uses: stefanprodan/kube-tools@v1
  with:
    kubectl: 1.14.9
    helm: 2.14.2
    command: |
      echo "Initializing Helm..."
      helm init --client-only
      echo "Updating Helm repositories..."
      helm repo update
```
