### ISSUE TITLE
Azure secrets provider does not authenticate using Client credentials

### ISSUE THREAD

**Issue by rlekni** [pulumi/pulumi#4072]
I've been setting up pulumi to use azure keyvault.

Prior to this I had my CI (on azure devops) build something like this:
```yaml
- script: |
    export PATH=$PATH:$HOME/.pulumi/bin
    pulumi login --cloud-url azblob://pulumi-state
    pulumi stack select test
    pulumi preview --diff
  displayName: run pulumi
  workingDirectory: src
  failOnStderr: true
  continueOnError: false
  env:
    ARM_CLIENT_ID: $(client_id)
    ARM_CLIENT_SECRET: $(client_secret)
    ARM_TENANT_ID: $(tenant_id)
    ARM_SUBSCRIPTION_ID: $(subscriptionId)
    AZURE_STORAGE_ACCOUNT: $(storage_account)
    AZURE_STORAGE_KEY: $(storage_account_key)
    PULUMI_CONFIG_PASSPHRASE: $(pulumi_config_passphrase)
```

I decided to move away from using passphrase, and use --secrets-provider. Created a stack fine, using the secrets provider, used my own user on azure to do that (just local commands).

However, now when I was trying to select the stack on the CI just using service principal authentication, pipeline is not able to authenticate against keyvault.

The error I'm getting is this `error: getting secrets manager: secrets (code=InvalidArgument): azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://somekeyvault.vault.azure.net/keys/keyname/someid/decrypt?api-version=7.0: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
`
That's without changing the above pipeline.

I've resolved the issue by authenticating with az cli as well as just passing sp credentials to pulumi.
```yaml
- script: |
    az login --service-principal -u $(client_id) -p $(client_secret) --tenant $(tenant_id)
    export PATH=$PATH:$HOME/.pulumi/bin
    pulumi login --cloud-url azblob://pulumi-state
    pulumi stack select test
    pulumi preview --diff
  displayName: run pulumi
  workingDirectory: src
  failOnStderr: true
  continueOnError: false
  env:
    ARM_CLIENT_ID: $(client_id)
    ARM_CLIENT_SECRET: $(client_secret)
    ARM_TENANT_ID: $(tenant_id)
    ARM_SUBSCRIPTION_ID: $(subscriptionId)
    AZURE_STORAGE_ACCOUNT: $(storage_account)
    AZURE_STORAGE_KEY: $(storage_account_key)
    AZURE_KEYVAULT_AUTH_VIA_CLI: true
```

The [documentation](https://www.pulumi.com/docs/intro/concepts/config/#azure-key-vault) specifies that it should use Azure Environment authentication, which in my case should just use Client credentials just like what pulumi is using, however that is not the case.

**Comment by Figglewatts** [comment]
Stumbled upon this while Googling for a separate issue - but have you tried using:
```yaml
AZURE_CLIENT_ID: $(client_id)
AZURE_CLIENT_SECRET: $(client_secret)
AZURE_TENANT_ID: $(tenant_id)
```
I.e. replace `ARM_` with `AZURE_`.
See [this link](https://docs.microsoft.com/en-us/azure/developer/go/azure-sdk-authorization#use-environment-based-authentication) for more details.

**Comment by nickpainter** [comment]
@Figglewatts  - Thanks for this bit.  I encountered the same problem and your post saved me a ton of troubleshooting :)  

I added the 3 `AZURE` variables in addition to the existing `ARM` ones.

**Comment by fraPace** [comment]
Hello @stack72 ,
I see that you assigned yourself on this issue.
Any updates on it? I am currently facing the problem of using the SP on a Azure pipeline.
On my local environment I have tried to add the `AZURE_` variables but then I get the usual message that I should not use the Azure CLI for SPs.
Have you identify the issue? I believe someone the tool (or Terraform) is looking at System Managed Identities to perform the login.

**Comment by Figglewatts** [comment]
@fraPace Defining the `AZURE_` environment variables should work fine in Azure Pipelines.

On your local environment you should make sure the environment variable `AZURE_KEYVAULT_AUTH_VIA_CLI` is set to `true` if you wish to authenticate to the key vault via the Azure CLI (after an `az login`), as in [the documentation](https://www.pulumi.com/docs/intro/concepts/config/#azure-key-vault). If you wish to use a service principal to authenticate then make sure `AZURE_KEYVAULT_AUTH_VIA_CLI` is set to `false`, and you have the `AZURE_` environment variables.

The setup I normally use is `AZURE_KEYVAULT_AUTH_VIA_CLI` for working on a stack on my local machine, and in a CI/CD environment I use the `AZURE_` environment variables.

**Comment by fraPace** [comment]
Hello @Figglewatts,
Unfortunately it does not work. I am using Pulumi 2.4.0 for Linux distros.

By digging in the code I have found that:
1.  Python uses a Go library to create CloudSecretsManagers (line 71 of https://github.com/pulumi/pulumi/blob/v2.4.0/pkg/secrets/cloud/manager.go)
2.  Such library uses a function that is called Dial to authenticate (https://godoc.org/gocloud.dev/secrets/azurekeyvault#Dial)
3.  The Dial function relies on the Go Azure environment variables like you correctly reported (https://docs.microsoft.com/en-us/go/azure/azure-sdk-go-authorization#use-environment-based-authentication)
4. Pulumi throws the following error when using such variables:
`error: Error building AzureAD Client: Authenticating using the Azure CLI is only supported as a User (not a Service Principal).
    To authenticate to Azure using a Service Principal, you can use the separate 'Authenticate using a Service Principal'
    auth method - instructions for which can be found here:
    Alternatively you can authenticate using the Azure CLI by using a User Account.`

After reading the Dial and the Azure documentation I understand why Pulumi was trying to get access to the System Managed Identity: if one authentication method cannot be used (lack of env variables), the move to the next. The last one is the Managed Identity, after that the Dial thrown an error.

Not sure how you setup your Azure Pipeline, but we find (as a company) very impractical to use a Service Connector and then have to specify the env variables in the pipeline itself. Since we want to build IaC and delegate roles permission, we would like to avoid (or at least try) to give SP credentials to a very high number of people (we have more than 5k devs).

The right approach should be that, since Pulumi knows that I am using a SP and since it has a way to pass such auth, it handles the creation (and destruction) of the env variables that are needed by the libraries that the Pulumi project uses.

We (as a company) could fork this project and create a version that works for us, but that is not our spirit. We want to help the community.

**Comment by WackPenguin** [comment]
While its not ideal, if azure pipelines are used, you can use Service connection to authenticate and set environment variables.
Something like this (on ubuntu agents):

```yaml
- task: AzureCLI@2
            displayName: run pulumi
            enabled: true
            continueOnError: false
            inputs:
              azureSubscription: devtest
              addSpnToEnvironment: true
              workingDirectory: src
              scriptType: bash
              scriptLocation: inlineScript
              failOnStderr: true
              inlineScript: |
                export ARM_CLIENT_ID=$servicePrincipalId
                export ARM_CLIENT_SECRET=$servicePrincipalKey
                export ARM_TENANT_ID=$tenantId
                export ARM_SUBSCRIPTION_ID=$(az account show | jq '.id' --raw-output)

                pulumi login --cloud-url azblob://pulumi-state
            env:
              AZURE_STORAGE_ACCOUNT: $(storage_account)
              AZURE_STORAGE_KEY: $(storage_account_key)
              AZURE_KEYVAULT_AUTH_VIA_CLI: true
```
Environment variable still needs to be set, if you want to use blob storage, even if you have CLIENT_ID etc set.
```yaml
AZURE_KEYVAULT_AUTH_VIA_CLI: true
```
It's an odd problem because even if you authenticate with CLI, to be able to use Keyvault, you still need to set SP credentials as environment variables for pulumi to be able to login to your azure stack.

**Comment by Figglewatts** [comment]
@fraPace I experienced the exact same error as you (in your 4th point) when I was setting up Pulumi where I work. I believe the issue was that I was specifying Service Principal credentials (via `AZURE_`/`ARM_` environment variables) in addition to `AZURE_KEYVAULT_AUTH_VIA_CLI`.

Setting `AZURE_KEYVAULT_AUTH_VIA_CLI` to `true` switches the authentication method used, as can be seen in the code here at the calling point: https://github.com/google/go-cloud/blob/master/secrets/azurekeyvault/akv.go#L96-L106
And here where the auth is actually performed, in the 'Dial' function you mentioned: https://github.com/google/go-cloud/blob/master/secrets/azurekeyvault/akv.go#L176-L207

Digging deeper into the auth library that go-cloud uses, you can see that if `AZURE_KEYVAULT_AUTH_VIA_CLI` is set, then it will use [`NewAuthorizerFromCLIWithResource`](https://github.com/Azure/go-autorest/blob/master/autorest/azure/auth/auth.go#L280), and if it is not set, it will use the [Microsoft environment authentication flow](https://docs.microsoft.com/en-us/azure/developer/go/azure-sdk-authorization#use-environment-based-authentication) with [`NewAuthoriserFromEnvironmentWithResource`](https://github.com/Azure/go-autorest/blob/master/autorest/azure/auth/auth.go#L78).

For developers working on their local machines, we provide a command for them to authenticate with the Azure-hosted Pulumi backend that works roughly like this:
```
export AZURE_KEYVAULT_AUTH_VIA_CLI="true"
export AZURE_STORAGE_ACCOUNT="{storage-acct-name}"
export AZURE_STORAGE_KEY=$(az storage account keys list \
                --account-name {storage-acct-name} \
                --subscription "{subscription}" \
                --resource-group {rg} \
                --query "[0].value" -o tsv)
export PULUMI_SECRET_KEY="azurekeyvault://{kv-name}.vault.azure.net/keys/pulumi"
echo "Populated AZURE_STORAGE_ACCOUNT, AZURE_STORAGE_KEY and PULUMI_SECRET_KEY"
pulumi login azblob://{container-name}
```

And for our CI/CD builds, we have set up service connections for each of our subscriptions, and we use them in Pipelines as a step template like so:
```yaml
parameters:
  PulumiVersion: "2.4.0"
  PulumiStorageAccountName: "{snip}"
  PulumiStorageAccountResourceGroup: "{snip}"
  PulumiStorageAccountSubscription: "{snip}"
  ContainerName: "{snip}"
  AzureSubscription: ""

steps:
  - bash: |
      if ! which pulumi; then
        curl -fsSL https://get.pulumi.com | sh -s -- --version ${{ parameters.PulumiVersion }}
        echo "##vso[task.prependpath]/home/vsts/.pulumi/bin"
      fi
    displayName: Install Pulumi ${{ parameters.PulumiVersion }} if not already installed
  - task: "AzureCLI@2"
    inputs:
      azureSubscription: "${{ parameters.AzureSubscription }}"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      addSpnToEnvironment: true
      inlineScript: |
        AZURE_STORAGE_ACCOUNT="${{ parameters.PulumiStorageAccountName }}"
        AZURE_STORAGE_KEY=$(az storage account keys list \
          --account-name "${{ parameters.PulumiStorageAccountName }}" \
          --resource-group "${{ parameters.PulumiStorageAccountResourceGroup }}" \
          --subscription "${{ parameters.PulumiStorageAccountSubscription }}" \
          --query "[0].value" | tr -d \")
        ARM_SUBSCRIPTION_ID=$(az account show --query 'id' --output tsv)
        echo "##vso[task.setvariable variable=AZURE_STORAGE_ACCOUNT]${AZURE_STORAGE_ACCOUNT}"
        echo "##vso[task.setvariable variable=AZURE_STORAGE_KEY]${AZURE_STORAGE_KEY}"
        echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]${ARM_SUBSCRIPTION_ID}"
        echo "##vso[task.setvariable variable=AZURE_CLIENT_ID]${servicePrincipalId}"
        echo "##vso[task.setvariable variable=AZURE_CLIENT_SECRET]${servicePrincipalKey}"
        echo "##vso[task.setvariable variable=AZURE_TENANT_ID]${$tenantId}"
    displayName: "Get credentials for Pulumi storage account and key vault"
  - bash: pulumi login --cloud-url azblob://${{ parameters.ContainerName }}
    displayName: Log in to Pulumi
```

This is very similar to the approach described by @WackPenguin, however we don't use `AZURE_KEYVAULT_AUTH_VIA_CLI` in the pipeline, it works with just the SP creds.

It's not ideal to expose the credentials to the entire pipeline like this, but as far as I'm aware there isn't a better way. I don't believe you can use managed identity authentication in a build agent unless you host your own on a VM, and this isn't convenient for us.

Nevertheless, we're successfully using this approach to manage 10 or so AKS clusters and a whole host of other Azure/AWS cloud resources across multiple dev teams, all with Pulumi.

**Comment by fraPace** [comment]
Hello @WackPenguin,

Thank you for the reply.
This is what I just did from my own environment (it is no different from the pipeline environment since I use an self-hosted agent with the same image).
I have run the following:
`export ARM_CLIENT_ID="******"
export ARM_CLIENT_SECRET="****"
export ARM_SUBSCRIPTION_ID="****"
export ARM_TENANT_ID="******"

export AZURE_STORAGE_ACCOUNT="*****"
export AZURE_STORAGE_KEY="****"

export AZURE_KEYVAULT_AUTH_VIA_CLI=true

pulumi login -c azblob://*****
pulumi stack select dev
pulumi preview`

I get the following error: `error: getting secrets manager: open keeper azurekeyvault://*****: failed to Dial default KeyVault: Invoking Azure CLI failed with the following error: Please run 'az login' to setup account.`

So my next actions is to add the following (according to the documentation of the Go secretManager that Pulumi is using):
`export AZURE_TENANT_ID="****"
export AZURE_CLIENT_ID="*****"
export AZURE_CLIENT_SECRET="****"`

The `pulumi preview` commands still return the same error: `error: getting secrets manager: open keeper azurekeyvault://***: failed to Dial default KeyVault: Invoking Azure CLI failed with the following error: Please run 'az login' to setup account.`

Therefore my last action is:
`export AZURE_KEYVAULT_AUTH_VIA_CLI=false`

**In this case `pulumi preview` is working!**

However, I would like to reiterate on the fact that it should not up to the final user to set up environment variables with redundant informations just because Pulumi is using Terraform on one side and some Go libraries on the other. The Pulumi Azure task is correctly set the `ARM_` variables taking them from the Service Connector. However, Pulumi should standardize the way login is performed to use the different functionalities that it provides. So a quick fix should be to get the SP credentials and set (and unset) the environment variables.

@Figglewatts Thank you. I think for the moment we will do the same, but as I already stated above, I do not think it is the right approach. "Fixing" this issue should be pretty straightforward. Sadly I am not use to Go, otherwise I would do a PR immediately.

**Comment by Figglewatts** [comment]
@fraPace I think to some extent it's always up to the end user. Having had experience with both Pulumi and Terraform, there's always at least some amount of juggling environment variables/tfvars files.

The redundant environment variables are actually from Terraform - the [Azure](https://www.terraform.io/docs/providers/azurerm/guides/service_principal_client_secret.html#configuring-the-service-principal-in-terraform) and [Azure AD](https://www.terraform.io/docs/providers/azuread/guides/service_principal_client_secret.html#configuring-the-service-principal-in-terraform) providers use the `ARM_` variables, whereas the go-cloud library uses the `AZURE_` variables.

**Comment by fraPace** [comment]
@Figglewatts I might be wrong her, but is Terraform using the go-cloud libraries or Pulumi? From the code that I scanned it looked like Pulumi. So to me it looks like Pulumi is using both and the login systems are different. Should be this left to the end user? Not sure I fully agree with you. I do agree on the fact that we should provide the credentials in different ways (cli, env, etc). Is providing the same credentials twice becoming the new standard of software development?

**Comment by Figglewatts** [comment]
@fraPace As far as I'm aware, the Terraform provider uses the Azure REST API to interact with Azure (so not go-cloud), and Pulumi uses go-cloud. I totally agree with you that it's a bit cumbersome to have to supply the same credentials twice.

As Pulumi simply calls into go-cloud without any specific behaviour for different kinds of secret managers (https://github.com/pulumi/pulumi/blob/v2.4.0/pkg/secrets/cloud/manager.go#L71), it would probably be better to fix this behaviour with a PR in go-cloud allowing it to also use `ARM_` environment variables for authentication to key vault.

**Comment by fraPace** [comment]
@Figglewatts 
I think that we should PR on Pulumi. Pulumi is using the go library not the way around.

**Comment by mastoj** [comment]
I've been trying basically everything above, but I still can't get it to work with keyvault on Azure Devops. Some background on the setup, since the are some policies in place so I don't have access with the service accounts everywhere.

I have three service principal accounts, one for dev, test and prod. The state and keyvault are located in my prod environment in under my prod subscription. The only way for me to access the cloud storage is to get the keys to the storage using the production service provider.

I have a small script, `set-pulumi-storage-env` that I use to get the storage account information:

```
KEYS=$(az storage account keys list --account-name elkdspulumistate --resource-group pulumi-state --output json)

export AZURE_STORAGE_ACCOUNT="elkdspulumistate"
export AZURE_STORAGE_KEY=$(echo $KEYS | jq -r ".[0].value")
export AZURE_KEYVAULT_AUTH_VIA_CLI=false
```

So far so good. For key vault access I struggle a bit more. The relevant part of the steps in my `azure-pipelines.yml` looks like this:

```
        deploy: 
          steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: Setup pulumi
            inputs:
              scriptType: bash
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              azureSubscription: "ITOP.Prod.ARM"
              # targetType: inline
              inlineScript: |
                chmod 777 -R ./scripts/*

                curl -fsSL https://get.pulumi.com | bash
                export PATH=$PATH:$HOME/.pulumi/bin
                echo "##vso[task.setvariable variable=path]$PATH"

                source ./scripts/set-pulumi-storage-env.sh
                echo "##vso[task.setvariable variable=azure_storage_account]$AZURE_STORAGE_ACCOUNT"
                echo "##vso[task.setvariable variable=azure_storage_key]$AZURE_STORAGE_KEY"
                echo "##vso[task.setvariable variable=azure_keyvault_auth_via_cli]$AZURE_KEYVAULT_AUTH_VIA_CLI"

                ARM_SUBSCRIPTION_ID=$(az account show | jq '.id' --raw-output)
                echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]${ARM_SUBSCRIPTION_ID}"
                echo "##vso[task.setvariable variable=ARM_CLIENT_ID]${servicePrincipalId}"
                echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]${servicePrincipalKey}"
                echo "##vso[task.setvariable variable=ARM_TENANT_ID]${tenantId}"
                
                echo "##vso[task.setvariable variable=AZURE_SUBSCRIPTION_ID]${ARM_SUBSCRIPTION_ID}"
                echo "##vso[task.setvariable variable=AZURE_CLIENT_ID]${servicePrincipalId}"
                echo "##vso[task.setvariable variable=AZURE_CLIENT_SECRET]${servicePrincipalKey}"
                echo "##vso[task.setvariable variable=AZURE_TENANT_ID]${tenantId}"
                
                pulumi plugin install resource azure-nextgen v0.2.3-alpha.1602700498+177a671e

          - task: AzureCli@2
            displayName: Deploy ${{ parameters.environment }}
            inputs:
              scriptType: bash
              scriptLocation: inlineScript
              azureSubscription: ${{ parameters.serviceConnectionName }}
              # ${{ parameters.serviceConnectionName }}
              inlineScript: |
                STACK=${{ parameters.environment }} make deploy-infra
```

The last line is what calls `pulumi up`. So the idea is this, first I have one task where I always use my production service provider , that will fetch the relevant storage bucket information using the script above. The there is  a second task that use the environment specific one to run `pulumi up`. The service connection in the second step is sort of secondary since I also have them in my `Pulumi.<stack>.yaml` file. In the deploy step I do print the env variables and can see that everything is set, but for some reason I get: 

> error: getting secrets manager: passphrase must be set with PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE environment variables

Why do I get that? I have set all the relevant env variables as I see it, but it still asks for the passphrase. Can someone spot anything obvious wrong?

**Comment by rlekni** [comment]
@mastoj What does your `Pulumi.<stack>.yaml` look like?

For example mine with keyvault configured has these 2 lines:
```
secretsprovider: azurekeyvault://somekeyvault.vault.azure.net/keys/test-key/7c2ce4e4ef374ce7b66t7e09626b0077
encryptedkey: <excluded>
```

Also have you tried just simply exporting the variables? instead of echo `"##vso[task.setvariable variable=ARM_CLIENT_ID]${servicePrincipalId}"` doing this export `ARM_CLIENT_ID=$servicePrincipalId`

This is what I use for testing purposes which works:
```yaml
stages:
  - stage: cibuild
    displayName: CI Build
    dependsOn: []
    variables:
      - group: deployment
    jobs:
      - job: cibuild
        displayName: ci build
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              curl -fsSL https://get.pulumi.com | sh
              export PATH=$HOME/.pulumi/bin:$PATH
              echo "##vso[task.setvariable variable=PATH;]$HOME/.pulumi/bin:$PATH"
              pulumi version
            displayName: install pulumi
          - task: NodeTool@0
            displayName: install node
            inputs:
              versionSpec: ">=14"
              checkLatest: true
          - script: |
              npm install
            workingDirectory: src
            displayName: install npm dependencies
          - task: AzureCLI@2
            displayName: run pulumi
            enabled: true
            continueOnError: false
            inputs:
              azureSubscription: planner-core-contributor
              addSpnToEnvironment: true
              workingDirectory: src
              scriptType: bash
              scriptLocation: inlineScript
              failOnStderr: true
              inlineScript: |
                export ARM_CLIENT_ID=$servicePrincipalId
                export ARM_CLIENT_SECRET=$servicePrincipalKey
                export ARM_TENANT_ID=$tenantId
                export ARM_SUBSCRIPTION_ID=$(az account show | jq '.id' --raw-output)

                pulumi login --cloud-url azblob://pulumi-state
                pulumi stack ls

                pulumi stack select container-registry

                pulumi up --diff --show-config --yes

                # pulumi destroy
            env:
              AZURE_STORAGE_ACCOUNT: $(storage_account)
              AZURE_STORAGE_KEY: $(storage_account_key)
              AZURE_KEYVAULT_AUTH_VIA_CLI: true
```
