### ISSUE TITLE
Support for Solution file in .NET Core

### ISSUE THREAD

**Issue by Rookian** [pulumi/pulumi#4185]
I have one csproj file within one Visual Studio solution. 

When I run `pulumi up` I get the following error:

>  MSBUILD : error MSB1050: Specify which project or solution file to use because the folder "." contains more than one project or solution file.

Please make it possible to explicitly pass in the correct csproj file via pulumi console or pulumi stack configuration or determine the csproj file automatically and pass it to msbuild.

**Comment by mikhailshilkov** [comment]
This should work if you add a `main` entry to your `Pulumi.yaml` file, e.g.

```yaml
name: azure-cs
runtime: dotnet
main: Infra.csproj
description: A minimal Azure C# Pulumi program
```
