### ISSUE TITLE
ManagedCertificate (networking.gke.io) custom resource

### ISSUE THREAD

**Issue by roee-hershko** [pulumi/pulumi#4230]
Hey so i am trying to add certificate to GCP load balancer trough GKE, to do so i need to create "ManagedCertificate" resource:
```
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: domain-staging
  namespace: nostro
spec:
  domains:
    - api-staging.domain.com
```

currently i am doing it as follow:
```
new k8s.yaml.ConfigFile("networking.gke.io/v1beta2", {
        file: './kubernetes/certificate.yml'
    }, {provider})
```
i did some digging and havnt found this resource supported by pulumi/k8s package,
is it really not supported? and if so is it possible to add custom resource as JS and not YML?

**Comment by lblackstone** [comment]
You're looking for the `apiextension.CustomResource` class.

https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/kubernetes/apiextensions/#CustomResource

Here's an example from one of our tests: https://github.com/pulumi/pulumi-kubernetes/blob/f1fab0e738b573f6b327de7e120fa9da5767967b/tests/integration/crds/step1/index.ts#L38-L49

**Comment by logston** [comment]
Is there support coming for `CustomResource`s in golang? 

I need to create ... 

```
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
 name: myredirect
spec:
 redirectToHttps:
   enabled: true
   responseCodeName: PERMANENT_REDIRECT
```

and 

```
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: mycert
spec:
  domains:
  - mydomain.com
```
