### ISSUE TITLE
Node.js policy packs cannot disable the built-in TypeScript support

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#4830]
Pulumi programs can disable the built-in TypeScript support with the following runtime setting in `Pulumi.yaml`:

```yaml
runtime:
  name: nodejs
  options:
    typescript: false
```

This isn't currently supported for policy packs -- currently, the built-in TypeScript support will always be used.

https://github.com/pulumi/pulumi/blob/2513709089ca20ceb95ed910c7396534baae3fc9/sdk/nodejs/cmd/run-policy-pack/index.ts#L112
