### ISSUE TITLE
"Error building AzureRM Client" on Azure Devops

### ISSUE THREAD

**Issue by mastoj** [pulumi/pulumi#4840]
Trying to deploy some azure servicebus things with the devops pipeline I've configured. I have configured a service principal and configured the `pulumi.dev.yaml` like such:

```
config:
  azure:clientId: XXXXXXX
  azure:clientSecret:
    secure: SECURESTRING
  azure:subscriptionId: GUIDAGAIN
  azure:tenantId: YYYY
```

The stage description that fails look like this:

```
- stage: DeployDev
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - deployment: DeployToDev
    displayName: Deploy Dev
    # creates an environment if it doesn't exist
    environment: 'sweetspot-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: Bash@3
            displayName: Setup pulumi
            inputs:
              targetType: inline
              script: |
                curl -fsSL https://get.pulumi.com | bash
                export PATH=$PATH:$HOME/.pulumi/bin
                echo "##vso[task.setvariable variable=path]$PATH"
                pulumi login
                curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            env:
              PULUMI_ACCESS_TOKEN: $(pulumi.access.token)            
          - task: Bash@3
            displayName: Deploy dev
            inputs:
              targetType: inline
              script: 
                make deploy
```

When running on Azure Devops I get the following error:

> error: Error building AzureRM Client: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed and then log-in with `az login`.
 
The `make deploy` executes a F# fake script that sets the stack and call `pulumi up -y`. The pulumi code I have deploy a kubernetes app and now also some servicebus stuff. It did work fine when I deployed only the kubernetes stuff, but I guess that is because I don't need to run the az cli tool for that. What might I be doing wrong?
