### ISSUE TITLE
CLI Compile hook

### ISSUE THREAD

**Issue by JakeGinnivan** [pulumi/pulumi#4862]
We are using TypeScript project references in a few projects we would like to introduce Pulumi into. ts-node doesn't work nicely with TypeScript project references so the simplest way I can see to move forward is to disable inbuilt TypeScript support then build the Pulumi program myself.

Something in Pulumi.yaml would be handy (or a well known script name in package.json would work). Something like this would be great

```
runtime:
  name: nodejs
  options:
    compile: yarn tsc -b
    typescript: false
```
