### ISSUE TITLE
Add support for Kubernetes provider in GitHub Actions

### ISSUE THREAD

**Issue by RobbieMcKinstry** [pulumi/pulumi#4969]
The current behavior of the Pulumi [GitHub Action](https://www.pulumi.com/docs/guides/continuous-delivery/github-actions/) does not permit use of the Kubernetes provider. Because the Action is executed inside of a Docker container, the host's `kubeconfig` file is not forwarded to the volume. There are no flags or options on the Action to permit this. Copying the `.kube/config` file is insufficient, as for certain providers like `DigitalOcean`, the config is fetched using `doctl` or other external commands no available on the Docker container.

**Comment by jaxxstorm** [comment]
Hi @RobbieMcKinstry 

We have quite a few users using the GitHub action with the Kubernetes provider, so this is a supported option. The general way this is done is by setting the provider inside the Pulumi program itself, you can see an example of this [here](https://github.com/pulumi/examples/blob/506cf5b8d45a5a9058a17f936e249270c0138f36/digitalocean-ts-k8s/index.ts#L29-L36)

Another option is to grab the kubeconfig as a step in the workflow, then use [set-env](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable) to set the resulting output to `KUBECONFIG` which can then be consumed by the action container. Something like this:


```
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: get kubeconfig
         run: echo ::set-env name=KUBECONFIG::$(doctl kubernetes cluster kubeconfig show)
      - uses: docker://pulumi/actions
        with:
          args: preview
        env:
          KUBECONFIG: ${{ env.KUBECONFIG }}
``` 

Do neither of these suit your use case?
