### ISSUE TITLE
Unable to output a value with a single backslash

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#5076]
When trying to output a string with a single backslash, `pulumi` seems to apply its own escaping to outputs and is turning `\` into `\\`.

I've tested this across TypeScript, CSharp, and Python and get the same results.

#### Code
```ts
import * as pulumi from "@pulumi/pulumi";

const region = "us-west-2";
const bucket = "foo-bar";

export let x = `\\\\${region}\\${bucket}`;
console.log(`X: ${x}`);

export let y = pulumi.interpolate`\\\\${region}\\${bucket}`;
y.apply(y => console.log(`Y: ${y}`));

export let z = "\\\\" + region + "\\" + bucket;
console.log(`Z: ${z}`);
```

#### Output
```
Diagnostics:
  pulumi:pulumi:Stack (interp-dev):
    X: \\us-west-2\foo-bar
    Z: \\us-west-2\foo-bar
    Y: \\us-west-2\foo-bar
Outputs:
    x: "\\\\us-west-2\\foo-bar"
    y: "\\\\us-west-2\\foo-bar"
    z: "\\\\us-west-2\\foo-bar"
```
