### ISSUE TITLE
Support top-level `await` in Node.js

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#5161]
Support for top-level await was just made available by default in Node `v14.8.0` (https://github.com/nodejs/node/pull/34558).  We should enable this to be used in Pulumi programs, and look into what we need to do in terms of Node versions, flags for older Node versions, TypeScript versions, TypeScript compilation targets, and module system configuration to be able to (a) allow users to use top-level await (b) make this the default mode for new projects and update existing examples to take advantage of this where possible.

**Comment by keithharvey** [comment]
Any progress on this? Starting to port my company onto Pulumi and the combination of 2.0 forcing Promise<Type> returns and the crosswalk files being out of date creates friction.

**Comment by suonto** [comment]
Has there been any progress in this?

**Comment by thanhtoan1196** [comment]
any updates?

**Comment by lukehoban** [comment]
This is now supported for JavaScript and pre-compiled TypeScript programs via support for ESM added in https://github.com/pulumi/pulumi/pull/7764.  Some details on how to use this in https://github.com/pulumi/pulumi/issues/4130#issuecomment-1002868483.

Additional support for features that enable this to be used via on-the-fly-compiled TypeScript programs (the most common use case in Pulumi) is coming in https://github.com/pulumi/pulumi/pull/8655.

**Comment by awoimbee** [comment]
This is now supported for on the fly compiled typescript.

How to:
- update all your imports (https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#file-esm-package-md)
- Add to `package.json`:
  ```json
  {
      # ...
      "type": "module",
      "dependencies": {
          "ts-node": "^10.4.0",
          # ...
      }
  }
  ```
- Add to `tsconfig.json`:
  ```json
      "target": "ESNext",
      "module": "ESNext",
  ```
- Add to `pulumi.yaml`:
  ```yaml
  runtime:
    name: nodejs
    options:
      # See https://github.com/TypeStrong/ts-node/issues/1007
      nodeargs: "--loader ts-node/esm --no-warnings"
  ```

**Comment by lukehoban** [comment]
Per @awoimbee's comment above, this is now as fully supported as it can currently be in Pulumi JS/TS.   It is not yet available directly in the default Pulumi templates, and https://github.com/pulumi/templates/issues/244 is tracking that.  But given the dependence on experimental Node.js loader features, switching to using this by default will likely be something that is still a ways further off.  In the meantime, it is easy for users to follow the approach in https://github.com/pulumi/pulumi/issues/5161#issuecomment-1010018506 to start using ESM and top-level await today!

**Comment by zvictor** [comment]
There is a working (and tested!) example of **Top-level `await` in TS and Pulumi** at https://github.com/pulumi/pulumi/tree/6bc7b1cc67621e515c44d9dde99ab8deba4d1c08/tests/integration/nodejs/esm-ts !

If you are having issues to make your setup work, try to compare with that code 👆 instead of spending as many hours as I have spent on debugging and googling this 😆

**Comment by zb-sj** [comment]
for those coming across `ERR_UNSUPPORTED_DIR_IMPORT` error with imports should add `--experimental-specifier-resolution=node` to `nodeargs` like:

```yml
# Pulumi.yaml
runtime: 
  name: nodejs
  options:
    # See https://github.com/TypeStrong/ts-node/issues/1007
    nodeargs: "--loader ts-node/esm --no-warnings --experimental-specifier-resolution=node"
```
