### ISSUE TITLE
Allow non dynamic output

### ISSUE THREAD

**Issue by GaboFDC** [pulumi/pulumi#5173]
This is more a feature request.

When you run pulumi command on the console, it prints some dynamic output showing what resource is being checked, but this output is overwritten dynamically, so the final output is much clearer.

But when you do this coman on non traditional shells, or environments, like in github actions, this dynamic output is all kept, which makes the output very verbose an unclear.

We could have a cli arg to avoid this dynamic output, so it will be much more clear when running on those said environments.

**Comment by nstires-ctgx** [comment]
Experiencing same issue...in both GitHub Actions and CircleCI, it should be registering as non-interactive.

```
jobs:
  myjob:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Update Pulumi
        run: |
          curl -fsSL https://get.pulumi.com | sh
          sudo mv /home/runner/.pulumi/bin/* /usr/local/bin/
```
