### ISSUE TITLE
Creating a new stack should prompt for for templated config

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi#5343]
Today, when creating a new project based on a template, the CLI prompts you interactively for whatever `config` properties are specified in the template:

```
name: some-base-project
...
template:
    config:
        aws:region:
            description: The AWS region to deploy into.
            default: us-west-2
        some_prop:
            description: Some configurable thing.
            default: some-val
            ...
```

```
$ pulumi new ../some-base-project
...
project name: (some-base-project) some-copy
stack name: (dev)
aws:region: The AWS region to deploy into.: (us-west-2)
some_prop: Some configurable thing (some-val)
...
```

This is a nice experience for creating a new project, but since the feature is presumably intended to make it easier to bootstrap an initial stack, it's odd that it doesn't apply to successive stacks:

```
$ pulumi stack init another-stack
Created stack 'another-stack' # 😢
```

To some extent, something like `--copy-config-from dev` could make creating `another-stack` a little easier, but given that the creation of a new stack likely entails having to provide differing configuration for it, one would still be left having to run `pulumi config set` to change the config values once they'd been copied from the `dev` stack. Basically, this feels like an unbalanced/asymmentrical experience.

Instead, it'd be nice to have the CLI prompt you interactively when creating successive stacks, just as it does when creating the first. It doesn't look like we currently copy the source template when a new project is created from one, so we'd need to do that as well to make this work, but since `pulumi stack init` without any arguments already prompts for user input, it should be okay to extend that same behavior to prompt for additional config when it's declared in `Pulumi.yaml`.
