### ISSUE TITLE
dotnet binary option via pulumi cli

### ISSUE THREAD

**Issue by gitfool** [pulumi/pulumi#5522]
Following up from #5334...
Currently, the `binary` option can only be controlled via `Pulumi.yaml`:
```yml
name: aws
runtime:
  name: dotnet
  options:
    binary: Aws.dll
description: AWS infrastructure
config: ..
```
I want to use source during development (on Windows) but use binaries during deployment (on Linux, in a container), so it would be useful to have a **binary option in the pulumi cli** as well.
