### ISSUE TITLE
In Pulumi GitHub Action, if COMMENT_ON_PR is set, jq fails if OUTPUT_FILE is too many lines

### ISSUE THREAD

**Issue by catmeme** [pulumi/pulumi#5781]
When `COMMENT_ON_PR` PR is set, if the body of the output from the job is too long (in my case 4743 lines were generated from a docker build), jq will fail as shown below:

```
/usr/bin/pulumi-action: line 152: /usr/bin/jq: Argument list too long
```

Example step:

```
      - uses: docker://pulumi/actions
        with:
          args: preview
        env:
          COMMENT_ON_PR: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: pr
          PULUMI_SKIP_UPDATE_CHECK: true
```

Related code:

https://github.com/pulumi/pulumi/blob/2b435bb1a7dcb9d8678933cb734374c4821192bd/docker/actions/entrypoint.sh#L150-L154

Test case demonstrating bug:

```
COMMENT=$(seq 1 1000000); echo '{}' | jq --arg body "$COMMENT" '.body = $body'
```

Work-around is to not set `COMMENT_ON_PR`.
