### ISSUE TITLE
Missing plugin in Github Action CI pipeline

### ISSUE THREAD

**Issue by simonlevy5** [pulumi/pulumi#6256]
Our Github action for running `pulumi preview` started failing with the following Diagnostic output:
```
Diagnostics:
  pulumi:providers:aws (default_3_26_1):
    error: no resource plugin 'aws-v3.26.1' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource aws v3.26.1`
```

This works locally for some of our developers but does not for others. (more detail below)

## Expected Behavior

The pipeline should install pulumi and run `pulumi preview` with no errors

## Current Behavior

Pipeline fails with the diagnostic:
```
Diagnostics:
  pulumi:providers:aws (default_3_26_1):
    error: no resource plugin 'aws-v3.26.1' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource aws v3.26.1`
```

## Steps to Reproduce
1. Run our CI pipeline which uses the Pulumi Github Action (`pulumi/actions@v1`) with the command `preview`. Pipeline code below:
```
name: Preview
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - uses: pulumi/actions@v1
        with:
          command: preview
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          IS_PR_WORKFLOW: true
          PULUMI_ROOT: deploy/legacy

```

For the developer where `pulumi preview` runs locally without issue running `pulumi plugin ls` produces:
```
aws         resource  3.26.1                            260 MB  3 days ago   3 days ago
aws         resource  3.25.1                            259 MB  1 week ago   1 week ago
aws         resource  3.24.0                            259 MB  2 weeks ago  2 weeks ago
aws         resource  3.23.0                            259 MB  3 weeks ago  3 weeks ago
aws         resource  3.21.0                            253 MB  1 month ago  1 month ago
aws         resource  3.20.0-alpha.1607556814+e40d2a9c  253 MB  1 month ago  1 month ago
aws         resource  3.20.0-alpha.1607454742+261742f4  253 MB  1 month ago  1 month ago
docker      resource  2.6.1                             43 MB   2 weeks ago  2 weeks ago
docker      resource  2.5.0                             43 MB   1 month ago  1 month ago
docker      resource  2.3.0                             45 MB   1 month ago  1 month ago
okta        resource  2.7.1                             45 MB   2 weeks ago  2 weeks ago
postgresql  resource  2.5.3                             41 MB   2 weeks ago  2 weeks ago
postgresql  resource  2.5.2                             41 MB   4 weeks ago  4 weeks ago
random      resource  3.0.1                             31 MB   2 weeks ago  2 weeks ago
random      resource  3.0.0                             31 MB   1 month ago  1 month ago
tls         resource  3.0.0                             31 MB   4 weeks ago  4 weeks ago
```

They are using brew installed version of pulumi `2.20.0`.

For the developer who can reproduce this locally, running `pulumi plugin ls` produces:
```
aws resource 3.25.1 259 MB 2 hours ago 2 hours ago
aws resource 3.21.0 253 MB 4 weeks ago 4 weeks ago
random resource 3.0.1 31 MB 2 hours ago 2 hours ago
```

The project contains the following dependencies:
```
        "@pulumi/aws": "^3.25.1",
        "@pulumi/awsx": "^0.24.0",
        "@pulumi/okta": "^2.7.1",
        "@pulumi/postgresql": "^2.5.2",
        "@pulumi/pulumi": "^2.17.2",
        "@pulumi/random": "^3.0.0",
        "@pulumi/tls": "^3.0.0",
```

The project running in the pipeline uses a stackReference.

## Context (Environment)

Our CI can't run pulumi

A suggested solution is to add the command to our pipeline:
`pulumi plugin install resource aws v3.26.1`

This would only affect one pipeline
