### ISSUE TITLE
Slow performance for Helm chart

### ISSUE THREAD

**Issue by ppawiggers** [pulumi/pulumi#6301]
I deploy a Helm chart with Pulumi:

```
chart = Chart(
    "kube-prometheus-stack",
    config=ChartOpts(
        chart="kube-prometheus-stack",
        version="13.4.1",
        fetch_opts=FetchOpts(
            repo="https://prometheus-community.github.io/helm-charts",
        ),
    ),
)
```

This wants to create ~120 resources and the initial deployment takes about 320 seconds to complete (the Docker images are already cached on the nodes).

The helmfile equivalent:

```
repositories:
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: kube-prometheus-stack
    namespace: prometheus
    chart: prometheus/kube-prometheus-stack
    version: 13.4.1
    disableValidation: true
```

takes just 40 seconds to complete.

A `destroy` with Pulumi takes even longer: ~500 seconds. With helmfile it's just 7 seconds.

I want to use Pulumi to deploy multiple Helm charts, but with this difference in speed I tend to use helmfile for the Kubernetes resources (and Pulumi just for the setup of the Kubernetes cluster itself).

Why can it be so slow?
