### ISSUE TITLE
Automation API saves config lists/maps as json strings, breaking `pulumi config get --path` commands

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi#6352]
Consider this `Pulumi.dev.yaml`:
```yaml
config:
  aws:region: us-west-2
  nested_config:bar: 1234
  nested_config:foo: aha
  nested_config:myList:
    - one
    - two
    - three
  nested_config:outer:
    inner:
      secure: AAABADOd8UPayqGlunla+Lo6kSSYA4LffCNBe84ElLwv0kyz7oIcYAw=
    other: something_else
```

You can do `pulumi config get —path outer.other` -> `something_else`
Or `pulumi config get --path "myList[0]"` -> `one`

If we use automation api to GetAllConfig and SetAllConfig the resulting ConfigMap, this is the resulting `Pulumi.dev.yaml`:
```yaml
config:
  aws:region: us-west-2
  nested_config:bar: "1234"
  nested_config:foo: aha
  nested_config:myList: '["one","two","three"]'
  nested_config:outer:
    secure: AAABAHho23grF7o/iYIX/8k1gNMDWQ15CxxnbfOXSSzQPwqWWVG0srJxal12syY7o5wvn4x4U3ky81nsF2z/NGIOvz3Ovq8ThJn60zzc
```

Now, the same commands as earlier fail:
`pulumi config get —-path outer.other` -> `error: configuration key 'outer.other' not found for stack 'dev'`
Or `pulumi config get --path "myList[0]"` -> `error: configuration key 'myList[0]' not found for stack 'dev'`

## Expected behavior

I should be able to use the CLI command `pulumi config get --path [nested-path]` on a config list/map item written by automation API.

## Current behavior

This throws an error. `pulumi config get —-path [nested-path]` -> `error: configuration key [nested-path] not found for stack [stack]`
