### ISSUE TITLE
Support yaml anchors in config

### ISSUE THREAD

**Issue by GaboFDC** [pulumi/pulumi#6480]
## Pulumi config support for yaml anchors
Right now, you can manually, edit the config file, and use yaml anchors, i.e:

```yml
config:
  aws:region: us-east-1
  proj:data:
    default: &default
      active: true
    foo:
      <<: *default
    bar:
      <<: *default
    biz:
      active: false
```

If you read this config, it works fine:

```py
import pulumi
import pulumi_aws as aws

pulumi_config = pulumi.Config("proj")
conf = pulumi_config.require_object("data")
print(conf)
```

```bash
$ pulumi config get proj:data
{"bar":{"active":true},"biz":{"active":false},"default":{"active":true},"foo":{"active":true}}
```
So far so good, but if you use the cli commands to save a new config:

```bash
$ pulumi config set proj:new test
```

the saved config will be interpreted:

```yaml
config:
  aws:region: us-east-1
  proj:data:
    bar:
      active: true
    biz:
      active: false
    default:
      active: true
    foo:
      active: true
  proj:new: test
```

So the config, in theory, is the same, but you lose the anchors. 
You can avoid this by adding new configs manually in the file. But if you need to add a secret there is no way to avoid it as far as I know.

Would be nice to be able to seamlessly use anchors in this config, this helps keep the config reusable and nonrepetitive (DRY)
