### ISSUE TITLE
Can't import a Lambda Function

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#6491]
I cannot successfully import a Lambda Function.  Moreover, I'm not even told what properties it tried to use for the import that led to the error message.

```
➜  importtests pulumi import aws:lambda/function:Function myfunc arn:aws:lambda:us-west-2:616138583583:function:kube2pulumi-convert-handler-daa9934 --diff
Previewing import (dev)

View Live: https://app.pulumi.com/lukehoban/importtests/dev/previews/d22d63cb-e08e-447f-8487-97ef1ffec029

  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::importtests::pulumi:pulumi:Stack::importtests-dev]
    bucketName: "my-bucket-0c61599"
error: Preview failed: diffing urn:pulumi:dev::importtests::aws:lambda/function:Function::myfunc: handler and runtime must be set when PackageType is Zip
error: preview failed
Resources:
    2 unchanged
```

Notably - both `handler` and `runtime` are set in the output from  `aws lambda get-function --function-name kube2pulumi-convert-handler-daa9934` is:

```yaml
- Code:
    Location: https://awslambda-us-west-2-tasks.s3.us-west-2.amazonaws.com/<redacted>
    RepositoryType: S3
  Configuration:
    CodeSha256: q6Aww6bEW+2SGc9xHNvyyU8GxsbwGqGAGpxOB0mJgOo=
    CodeSize: 15771329
    Description: ''
    FunctionArn: arn:aws:lambda:us-west-2:616138583583:function:kube2pulumi-convert-handler-daa9934
    FunctionName: kube2pulumi-convert-handler-daa9934
    Handler: handler
    LastModified: 2020-08-11T23:43:33.077+0000
    LastUpdateStatus: Successful
    MemorySize: 1024
    RevisionId: 3ddb0686-6bb6-4d3a-acdb-ef72c4bd71f6
    Role: arn:aws:iam::616138583583:role/tfpulumi-convert-handler-role-913ee0f
    Runtime: go1.x
    State: Inactive
    StateReason: The function is currently idle.
    StateReasonCode: Idle
    Timeout: 300
    TracingConfig:
      Mode: PassThrough
    Version: $LATEST
    VpcConfig:
      SecurityGroupIds:
      - sg-0cf94170e9406a763
      SubnetIds:
      - subnet-0db2ba2c77ef6a4ae
      - subnet-078f7827478cabf51
      VpcId: vpc-0409c192d0aaa7407
  Tags:
    Owner: '616138583583'
```
