### ISSUE TITLE
[NodeJS] Add "all" variable to Config that acts like "outputs" in StackReference & RemoteStateReference

### ISSUE THREAD

**Issue by awoimbee** [pulumi/pulumi#6789]
This is a proposal to implement something like:
```typescript
export declare class Config {
    readonly all: Output<{
        [name: string]: any;
    }>;
    // (...)
}
```

## Affected feature

`pulumi.Config`

## Problem

Reading a `Config` object is kind of a mess, especially when config keys start being nested.
There are 8 `getThing` and 8 `requireThing` methods, none of them work well with nested objects !

```
get
getSecret
getBoolean
getSecretBoolean
getNumber
getSecretNumber
getObject
getSecretObject
require
requireSecret
requireBooleanis:open 
requireSecretBoolean
requireNumber
requireSecretNumber
requireObject
requireSecretObject
```

Most of these are made to select a value in a flat structure and become useless when configuration values are nested.
Consider:
```yaml
config:
  my-stack:project-0:
    container-repository:
      tag: my-tag
      use_special_repo: true
  my-stack:project-1:
    container-repository:
      tag: my-other-tag
      use_special_repo: false
    env-vars:
      TOTO: yes
      PASSWORD:
        secure: <encrypted_password>
```

The only methods I can use are: `getSecretObject`, `getObject`, `requireObject`, `requireSecretObject`.
And the resulting code is sub-optimal:
```typescript
const containerTag = cfg.requireObject<any>("project-0")["container-repository"]["tag"] as string;
const password = cfg.requireSecretObject<any>("project-1").apply(p => p["env-vars"]["PASSWORD"]) as Output<string>;
```

## Solution

- One solution is to make all the `getWathever()` and `requireWhatever()` methods work well with paths.
- The other solution is the one I'm proposing now:

With this proposal I could use:
```typescript
const containerTag = cfg.all.apply(all => all["project-0"]["container-repository"]["tag"] as string);
const password = cfg.all.apply(all => all["project-1"]["env-vars"]["PASSWORD"] as string);
```
It is then down to the user to check the type / validity of the values, just like with `StackReference.outputs` and `RemoteStateReference.outputs`.
