### ISSUE TITLE
Pulumi automation can not handle objectValue in Config

### ISSUE THREAD

**Issue by ncd** [pulumi/pulumi#6809]
I made pulumi config as an object.
```yaml
ram:
    roles:
    - assume_policy: autoscaler_assume
      name: cluster-autoscaler
      policy_attachments:
        custom_policies:
        - cluster_autoscaler
```
When I run stack refresh/up using pulumi.x.automation module --> I always failed due to an error: unexpected keyword argument 'objectValue'.
Recheck with pulumi stack history command:
```
"devops-ram:ram": {
        "value": "{\"roles\":[{\"assume_policy\":\"autoscaler_assume\",\"name\":\"cluster-autoscaler\",\"policy_attachments\":{\"custom_policies\":[\"cluster_autoscaler\"]}}]}",
        "objectValue": {
          "roles": [
            {
              "assume_policy": "autoscaler_assume",
              "name": "cluster-autoscaler",
              "policy_attachments": {
                "custom_policies": [
                  "cluster_autoscaler"
                ]
              }
            }
          ]
        },
        "secret": false
      }
    }
```

## Expected behavior

The code will run normally

## Current behavior

The code has error

## Steps to reproduce

1. Run pulumi automation with configuration is in object type.
