### ISSUE TITLE
[dotnet/sdk] Serilog logging should set `SourceContext`

### ISSUE THREAD

**Issue by gitfool** [pulumi/pulumi#7093]
I'm using `config.Development.yml` to configure Serilog logging in a generic host:
```yaml
Serilog:
  MinimumLevel:
    Override:
      Microsoft: Information
      Microsoft.Hosting.Lifetime: Warning
  WriteTo:
    - Name: Seq
      Args:
        serverUrl: http://localhost:5341
```
But I can't control the dotnet automation api logging since it doesn't generate a source context:

![image](https://user-images.githubusercontent.com/750121/118939928-4e0a3900-b9a4-11eb-93cd-65118391b02c.png)

This should be a matter of using `ILogger<T>` instead of `ILogger` where type `T` becomes the source context, like the following:
```c#
public sealed partial class DeployCommand : AsyncCommandBase<DeployCommand.Settings>
{
    public DeployCommand(IOptions<Config> options, ILogger<DeployCommand> logger, IServiceProvider serviceProvider)
        : base(options, logger) { }

    protected override async Task<int> OnExecuteAsync(CommandContext context, Settings settings)
    {
        Logger.LogInformation("Deploying resources...");
        using var totalTimeLogger = new ElapsedTimeLogger(Logger, "Deployed resources");
        ...
    }
}

public abstract class AsyncCommandBase<TSettings> : AsyncCommand<TSettings> where TSettings : CommandSettings
{
    protected AsyncCommandBase(IOptions<Config> options, ILogger logger)
    {
        Config = options.Value;
        Logger = logger;
    }

    protected Config Config { get; }
    protected ILogger Logger { get; }
}
```
