### ISSUE TITLE
Missing required property 'value' error from requireSecretObject

### ISSUE THREAD

**Issue by austinbutler** [pulumi/pulumi#7113]
I have a config like this:

```yaml
config:
  my-stack:my_secrets:
    secret_a:
    - password:
        secure: v1:yadayada
      username: user1
    - password:
        secure: v1:yadayada
      username: user2
```

And I access it via:
```typescript
const my_secrets =
  config.requireSecretObject<{
    [secret_name: string]: { username: string; password: string }[];
  }>("my_secrets");
```

This results in: `Error: Missing required property 'value'`.

## Expected behavior

I can use that structured config with `requireSecretObject`.

## Current behavior

It seems `requireSecretObject` doesn't understand the config.

## Steps to reproduce

Add the config to your stack, run `pulumi up`.

## Context (Environment)

Prior to Pulumi 3.3.0 I was just using `requireObject` without issue, but 3.3.0 started warning about secrets not being accessed via `requireSecretObject` so I figured I should use that.

**Comment by austinbutler** [comment]
In the same project the following config is loaded by `requireSecretObject` just fine:

```yaml
config:
  my-stack:more_secrets:
    non_secret: non_secret_value
    secret_value:
      secure: v1:blahblah
```
