### ISSUE TITLE
.NET CodeGen started emitting InvokeArgs for a Resource input object?

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#7207]
When I upgraded my code generation to pulumi/pulumi@v3.3.1, I started seeing incorrect .NET code generation being introduced.

The following diff appeared - which doesn't compile:

```patch
diff --git a/sdk/dotnet/Inputs/SwaggerGatewayResponseArgs.cs b/sdk/dotnet/Inputs/SwaggerGatewayResponseArgs.cs
index d7a1f71..25b34c0 100644
--- a/sdk/dotnet/Inputs/SwaggerGatewayResponseArgs.cs
+++ b/sdk/dotnet/Inputs/SwaggerGatewayResponseArgs.cs
@@ -10,28 +10,28 @@ using Pulumi.Serialization;
 namespace Pulumi.Apigateway.Inputs
 {
 
-    public sealed class SwaggerGatewayResponseArgs : Pulumi.ResourceArgs
+    public sealed class SwaggerGatewayResponse : Pulumi.InvokeArgs
     {
         [Input("responseParameters")]
-        private InputMap<string>? _responseParameters;
-        public InputMap<string> ResponseParameters
+        private Dictionary<string, string>? _responseParameters;
+        public Dictionary<string, string> ResponseParameters
         {
-            get => _responseParameters ?? (_responseParameters = new InputMap<string>());
+            get => _responseParameters ?? (_responseParameters = new Dictionary<string, string>());
             set => _responseParameters = value;
         }
 
         [Input("responseTemplates")]
-        private InputMap<string>? _responseTemplates;
-        public InputMap<string> ResponseTemplates
+        private Dictionary<string, string>? _responseTemplates;
+        public Dictionary<string, string> ResponseTemplates
         {
-            get => _responseTemplates ?? (_responseTemplates = new InputMap<string>());
+            get => _responseTemplates ?? (_responseTemplates = new Dictionary<string, string>());
             set => _responseTemplates = value;
         }
 
         [Input("statusCode")]
-        public Input<double>? StatusCode { get; set; }
+        public double? StatusCode { get; set; }
 
-        public SwaggerGatewayResponseArgs()
+        public SwaggerGatewayResponse()
         {
         }
     }
diff --git a/sdk/dotnet/Pulumi.Apigateway.csproj b/sdk/dotnet/Pulumi.Apigateway.csproj
index cd65fd9..2112d2b 100644
--- a/sdk/dotnet/Pulumi.Apigateway.csproj
+++ b/sdk/dotnet/Pulumi.Apigateway.csproj
@@ -25,6 +25,10 @@
     <PublishRepositoryUrl>true</PublishRepositoryUrl>
   </PropertyGroup>
 
+  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
+    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
+  </PropertyGroup>
+
   <ItemGroup>
     <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />
   </ItemGroup>
diff --git a/sdk/dotnet/RestAPI.cs b/sdk/dotnet/RestAPI.cs
index d490a17..4f69144 100644
--- a/sdk/dotnet/RestAPI.cs
+++ b/sdk/dotnet/RestAPI.cs
@@ -78,15 +78,15 @@ namespace Pulumi.Apigateway
         public Pulumi.Apigateway.APIKeySource? ApiKeySource { get; set; }
 
         [Input("gatewayResponses")]
-        private ImmutableDictionary<string, Inputs.SwaggerGatewayResponseArgs>? _gatewayResponses;
+        private ImmutableDictionary<string, Inputs.SwaggerGatewayResponse>? _gatewayResponses;
 
         /// <summary>
         /// Define custom gateway responses for the API. This can be used to properly enable
         /// CORS for Lambda Authorizers.
         /// </summary>
-        public ImmutableDictionary<string, Inputs.SwaggerGatewayResponseArgs> GatewayResponses
+        public ImmutableDictionary<string, Inputs.SwaggerGatewayResponse> GatewayResponses
         {
-            get => _gatewayResponses ?? (_gatewayResponses = new ImmutableDictionary<string, Inputs.SwaggerGatewayResponseArgs>());
+            get => _gatewayResponses ?? (_gatewayResponses = new ImmutableDictionary<string, Inputs.SwaggerGatewayResponse>());
             set => _gatewayResponses = value;
         }
 
```

Strangely - all other object types still seem to work fine - I cannot tell what is different about this one that it got turned into an InvokeArgs (even though my schema defines no functions).  The segment of the schema for this is:

```yaml
      gatewayResponses:
        type: object
        additionalProperties:
          "$ref": "#/types/apigateway:index:SwaggerGatewayResponse"
        description: |
          Define custom gateway responses for the API. This can be used to properly enable
          CORS for Lambda Authorizers.
```

and 

```yaml
  apigateway:index:SwaggerGatewayResponse:
    type: object
    properties:
      statusCode:
        type: number
      responseTemplates:
        type: object
        additionalProperties:
          type: string
      responseParameters:
        type: object
        additionalProperties:
          type: string
```

The only thing that is "different" is that this type is the `additionalProperties` type for an object type. 

As well as being apparently wrong, the generated code doesn't compile - I get:

```
RestAPI.cs(89,66): error CS1729: 'ImmutableDictionary<string, SwaggerGatewayResponse>' does not contain a constructor that takes 0 arguments [/Users/lukehoban/go/src/github.com/pulumi/pulumi-apigateway-ts/sdk/dotnet/Pulumi.Apigateway.csproj]
```
