### ISSUE TITLE
Be able to configure CLI flags on a permanent basis

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi#7403]
It would be very helpful sometimes to be able to set Pulumi CLI flags on a permanent basis instead of keep passing them via CLI. For example, in my company we use Pulumi extensively and we have a lot of outputs, but we don't want to see them all the time, only when we really want to. To accomplish this we run `pulumi up --suppress-outputs`, but having to do this all the time is cumbersome.

I propose that we use Pulumi.yaml to store those flags, so that we don't need to keep passing them. For example:
```
runtime:
  name: python
flags:
  - up:suppress-outputs
  - emoji
  - up:suppress-permalink
```
Or:
```
runtime:
  name: python
flags:
  global:
    - emoji
  up:
    - suppress-outputs
    - suppress-permalink
```

**Comment by lukehoban** [comment]
Definitely an interesting idea.  Curious if you know of any precedent for this in other CLI tools where this is done well?

**Comment by Sodki** [comment]
The one that comes to mind is Ansible: https://docs.ansible.com/ansible/latest/installation_guide/intro_configuration.html

There is a huge amount of configurations available and all of them can be configured via configuration files or environment variables. A subset of these is available via CLI.

**Comment by 1oglop1** [comment]
Moving in my 2 cents from #8193 

### Problem
As a developer, I often need to run `pulumi preview` or `pulumi up` and other commands. Many of these commands have different flags which makes it difficult to remember and makes writing these commands over and over very tedious and long.
Also, different developers may have different preferences.

### Example
When the code contains a lot of outputs that I'm not interested in during the development I can use the flag `--suppress-outputs` 
because they clutter Pulumi CLI output. 
Then I have to call every command with its unique flags
`pulumi up --suppress-outputs`, `pulumi preview --suppress-outputs`, etc...


### Proposal
There should be a way to set these flags permanently globally for the project as well as per the developer's preference.

For project global configuration these values could live in `Pulumi.yaml`
Where the schema could be like a so:
```yaml
cli:
   pulumi_subcommand:
     - list of flag objects
     - pure-flag
     - flag_with_multiple_values: value
```

e.g. for command `pulumi preview --suppress-outputs`
```yaml
cli:
  preview:
    - suppress-outputs
```

Then these settings can be overridden either via ENV variable/s or similar approach `docker-compose` has with `Pulumi-override.yaml` to avoid serialisation and deserialisation problems of parsing strings from ENV.
