### ISSUE TITLE
Go codegen doesn't handle hyphenated package names

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#8181]
When I use this in `schema.json` for a package named `aws-apigateway`:

```yaml
  go:
    importBasePath: github.com/lukehoban/pulumi-package-aws-apigateway/sdk/go/apigateway
```

I end up with `go/apigateway/restAPI.go` with package `aws`.

If I use this:

```yaml
  go:
    importBasePath: github.com/lukehoban/pulumi-package-aws-apigateway/sdk/go/apigateway
    rootPackageName: apigateway
```

I end up with `go/restAPI.go` with package `apigateway`.

But neither of these seems to be "right" - I want (and kind of assume I should get by default) `go/apigateway/restAPI.go` with package `apigateway`.

It feels like we should make one or both of these changes:
1. The default package name should not be `strings.Split(name, "-")[0]` but perhaps `strings.ReplaceAll(name, "-", "")`
2. If `importBasePath` is specified, the last part of the path (`apigateway` in the examples above) should be used as the package name, instead of "guessing" it from the `strings.Split(name, "-")[0]` logic.  Or at least, that logic should apply to the final part of the user-provided import base path.
