### ISSUE TITLE
Pulumi CLI configuration via file or ENV vars

### ISSUE THREAD

**Issue by 1oglop1** [pulumi/pulumi#8193]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

### Problem
As a developer, I often need to run `pulumi preview` or `pulumi up` and other commands. Many of these commands have different flags which makes it difficult to remember and makes writing these commands over and over very tedious and long.
Also, different developers may have different preferences.

### Example
When the code contains a lot of outputs that I'm not interested in during the development I can use the flag `--suppress-outputs` 
because they clutter Pulumi CLI output. 
Then I have to call every command with its unique flags
`pulumi up --suppress-outputs`, `pulumi preview --suppress-outputs`, etc...

### Proposal
There should be a way to set these flags permanently globally for the project as well as per the developer's preference.

For project global configuration these values could live in `Pulumi.yaml`
Where the schema could be like a so:
```yaml
cli:
   pulumi_subcommand:
     - list of flag objects
     - pure-flag
     - flag_with_multiple_values: value
```

e.g. for command `pulumi preview --suppress-outputs`
```yaml
cli:
  preview:
    - suppress-outputs
```

Then these settings can be overridden either via ENV variable/s or similar approach `docker-compose` has with `Pulumi-override.yaml` to avoid serialisation and deserialisation problems of parsing strings from ENV.

### Affected area/feature
Pulumi CLI
