### ISSUE TITLE
Provide a way to merge yaml subsets into configs prior to execution

### ISSUE THREAD

**Issue by atrauzzi** [pulumi/pulumi#8372]
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I'm working through setting up multiple projects within a single C# solution.  Each project corresponds _roughly_ to one repository or microservice in my application architecture, _with two exceptions_: Core infra and ingress/load balancing/application gateway-ing.

Each project leverages a common configuration schema for some conventions that they all need to be able to rely on having.

So, let's say I have a `Pulumi.dev.yaml` inside of a `Project.yaml` for a project called `myorg-core` that looks like this:

```yaml
encryptionsalt: secret-shhh!
config:
  myorg-core:project:
    Debug: true
    Name: "myorg-prototype-3"
    OrganizationName: "myorg"
    OrganizationNameShort: "mp"
    EnvironmentNameShort: "mp3"
    DefaultLocation: "us-central1"
    Regions:
      ca:
        Code: "ca"
        Global: true
        Location: "northamerica-northeast1"
        Cidr: "10.8.0.0/28"
      us:
        Code: "us"
        Location: "us-central1"
        Global: false
        Cidr: "10.9.0.0/28"
  gcp:project: myorg-prototype-3
  google-native:project: myorg-prototype-3
```

I basically want these values:

```yaml
    # Common Config Snippet
    Debug: true
    Name: "myorg-prototype-3"
    OrganizationName: "myorg"
    OrganizationNameShort: "mp"
    EnvironmentNameShort: "mp3"
    DefaultLocation: "us-central1"
    Regions:
      ca:
        Code: "ca"
        Global: true
        Location: "northamerica-northeast1"
        Cidr: "10.8.0.0/28"
      us:
        Code: "us"
        Location: "us-central1"
        Global: false
        Cidr: "10.9.0.0/28"
```

...in every project.

The issue is that right now I have to hand-duplicate these values, even though they _have_ to be the same for each project.

---

#### One Rough Idea

```yaml
encryptionsalt: secret-shhh!
config:
  myorg-core:project: !include ../common-project.yaml
```

And then obviously `../common.yaml` might be something like the contents of the "Common Config Snippet" above.

Hopefully I've conveyed the most basic concept here, but feel free to ask questions.  The overall idea here is that most projects end up working off of conventions, and so it's nice to avoid manual mistakes by not having to maintain the same values multiple times.

I could also see this feature being useful as a mechanism for CI/CD to inject values by templating a YAML file with deployment specifics and placing it in a well known location to be included.
