### ISSUE TITLE
config set-all breaks with mapped properties 

### ISSUE THREAD

**Issue by tomdavidson** [pulumi/pulumi#8401]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Setting mapped config via `config set-all` is not possible. Strings are converted to numbers and parent objects can end up undefined.

### Steps to reproduce

1. pulumi --config-file temp.yaml config set-all   --path --plaintext namespace:peering.account='3354230923499346' 
    --plaintext namespace:dns-account='3354230923499346' 
2. observe the peering.account is a number where as dns-account is a string.

Expected: 

Able to set all of the stacks config via `config set-all`, including mapped values.

Actual: 

Here is problematic portions of the config:
```yaml
 namespace:dns-account: "3354230923499346"
  namespace:peering:
    account: "3354230923499346"
  namespace:vpc-cidrs:
    default: 10.201.0.0/22
    private:
    - 10.170.0.0/16
    - 10.171.0.0/16
    - 10.172.0.0/16
    - 10.173.0.0/16
    public:
    - 10.201.4.0/22
    - 10.201.8.0/22
    - 10.201.12.0/22
    - 10.201.16.0/22
```

When using `config set-all` to set namespace:vpc-ciders, i.e.

> --path --plaintext okera:vpc-cidrs.default='10.201.0.0/22'
> --path --plaintext okera:vpc-cidrs.private[0]='10.170.0.0/16'
> --path --plaintext okera:vpc-cidrs.private[1]='10.171.0.0/16'
> --path --plaintext okera:vpc-cidrs.private[2]='10.172.0.0/16'
> --path --plaintext okera:vpc-cidrs.private[3]='10.173.0.0/16'
> --path --plaintext okera:vpc-cidrs.public[0]='10.201.4.0/22'
> --path --plaintext okera:vpc-cidrs.public[1]='10.201.8.0/22'
> --path --plaintext okera:vpc-cidrs.public[2]='10.201.12.0/22'
> --path --plaintext okera:vpc-cidrs.public[3]='10.201.16.0/22'

Yeilds:
```shell
    panic: fatal: A failure has occurred: missing required configuration variable 'namespace:vpc-cidrs'; run `pulumi config` to set
```

So if I try to configure the vpc-cidrs via a config file and the rest via set-all `--config-file ephemeral.yaml  config set-all --path --plaintext okera:peering.account='3354230923499346' `

Yeilds:
```shell
    panic: fatal: A failure has occurred: unable to unmarshall required configuration variable 'namespace:peering'; json: cannot unmarshal number into Go struct field peeringInfo.Account of type string
```
and what is curious is that  namespace:peering that is written to the config file is a number rather than a string, but other config items are not converted to a number:

```yaml
  namespace:dns-account: "3354230923499346"
  namespace:peering:
    account: 3354230923499346
```
vs
```yaml
  namespace:dns-account: "3354230923499346"
  namespace:peering:
    account: "3354230923499346"
```

Once I change it back to a string and only use the the config-file without set-all, the stack provisions just fine, without error.
