### ISSUE TITLE
Pulumi Github Action fails to find venv

### ISSUE THREAD

**Issue by boyntoni** [pulumi/pulumi#8765]
## Issue details

I'm attempting to use the Github Pulumi Action (preview) with a Python stack, and am unable to do so because the action is unable to location the virtual environment defined in the `Pulumi.yaml`.

Specifically, I am running into the following error:

```
Failed to resolve python version command: fork/exec /home/runner/work/repo/repo/serivce_a/infrastructure/component_a/venv/bin/python: no such file or directory
```

Locally, I am able to run all commands without issue.

I found a similar reported issue here https://github.com/pulumi/pulumi/issues/8460 but have not found a subsequent follow up

### Steps to reproduce

My project directory is as follows:

```
.
├── infrastructure
│   └──shared_stack
└── service_a
    ├── infrastructure
    │   └── component_a
    │       ├── __main__.py
    │       ├── ..other files for stack
```

1. Set up Github action as detailed: https://www.pulumi.com/docs/guides/continuous-delivery/github-actions/
2. Use `work-dir`  - `service_a/infrastructure/component_a`
3. Trigger action
4. Observe error

#### Pulumi.yaml

```
name: component_a
runtime:
  name: python
  options:
    virtualenv: venv
```

#### Github Workflow

```
name: PR workflow
on:  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    env:
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: pip install -r requirements.txt
        working-directory: ./service_a/infrastructure/component_a
      - name: Pulumi login
        run: pulumi login {s3_url}
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: component_a
          comment-on-pr: true
          work-dir: service_a/infrastructure/component_a
```

Expected: Stack is able to be preview
Actual: Unable to locate venv

**Comment by kstkrv** [comment]
Hello @boyntoni, was it solved?

**Comment by kstkrv** [comment]
@boyntoni, thank you for sharing!

**Comment by augustovictor** [comment]
I'm in a scenario where I have multiple folders. Each with different subgroups of resources which should be managed individually.
Something like this:
```
my-awesome-repo
- pulumi_modules_stuff
    - team_a
        - main.py
        - Pulumi.production.yaml
    - shared_resources
        - some_resource_specification.py
```

Say `pulumi_modules_stuff/team_a/main.py` uses something from `pulumi_modules_stuff/shared_resources/some_resource_specification.py`.

Configuring only pulumi's action's param `work-dir` did not work since `pulumi_modules_stuff/shared_resources/some_resource_specification.py` was not included in `sys.path`. Which threw a`No module named ...` exception. Then I had to set `PYTHONPATH` (as suggested by @boyntoni)

```
  pulumi-preview:
    name: "Pulumi preview"
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - run: |
          pip install pulumi pulumi-aws

      - uses: pulumi/actions@v3
        with:
          command: preview
          work-dir: pulumi_modules_stuff/team_a
          stack-name: production
          comment-on-pr: true
          cloud-url: s3://common-pulumi-bucket/my-stack-folder
          github-token: ${{ secrets.GITHUB_TOKEN }}
          diff: true
          color: always # Although this colors the output in the logs, the comment made by pulumi in the PR is full of encoding errors;
        env:
          PULUMI_CONFIG_PASSPHRASE: ""
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          PYTHONPATH: "/home/runner/work/my-awesome-repo/my-awesome-repo"

```
