### ISSUE TITLE
Destroy does not download plugins

### ISSUE THREAD

**Issue by chainlink** [pulumi/pulumi#8768]
## Issue details

When I try running `destroy` the necessary plugins are not downloaded (Running `up` downloads plugins and succeeds) 

Error message:

```
stderr: error: could not load plugin for kubernetes provider 'urn:pulumi:pulumi-preview::jupyter-test::pulumi:providers:kubernetes::k8sprovider': no resource plugin 'kubernetes' found in the workspace or on your $PATH
```
### Steps to reproduce

Github action setup:
```
jobs:
  up:
    name: remove-preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
         with:
           go-version: '^1.17.2'
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
      - uses: pulumi/actions@v3
        with:
          command: destroy
          stack-name: blah
          work-dir: infra
```

Expected: Destroy to run sucessfully
Actual: Destroy failed with above error
