### ISSUE TITLE
Azure Dev-Ops Pulumi@1 action hangs when running on Windows agent

### ISSUE THREAD

**Issue by StevenTCramer** [pulumi/pulumi#9035]
I have the following task in azure dev-ops and it runs fine on a Linux agent but it hangs on Windows agent:
```
        - task: Pulumi@1
          condition: or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual'))
          inputs:
            azureSubscription: "XYZ"
            command: "preview"
            cwd: "dev-ops/pulumi/XYZ"
            stack: "XYZ/Development"
```
Windows Agent output stops there:
![image](https://user-images.githubusercontent.com/357219/155349996-7563b336-1e3c-4a8e-873a-7b5a2b5b1c35.png)

If I go to the agents working directory and run the `pulumi preview ` it works fine.
