### ISSUE TITLE
Allow `pulumi config` to have different backends for storing configurations

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi#9313]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, Pulumi has its own configuration management system using `pulumi.<stack-name>.yaml`. However, this current model is limiting as only yaml file is supported.
Additionally, customers may not want to commit those configuration files into their source code as there may be  sensitive information (but not secrets) or they have specific requirements.

This request is to ask for the implementation of configuration providers similar to secrets providers. The `pulumi.<stack-name>.yaml` would only contain the _url_ where the configuration is stored.

As esxamples of providers:

* AWS S3: The service would store the referenced configuration and contain multiple key/pair values. It would rely on the user's credentials to access the stored configuration.
* AWS Secrets Manager: Similarly to S3, AWS Secrets Manager would store multiple key/pair values. It would rely on the user's credentials to access the stored configuration.

Having this feature would completely separate configuration from code while providing the same seemless experience using `pulumi config` and related functions.

As an alternative and instead of storing the whole configuration into the config provider, another syntax would be to replace the value and use a pointer to the provider and the location. Something like

```yaml
config:
  clientcert: aws://arn:aws:secretsmanager:us-west-2:123456789012:secret:MyClientCertificate-a1b2c3
  dbhost: aws://arn:aws:secretsmanager:us-west-2:123456789012:secret:MyTestDatabaseSecret-a1b2c3/host
  dbport: aws://arn:aws:secretsmanager:us-west-2:123456789012:secret:MyTestDatabaseSecret-a1b2c3/port
```

In the `clientcert` example above, the whole secret would be retrieve and served as the `clientcert` value. In the 2nd and 3rd example, the value would be picked out of a json or yaml formatted secret.

### Affected area/feature

* Pulumi CLI
