### ISSUE TITLE
[Go] RequireObject doesn't read config stack data

### ISSUE THREAD

**Issue by bogdan-matei** [pulumi/pulumi#9570]
### What happened?

Currently I'm setting up a couple of structures to handle the creation of Linux VM in Azure. Because I reuse the functions I want to provide the parameters to the LinuxVirtualMachineArgs via the config properties of my stack.

[RequireObject](https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v3@v3.32.1/go/pulumi/config?utm_source=gopls#Config.RequireObject) returns an empty object instead of mapping the values of the object to the structure.

### Steps to reproduce

Stack:

```yaml
config:
  azure-go:cluster:
    dnsName: wooferiuskubeadm
    workerNodes: 1
  azure-go:defaultNodeSku: Standard_DS2_v2
```
If you already have a stack
```bash
pulumi config set --path 'cluster.dnsName' 'wooferiuskubeadm'
pulumi config set --path 'cluster.workerNodes' 1
pulumi config set --path 'defaultNodeSku' 'Standard_DS2_v2'
```

Code:

```go
func main() {
  pulumi.Run(func(ctx *pulumi.Context) error {
    config := config.New(ctx,"")

    // Cluster values from stack
    var clusterConfig ClusterConfig
    config.RequireObject("cluster", &clusterConfig)

    fmt.Printf("Name: %s\n", clusterConfig.dnsName)
    fmt.Printf("Property: %s\n", config.Require("defaultNodeSku"))

    return nil
  })
}
```

### Expected Behavior

``clusterConfig`` variable is populated with the values from the configuration of the stack.

### Actual Behavior

```yaml
Diagnostics:
  pulumi:pulumi:Stack (azure-go-dev):
    Name:
    Property: Standard_DS2_v2
```

While the Require works as expected, the RequiredObject doesn't update my object.

### Versions used

CLI          
Version      3.32.1
Go Version   go1.18.1
Go Compiler  gc

Plugins
NAME          VERSION
azure         4.42.0
azure-native  1.64.0
go            unknown

Host     
OS       darwin
Version  11.5.2
Arch     x86_64

### Additional context

I've also checked the examples from the official documentation [page](https://www.pulumi.com/docs/intro/concepts/config/#structured-configuration).

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
