### ISSUE TITLE
`pulumi convert` support for arbitrary output types in C#/dotnet

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#9642]
Converting a simple YAML program such as this produces invalid code in C#:

```yaml
name: random
runtime: yaml
outputs:
  arrVar:
  - fizz
  - buzz
```

The generated code incorrectly types `arrVar` as an `Output<string>`.
