### ISSUE TITLE
`pulumi convert` support for string, array, non-Output properties

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#9692]
When running `pulumi convert` on a YAML program like the one below, the generated Go is invalid as `ctx.Export` expects an Output:

```yaml
name: random
runtime: yaml
outputs:
  strVar: "foo"
  arrVar:
  - fizz
  - buzz
  readme:
    Fn::ReadFile: ./Pulumi.README.md
```

```go
package main

import (
	"io/ioutil"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func readFileOrPanic(path string) pulumi.StringPtrInput {
	data, err := ioutil.ReadFile(path)
	if err != nil {
		panic(err.Error())
	}
	return pulumi.String(string(data))
}

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		ctx.Export("strVar", "foo")
		ctx.Export("arrVar", []string{
			"fizz",
			"buzz",
		})
		ctx.Export("readme", readFileOrPanic("./Pulumi.README.md"))
		return nil
	})
}
```
