### ISSUE TITLE
`pulumi convert` fails on `Fn::Invoke`s without arguments

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#9896]
If I try to convert a program that has a `Fn::Invoke` without any arguments:

```yaml
name: yamyam
runtime: yaml
variables:
  foo:
    Fn::Invoke:
      Function: aws:getAvailabilityZones
```

I get a failure:

`
error: could not load yaml program: failed to load YAML program, internal error: program.pp:0,13-66: missing second arg; missing second arg
`

This unfortunately leaks the internal machinery of how the conversion works (`program.pp` is the PCL IR form). I was able to hack the CLI to print out the PCL which helped me narrow down the root cause (this was happening in a 200 line YAML file):

The PCL IR is:

```
foo = invoke("aws:index/getAvailabilityZones:getAvailabilityZones")
```

Adding an empty arguments map:

```yaml
name: yamyam
runtime: yaml
variables:
  foo:
    Fn::Invoke:
      Function: aws:getAvailabilityZones
      Arguments:
```

Did not work, as it triggered a panic:

```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   3.35.0-alpha.1655483272+2a07ed75.dirty
Go Version:       go1.17.4
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x56fa1e0, 0x6d6d9a0})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/ast.(*TemplateDecl).NewDiagnosticWriter(0x0, {0x5de5320, 0xc0001aa010}, 0x0, 0x1)
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/ast/template.go:422 +0x45
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.Eject({0xc000058064, 0x40d8686}, {0x0, 0x0})
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen/eject.go:30 +0xb4
main.newConvertCmd.func1(0xf, {0xc00022b500, 0xc00079fd90, 0x41f0105})
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/convert.go:81 +0x266
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000bd4280, {0xc000597f40, 0x0, 0x4})
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc000bd4280, {0xc000597f00, 0x4, 0x4})
	/Users/joeduffy/dev/code/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc0009d2c80)
	/Users/joeduffy/dev/code/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/joeduffy/dev/code/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45
```

But adding a valid set of arguments finally did the trick:

```yaml
name: yamyam
runtime: yaml
variables:
  foo:
    Fn::Invoke:
      Function: aws:getAvailabilityZones
      Arguments:
        excludeNames: []
```

We should be able to handle invokes that lack arguments altogether as well as empty argument maps.
