### ISSUE TITLE
`pulumi convert` drops `Fn::ReadFile` for Go language target

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#9981]
If I convert a simple YAML file that contains a `Fn::ReadFile` to Go, such as

```yaml
name: fnrf
runtime: yaml
variables:
  key:
    Fn::ReadFile: key.pub
```

The resulting Go program is missing the actual declaration of the `key` variable.

Presumably it did _something_, since I see this at the top of the file, however:

```go
func readFileOrPanic(path string) pulumi.StringPtrInput {
        data, err := ioutil.ReadFile(path)
        if err != nil {
                panic(err.Error())
        }
        return pulumi.String(string(data))
}
```

But yet, no `key` variable, so the conversion definitely wasn't correct/complete.
